### ISSUE TITLE
Color option

### ISSUE THREAD

**Issue by dxcore35** [FlorianWoelki/obsidian-iconize#124]
I searched the Obsidian forum and Discord and I cannot find any good solution how to change color of individual folder except going into CSS and adding fixed rules for folder name. 

# Request feature

Expect adding of the icon for folder and file add option to:

- chose any color that will be applied to the icon (for individual folder!) 
- chose if the color will be applied only to icon or also to folder name (color of text)
- chose for example the children files to just have color inhirited not the icon, but also add inhirit all (icon + color)

All these features work with individual folders, meaning I can have different folders with differnet color.

# Benefit

Your plugin will become one solution for all visual tweaking of the folder and files. And it will be the only one, as there isn't anything like that.

**Comment by Thomas-Schmall** [comment]
@dxcore35 There is the [File Color plugin](https://github.com/ecustic/obsidian-file-color) that does that very well.
This one also colors the icon from this plugin here.

I think it might be unnecessary or even tricky to duplicate that functionality here.

**Comment by FlorianWoelki** [comment]
This is now available in [v2.9.0](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.9.0).

**Comment by veitch123** [comment]
Amazing!!
