### ISSUE TITLE
Allow custom icon rules defined by path in the vault rather than individual name

### ISSUE THREAD

**Issue by KillyMXI** [FlorianWoelki/obsidian-iconize#172]
> **Is your feature request related to a problem? Please describe.**

I can't have files in a folder to get automatically inferred icons that are different from containing folder icon but depend on that folder (or its ascendants) name.

> **Describe the solution you'd like**

Regular expressions in Custom Icon Rules should be applied to the path within vault, not only the terminal item.

Preferably, the path should be platform-independent - `/`, not `\` as path separators even on Windows. Or this should be an option.

> **Describe alternatives you've considered**

Currently, it is only possible to assign icons per item (file or folder) specifically (manually or through a rule by name) or via inheritance.

I find the combination of these confusing and less flexible than it could've been.

Inheritance can potentially be replaced with a custom rule addition like `^<folder path>/[^/]+$`, albeit this might simplify the design by the cost of user experience - not everyone is familiar with regexes.

**Comment by FlorianWoelki** [comment]
Thanks for your request. So you mean something like a mix between inheritance icons and custom rules? Because inheritance icons already exist but you cannot specify the specific files or folders inside of them.

**Comment by KillyMXI** [comment]
I mean make custom rules more powerful (check full path within vault instead of just the name).
As a side effect, it also becomes a more general case of what inheritance can do.

**Comment by nevir** [comment]
I'm also interested in this - similarly, I'd like to be able to have the icon rules have the ability to match the entire path, rather than just file name

For example: I have a daily folder that contains my daily plan, as well as notes for each meeting that occurred that day. I'd love for meetings to have a calendar icon, while the plan has something else.

**Comment by FlorianWoelki** [comment]
This has been released in [v2.3.0](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.3.0).

I hope that fixes your problem and solves your use case.
