### ISSUE TITLE
Automatic icon inheritance

### ISSUE THREAD

**Issue by rben01** [FlorianWoelki/obsidian-iconize#205]
**Is your feature request related to a problem? Please describe.**
I have lots of folders with icons. I'd like for every folder to have its icon-less children inherit its icon, with nested folders taking priority over their parents. But doing this on a folder-by-folder basis is incredibly tedious.

**Describe the solution you'd like**
A setting to automatically apply the “inherit icon” setting to folders, applying their current icon to all of their descendants. Child folders’ icons would take precedence over parents‘.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by FlorianWoelki** [comment]
I'll close this for now, because inheritance functionality will be deprecated in `v2.10.0`. By now, you can achieve everything with custom rules as well.
