### ISSUE TITLE
Opening the same file in the same tab a second time will reset the tab icon

### ISSUE THREAD

**Issue by 5HT2** [FlorianWoelki/obsidian-iconize#208]
**Describe the bug**
Opening the same file in the same tab a second time will reset the tab icon.

**To Reproduce**
1. Open a file
2. Open it again, in the same tab

**Expected behavior**
It doesn't reset the icon

**Screenshots**

https://github.com/FlorianWoelki/obsidian-icon-folder/assets/17222512/2b50ec3b-10ca-4b8b-b0f0-6963be6b812c

**Additional context**
This is a problem because if I use the shortcut to open today's note twice it'll reset the icon :(

**Comment by khanhtoan529** [comment]
I have same issue here

**Comment by FlorianWoelki** [comment]
This has been released in [v2.3.0](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.3.0).
