### ISSUE TITLE
[BUG]: Conflict between inheritance & custom rules

### ISSUE THREAD

**Issue by Lisandra-dev** [FlorianWoelki/obsidian-iconize#225]
**Describe the bug**
I have a rule that apply to all markdown files (`.md`). 
If I try to set an inheritance icon:
- First I have duplication with the rule icon and the inherited icon.
- If I reload, I get the ruled icon, not the inherited. 

**To Reproduce**
1. Create a custom "general" rules, for ie `\.md$` files.
2. Inherit an icon on file in a folder
3. See duplication
4. Reload Obsidian
5. See that only the ruled icon is applied

**Expected behavior**
Normally, the inherited icon must be applied, not the ruled ?

**Screenshots**
https://github.com/FlorianWoelki/obsidian-icon-folder/assets/30244939/57d65b12-2d52-4b3a-afdd-890f77a70b08

**Additional context**
I tried custom rules, but because of the order, the `\.md` is applied in last and result in a strange "blink" between the icon

**Comment by FlorianWoelki** [comment]
This has been released in [v2.3.0](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.3.0).
