### ISSUE TITLE
Auto-addition of the icon depending on the type

### ISSUE THREAD

**Issue by avraam-inside** [FlorianWoelki/obsidian-iconize#236]
Hi!

Isn't it possible to add auto-addition of the default icon depending on the type - folder or file? Without this, there is no point in using this wonderful extension...

**Comment by FlorianWoelki** [comment]
You might check out our [custom rules](https://github.com/FlorianWoelki/obsidian-iconize?tab=readme-ov-file#custom-rules-for-automatically-adding-icons) implementation. Does this solve your problem?

**Comment by avraam-inside** [comment]
Custom rules are tied to folder and file NAMES (I only see the setting using a regular expression)

I'm talking about defining a rule BY the TYPE of object - is it a file or a folder

**Comment by FlorianWoelki** [comment]
> Custom rules are tied to folder and file NAMES (I only see the setting using a regular expression)
> 
> I'm talking about defining a rule BY the TYPE of object - is it a file or a folder

There is the functionality of setting the type of object:
<img width="240" alt="image" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/20746070/4e0c6f64-1988-4f7e-a5a0-fe111192f663">

**Comment by avraam-inside** [comment]
Yes, it really worked! Thanks!
I previously Googled here: https://forum.obsidian.md/t/how-to-auto-add-icon-to-folders-and-notes/51809/2 - and as you can see, the people also did not understand how to do it...

I think it would be nice to modify the documentation, otherwise I could not find an answer to such a simple request on my own (

**Comment by FlorianWoelki** [comment]
> Yes, it really worked! Thanks! I previously Googled here: https://forum.obsidian.md/t/how-to-auto-add-icon-to-folders-and-notes/51809/2 - and as you can see, the people also did not understand how to do it...
> 
> I think it would be nice to modify the documentation, otherwise I could not find an answer to such a simple request on my own (

Good thought! Could you please describe quickly what Regex you've used and what options you've applied? Then I'll adapt the README accordingly.

**Comment by avraam-inside** [comment]
@FlorianWoelki of course!
just dot-s))0
![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/52919010/11867344-1e7a-4f3a-8d68-d31ef809648d)
This solved my issue

**Comment by FlorianWoelki** [comment]
> @FlorianWoelki of course!
> 
> just dot-s))0
> 
> ![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/52919010/11867344-1e7a-4f3a-8d68-d31ef809648d)
> 
> This solved my issue

Was kind of obvious :D I've adapted the README to explain how to set a default icon.
