### ISSUE TITLE
Tabler icons not found after updating plugin

### ISSUE THREAD

**Issue by rben01** [FlorianWoelki/obsidian-iconize#239]
**Describe the bug**
All of my folders’ icons are Tabler icons. Despite having the Tabler icon pack installed, and its ZIP present in `.obsidian/plugins/obsidian-icon-folder/icons`, when I start up Obsidian, I get a million notifications saying “icon not found”, and icons are not shown for my vault’s folders.

**To Reproduce**
1. Install the Tabler icon pack
1. Set many folders’ icons to Tabler icons
2. Fast forward several months
3. Update the plugin after not updating it for a few months
4. Restart Obsidian
5. Bug: a million “icon missing” notifications, and icons aren't visible

**Expected behavior**
No issue; folder icons remain visible

**Screenshots**
It is almost certainly related to this, the contents of `.obsidian/plugins/obsidian-icon-folder`:

```
    - .
10.0k ├── data.json
    - ├── icons
    - │  ├── tabler-icons
  569 │  │  └── Template.svg
  28M │  └── tabler-icons.zip
 803k ├── main.js
  309 ├── manifest.json
 2.3k └── styles.css
```

After updating, it looks like the set of icons was replaced with a ZIP, but the icons in use were not extracted into a folder correctly. The file `tabler-icons/Template.svg` was only created when I set the icon of a folder _after_ updating.

**Additional context**
The data in `data.json` is still intact, so in theory this could be fixed by running through that file and extracting all the necessary icons.

**Comment by FlorianWoelki** [comment]
I don't quite understand it. The plugin never removes or deletes any icons when they are updated. Normally, after the recent update, you should've just downloaded the tabler icons pack as a zip and everything would have worked.

What you could do to resolve the issue, is just extracting all the icons into the tabler icons directory.

**Comment by rben01** [comment]
Looks like it may be related to the change [here (#153)](https://github.com/FlorianWoelki/obsidian-iconize/issues/153) not taking into account the icons that are needed in the vault before cleaning things up.

**Comment by FlorianWoelki** [comment]
Got it. I think I could make something asynchronous in the background that checks in the beginning, if all used icons are downloaded/added correctly. That would fix some things.

I'll create a new issue for that and close this for now!

**Comment by FlorianWoelki** [comment]
Keeping track of it at #242
