### ISSUE TITLE
Background check for missing icons

### ISSUE THREAD

**Issue by FlorianWoelki** [FlorianWoelki/obsidian-iconize#242]
This feature will include a background check, which checks if all added icons are actually added and downloaded correctly (exist in the icon pack directory). This will fix minor syncing issue, but also unwanted missing icons.

**Comment by paschalis** [comment]
New zip-folder sync was a very welcome addition, however, this is necessary.
If icons are missing, it should auto-extract them and make them available.

**Comment by FlorianWoelki** [comment]
This has been added in the [newest release](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.4.0).

**Comment by paschalis** [comment]
Unfortunately, after enabling the sync setting, we still get: `Icon file <filename> could not be found.`,
and the icon does not get downloaded.

This is after enabling the setting and restarting Obsidian,

**Comment by FlorianWoelki** [comment]
> Unfortunately, after enabling the sync setting, we still get: `Icon file <filename> could not be found.`, and the icon does not get downloaded.
> 
> This is after enabling the setting and restarting Obsidian,
> 
> EDIT: one thing it does not check for sure, is when the icons come from a "Custom icon rule". So these are left out.

Cannot reproduce it with the newest version. Custom icon rules are working fine as well.
This is how my `icons` directory look like:
<img width="235" alt="image" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/20746070/2e41780c-0b17-4d26-9efd-0a6925f64110">

When I remove `icon-brew` and `lucide-icons` directories and restart Obsidian, all icons (file/folder icons, custom rules, inheritance) are added.
