### ISSUE TITLE
Phantom icons, possibly misidentified icon packs

### ISSUE THREAD

**Issue by AbFarid** [FlorianWoelki/obsidian-iconize#245]
**Describe the bug**
I deleted all my individual icons and re-downloaded them as packs.
After downloading all the packs back, I have 3 icons that seem to have the pack name and no icon to them.

**To Reproduce**
1. Download all the icon packs (only Fab packs might be enough)
2. Trigger the icon selection popup
3. See phantom icons

**Screenshot**
<img width="628" alt="image" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/8946919/411c32ec-169b-423b-bc19-fdae252508f5">

I don't really want to re-download the packs, cause then I will have to set all my icons again, and I have just done that. So hoping there's a way to fix this without doing that.

**Comment by FlorianWoelki** [comment]
Thanks for the bug report! Is this related to #241?

**Comment by AbFarid** [comment]
I suppose it is, my bad.
I looked at the recent issues and didn't see anything that I thought was related to this.
You also mentioned that it has already been fixed, so this can be closed.

**Comment by FlorianWoelki** [comment]
> I suppose it is, my bad.
> 
> I looked at the recent issues and didn't see anything that I thought was related to this.
> 
> You also mentioned that it has already been fixed, so this can be closed.

No worries. Exactly. Still waiting for Obsidian to accept the renaming of the plugin :D
