### ISSUE TITLE
Icons not showing up at all

### ISSUE THREAD

**Issue by Skarlso** [FlorianWoelki/obsidian-iconize#247]
**Describe the bug**
Hello.

I installed the plugin and downloaded one of the pre-set fonts:

<img width="1099" alt="Screenshot 2023-09-20 at 10 32 43" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/182850/587ec2a9-8860-4098-8f3a-5c5bcb6ffec2">

I did delete everything before hand and this is my plugins folder:

```
plugins ls -l
total 0
drwxr-xr-x@ 5 skarlso  staff  160 Feb 10  2023 buttons
drwxr-xr-x@ 5 skarlso  staff  160 Jul  5 21:40 calendar
drwxr-xr-x@ 5 skarlso  staff  160 Feb 10  2023 cm-editor-syntax-highlight-obsidian
drwxr-xr-x@ 6 skarlso  staff  192 Sep 19 17:18 dataview
drwxr-xr-x@ 5 skarlso  staff  160 May 11 10:29 heatmap-calendar
drwxr-xr-x@ 6 skarlso  staff  192 Sep 20 09:29 obsidian-activity-history
drwxr-xr-x@ 5 skarlso  staff  160 Jul  5 20:55 obsidian-dangling-links
drwxr-xr-x@ 5 skarlso  staff  160 May 10 14:22 obsidian-emoji-toolbar
drwxr-xr-x@ 6 skarlso  staff  192 Sep 19 17:19 obsidian-excalidraw-plugin
drwxr-xr-x@ 6 skarlso  staff  192 Sep 20 10:07 obsidian-extract-pdf-highlights
drwxr-xr-x@ 7 skarlso  staff  224 Sep 20 10:31 obsidian-icon-folder
drwxr-xr-x@ 6 skarlso  staff  192 Sep 20 10:05 obsidian-projects
drwxr-xr-x@ 5 skarlso  staff  160 Sep 19 17:18 obsidian-rollover-daily-todos
drwxr-xr-x@ 6 skarlso  staff  192 Sep 19 17:19 obsidian-tasks-plugin
drwxr-xr-x@ 5 skarlso  staff  160 Feb 10  2023 obsidian-tracker
```

And inside the icons folder there is an icons folder and I can see the downloaded font:

```
➜  obsidian-icon-folder tree
.
├── data.json
├── icons
│   └── font-awesome-regular.zip
├── main.js
├── manifest.json
└── styles.css

2 directories, 5 files
```

Yet, I still don't see any folder icons. :(

<img width="375" alt="Screenshot 2023-09-20 at 10 34 13" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/182850/18ac875d-6c78-4cc7-9453-e197903bea32">

Am I missing something or didn't include some step or something?

I'm running Obsidian Version 1.4.13 (Installer 1.4.13).

I tried turning off the template that I'm using that might be overwriting the folder view, but that didn't help. I also tried turning off all other plugins as well.

**Comment by FlorianWoelki** [comment]
Thanks for trying out the plugin.

You need to set the icon for yourself (right click on file/folder and then change icon). At the moment there is no "automatic" icon functionality.

**Comment by FlorianWoelki** [comment]
> 🤦 
> 
> 
> 
> I am so sorry. Thank you for taking the time to reply and not just tell me to RTFM. :D Which I should have. :D
> 
> 
> 
> Thank you!

All good! :D I am always happy to help :)
