### ISSUE TITLE
Add Icon Hotkey

### ISSUE THREAD

**Issue by ianTevesAcc** [FlorianWoelki/obsidian-iconize#249]
**Describe the solution you'd like**
I'd like a feature which when a hotkey is pressed "ctrl + alt + I" activates icon change for current note / folder selected.

**Describe alternatives you've considered**
Only alternative right now is clicking file and clicking change icon.

**Comment by MayneX** [comment]
Just adding to the command palette would already worked for me. Hotkeys might be assigned at will

**Comment by FlorianWoelki** [comment]
this has been implemented in the latest version of Iconize.
