### ISSUE TITLE
How to change color of icons in icon selection window? 

### ISSUE THREAD

**Issue by pinetreemoonlight** [FlorianWoelki/obsidian-iconize#250]
I am using a custon theme (Anupuccin), unfortunately, with it enabled (light theme), icons are very hard to see in the icon preview/selection window (see pic). I could not figure out how to change the color of the icon previews. Any help is appreciated.

![Screenshot 2023-09-23 120852](https://github.com/FlorianWoelki/obsidian-iconize/assets/115622756/29a99d01-66f8-4d25-bbb1-ad02cb9d3ce4)

**Comment by FlorianWoelki** [comment]
At the moment it is not possible to directly change the icon color in the selection modal.
I'll update the CSS for this plugin to respect the CSS from the theme. Thank you for the bug report!

**Comment by FlorianWoelki** [comment]
This has now been resolved in [v2.3.1](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.3.1). Thank you for the report!
