### ISSUE TITLE
Icons Detached

### ISSUE THREAD

**Issue by mjain234** [FlorianWoelki/obsidian-iconize#251]
**Describe the bug**
As you can in the image provided, the icons gets detached from its position. I don't know how it's happenwd because I have been using this ICON folder plugin since 5 days and this just happened suddenly.

**Screenshots**
![Screenshot_20230923-220802.png](https://github.com/FlorianWoelki/obsidian-iconize/assets/70900505/23a6a114-d980-4a1d-8dac-42f2c8213775)

**Comment by FlorianWoelki** [comment]
You can simply adjust the margin in the settings.
