### ISSUE TITLE
[BUG]: Shared icon pack doesn't appear

### ISSUE THREAD

**Issue by Lisandra-dev** [FlorianWoelki/obsidian-iconize#256]
**Describe the bug**
My icon pack doesn't appear in the settings and I can't set a icon from them in a new file. Old icon are okay, but the folder doesn't appear in the settings.

**Logs** 
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at getExtraPath (plugin:obsidian-icon-folder:262:17)
    at eval (plugin:obsidian-icon-folder:521:23)
    at Generator.next (<anonymous>)
    at eval (plugin:obsidian-icon-folder:31:71)
    at new Promise (<anonymous>)
    at __awaiter (plugin:obsidian-icon-folder:27:12)
    at getLoadedIconsFromZipFile (plugin:obsidian-icon-folder:519:60)
    at eval (plugin:obsidian-icon-folder:513:35)
    at Generator.next (<anonymous>)
    at fulfilled (plugin:obsidian-icon-folder:28:58)
```

**Screenshot**
![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/30244939/cf69abfd-5eb3-490d-b4c6-cdf611fe5a0c)
![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/30244939/4b74ceee-2f62-405a-a3eb-b20dbca5457a)

**Comment by Lisandra-dev** [comment]
Can be fixed with editing https://github.com/FlorianWoelki/obsidian-iconize/blob/7ac4c14898aa332cbffba509ebc8a98930432f9e/src/iconPacks.ts#L68
To:
```
return path?.length === 0 ? undefined : path;
```

**Comment by FlorianWoelki** [comment]
Did you create a zip file for your custom icon pack?

**Comment by Lisandra-dev** [comment]
Only iconify, the one that doesn't disappear, has not a zip.

**Comment by FlorianWoelki** [comment]
Feel free to checkout the fix :)

**Comment by Lisandra-dev** [comment]
Hm, on the new version, I can't build because I have a lot error in the code: 

```
The argument of type 'this' is not attributable to the parameter of type 'Plugin'.
  The 'IconFolderPlugin' type does not have the following properties of the 'Plugin' type: description, filename, length, name and 2 others.ts(2345)
  ```
For example!

**Comment by Lisandra-dev** [comment]
Seems fixed :>
