### ISSUE TITLE
Reinstalling icons packs as recommended by plugin migration removes existing icons from folders

### ISSUE THREAD

**Issue by serpro69** [FlorianWoelki/obsidian-iconize#257]
**Describe the bug**

After upgrading the plugin from 2.1.2 to 2.3.1, I got a prompt in obsidian to re-install all existing icon packs to use the new sync functionality.
Doing that removed all the icons files from the vault, and consequently all my folders didn't have icons anymore.

To fix that I had to manually assign an icon to each folder again.

**To Reproduce**

- Upgrade from an earlier version (pre-iconize)
- Remove icon packs in plugin settings and re-install them
- Restart obsidian
- All folders which had icons are now without icons

**Expected behavior**

Iconize should check which icons are in use and not remove them.
Otherwise migrating to a new version becomes a pain. I'm dreading the idea of updating the plugin in my other vault where I have several dozen folders with icons :D 

**Screenshots**

n/a

**Additional context**

n/a

**Comment by KrzysiekWu** [comment]
**Describe the bug**
In addition to addressing this specific bug that occurs after an upgrade, the solution should also consider other reasons for failures when attempting to locate extracted icons from the icon pack archive. This includes scenarios such as deleting the icon pack from the interface, as well as other issues like previous bugs encountered when switching to archived icon packs or simply the removal of files from the specified "icons" folder by the user or as a result of Obsidian Synchronization  shortcommings.

**Quick workaround:**
- Carefully extract cherry-picked icons from the list of icons in use, or alternatively, extract all icons from the archives (although this will revert the improved method of storing such icons).

**Expected behavior:**
- Iconize should iterate over the icons used by the user from "data.json" and extract them.

**Comment by FlorianWoelki** [comment]
> **Describe the bug** In addition to addressing this specific bug that occurs after an upgrade, the solution should also consider other reasons for failures when attempting to locate extracted icons from the icon pack archive. This includes scenarios such as deleting the icon pack from the interface, as well as other issues like previous bugs encountered when switching to archived icon packs or simply the removal of files from the specified "icons" folder by the user or as a result of Obsidian Synchronization shortcomings.
> 
> **Quick workaround:**
> 
> * Carefully extract cherry-picked icons from the list of icons in use, or alternatively, extract all icons from the archives (although this will revert the improved method of storing such icons).
> 
> **Expected behavior:**
> 
> * Iconize should iterate over the icons used by the user from "data.json" and extract them from the archives like it does while attaching the icon in the nav pane.

Please create a new issue, if the latest release does not fulfil this requirement.



> **Describe the bug**
> 
> After upgrading the plugin from 2.1.2 to 2.3.1, I got a prompt in obsidian to re-install all existing icon packs to use the new sync functionality. Doing that removed all the icons files from the vault, and consequently all my folders didn't have icons anymore.
> 
> To fix that I had to manually assign an icon to each folder again.
> 
> **To Reproduce**
> 
> * Upgrade from an earlier version (pre-iconize)
> * Remove icon packs in plugin settings and re-install them
> * Restart obsidian
> * All folders which had icons are now without icons
> 
> **Expected behavior**
> 
> Iconize should check which icons are in use and not remove them. Otherwise migrating to a new version becomes a pain. I'm dreading the idea of updating the plugin in my other vault where I have several dozen folders with icons :D
> 
> **Screenshots**
> 
> n/a
> 
> **Additional context**
> 
> n/a

You can try the [newest update](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.4.0) now. If icons are missing, you can enable the background checker. This will add all the missing icons.

I'll close this issue for now.

**Comment by serpro69** [comment]
This seems like it doesn't work entirely.
After removing all old icon packs, and adding new ones (zip files), enabling the 'background check' option and restarting the vault, I still see some (though not all) icons missing

Each time I re-open obsidian, I'm getting "Looks like you don't have ... icon pack installed" for a bunch of icons (the missing ones?) 
I suspect the problem is that is does the "background check" before the icons are actually loaded.

In the console I see : 

```
loaded icon pack boxicons (1634)
plugin:obsidian-icon-folder:554 loaded icon pack font-awesome-brands (472)
plugin:obsidian-icon-folder:554 loaded icon pack font-awesome-regular (163)
plugin:omnisearch:50 Omnisearch - Loading index from cache: 23967.98388671875 ms
plugin:omnisearch:50 Omnisearch - Indexing total time: 24079.374755859375 ms
plugin:obsidian-excalidraw-plugin:79 Initialized Excalidraw Image Cache
plugin:obsidian-icon-folder:554 loaded icon pack font-awesome-solid (1390)
plugin:obsidian-icon-folder:554 loaded icon pack icon-brew (284)
plugin:obsidian-icon-folder:554 loaded icon pack lucide-icons (1257)
plugin:obsidian-icon-folder:554 loaded icon pack remix-icons (2537)
plugin:obsidian-icon-folder:554 loaded icon pack simple-icons (2715)
plugin:obsidian-icon-folder:554 loaded icon pack tabler-icons (4673)
plugin:obsidian-icon-folder:3420 Icon file FasArrowRightFromBracket could not be found.
eval @ plugin:obsidian-icon-folder:3420
plugin:obsidian-icon-folder:3420 Icon file FasFolderTree could not be found.
eval @ plugin:obsidian-icon-folder:3420
plugin:obsidian-icon-folder:3420 Icon file SiLinode could not be found.
eval @ plugin:obsidian-icon-folder:3420
plugin:obsidian-icon-folder:3420 Icon file RiSunLine could not be found.
eval @ plugin:obsidian-icon-folder:3420
plugin:obsidian-icon-folder:3420 Icon file FasFileCode could not be found.
eval @ plugin:obsidian-icon-folder:3420
plugin:obsidian-icon-folder:3420 Icon file FasTextHeight could not be found.
eval @ plugin:obsidian-icon-folder:3420
plugin:obsidian-icon-folder:3420 Icon file FasListCheck could not be found.
eval @ plugin:obsidian-icon-folder:3420
plugin:obsidian-icon-folder:3420 Icon file FasCircleInfo could not be found.
eval @ plugin:obsidian-icon-folder:3420
plugin:obsidian-icon-folder:3420 Icon file FasCalendarDays could not be found.
eval @ plugin:obsidian-icon-folder:3420
plugin:obsidian-icon-folder:3420 Icon file FarNoteSticky could not be found.
eval @ plugin:obsidian-icon-folder:3420
plugin:obsidian-icon-folder:3420 Icon file FasListCheck could not be found.
eval @ plugin:obsidian-icon-folder:3420
plugin:obsidian-icon-folder:3420 Icon file FasCircleQuestion could not be found.
eval @ plugin:obsidian-icon-folder:3420
plugin:obsidian-icon-folder:3420 Icon file FasFileImage could not be found.
eval @ plugin:obsidian-icon-folder:3420
plugin:obsidian-icon-folder:3420 Icon file FasFilePdf could not be found.
eval @ plugin:obsidian-icon-folder:3420
plugin:obsidian-icon-folder:3420 Icon file RiHammerFill could not be found.
eval @ plugin:obsidian-icon-folder:3420
plugin:obsidian-icon-folder:3420 Icon file RiCpuLine could not be found.
eval @ plugin:obsidian-icon-folder:3420
plugin:obsidian-icon-folder:3420 Icon file RiGithubLine could not be found.
eval @ plugin:obsidian-icon-folder:3420
plugin:obsidian-icon-folder:3420 Icon file RiShieldFill could not be found.
eval @ plugin:obsidian-icon-folder:3420
plugin:obsidian-icon-folder:3420 Icon file FabGithubAlt could not be found.
eval @ plugin:obsidian-icon-folder:3420
plugin:obsidian-icon-folder:3420 Icon file RiGithubFill could not be found.
eval @ plugin:obsidian-icon-folder:3420
plugin:obsidian-icon-folder:3420 Icon file RiProfileLine could not be found.
eval @ plugin:obsidian-icon-folder:3420
plugin:obsidian-icon-folder:3420 Icon file FasUserShield could not be found.
eval @ plugin:obsidian-icon-folder:3420
plugin:obsidian-icon-folder:3420 Icon file RiTestTubeLine could not be found.
eval @ plugin:obsidian-icon-folder:3420
plugin:obsidian-icon-folder:3420 Icon file FasUmbrellaBeach could not be found.
eval @ plugin:obsidian-icon-folder:3420
plugin:obsidian-icon-folder:3420 Icon file FasPuzzlePiece could not be found.
eval @ plugin:obsidian-icon-folder:3420
2plugin:obsidian-icon-folder:3420 Icon file RiShieldFill could not be found.
eval @ plugin:obsidian-icon-folder:3420
plugin:obsidian-icon-folder:3420 Icon file FasQuoteLeft could not be found.
eval @ plugin:obsidian-icon-folder:3420
plugin:obsidian-icon-folder:3420 Icon file FasTableColumns could not be found.
eval @ plugin:obsidian-icon-folder:3420
plugin:obsidian-icon-folder:3420 Icon file FasNoteSticky could not be found.
eval @ plugin:obsidian-icon-folder:3420
plugin:obsidian-icon-folder:3420 Icon file FasSquarePollHorizontal could not be found.
eval @ plugin:obsidian-icon-folder:3420
plugin:obsidian-icon-folder:3420 Icon file RiFilmLine could not be found.
eval @ plugin:obsidian-icon-folder:3420
plugin:obsidian-icon-folder:3420 Icon file FasFileExport could not be found.
eval @ plugin:obsidian-icon-folder:3420
plugin:obsidian-icon-folder:3420 Icon file FasLaptopCode could not be found.
eval @ plugin:obsidian-icon-folder:3420
plugin:obsidian-icon-folder:3420 Icon file RiSlideshowLine could not be found.
eval @ plugin:obsidian-icon-folder:3420
plugin:obsidian-icon-folder:3420 Icon file FarFileZipper could not be found.
eval @ plugin:obsidian-icon-folder:3420
plugin:obsidian-icon-folder:3420 Icon file FasHeartPulse could not be found.
eval @ plugin:obsidian-icon-folder:3420
plugin:obsidian-icon-folder:3420 Icon file FasAppleWhole could not be found.
eval @ plugin:obsidian-icon-folder:3420
plugin:obsidian-icon-folder:3420 Icon file FasPersonSwimming could not be found.
eval @ plugin:obsidian-icon-folder:3420
plugin:obsidian-icon-folder:3420 Icon file RiFileList3Fill could not be found.
eval @ plugin:obsidian-icon-folder:3420
plugin:obsidian-icon-folder:3420 Icon file RiSpaceShipFill could not be found.
eval @ plugin:obsidian-icon-folder:3420
2plugin:obsidian-icon-folder:3420 Icon file RiArchiveFill could not be found.
```

**Comment by FlorianWoelki** [comment]
> This seems like it doesn't work entirely. After removing all old icon packs, and adding new ones (zip files), enabling the 'background check' option and restarting the vault, I still see some (though not all) icons missing
> 
> Each time I re-open obsidian, I'm getting "Looks like you don't have ... icon pack installed" for a bunch of icons (the missing ones?) I suspect the problem is that is does the "background check" before the icons are actually loaded.
> 
> In the console I see :
> 
> ```
> loaded icon pack boxicons (1634)
> plugin:obsidian-icon-folder:554 loaded icon pack font-awesome-brands (472)
> plugin:obsidian-icon-folder:554 loaded icon pack font-awesome-regular (163)
> plugin:omnisearch:50 Omnisearch - Loading index from cache: 23967.98388671875 ms
> plugin:omnisearch:50 Omnisearch - Indexing total time: 24079.374755859375 ms
> plugin:obsidian-excalidraw-plugin:79 Initialized Excalidraw Image Cache
> plugin:obsidian-icon-folder:554 loaded icon pack font-awesome-solid (1390)
> plugin:obsidian-icon-folder:554 loaded icon pack icon-brew (284)
> plugin:obsidian-icon-folder:554 loaded icon pack lucide-icons (1257)
> plugin:obsidian-icon-folder:554 loaded icon pack remix-icons (2537)
> plugin:obsidian-icon-folder:554 loaded icon pack simple-icons (2715)
> plugin:obsidian-icon-folder:554 loaded icon pack tabler-icons (4673)
> plugin:obsidian-icon-folder:3420 Icon file FasArrowRightFromBracket could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file FasFolderTree could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file SiLinode could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file RiSunLine could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file FasFileCode could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file FasTextHeight could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file FasListCheck could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file FasCircleInfo could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file FasCalendarDays could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file FarNoteSticky could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file FasListCheck could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file FasCircleQuestion could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file FasFileImage could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file FasFilePdf could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file RiHammerFill could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file RiCpuLine could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file RiGithubLine could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file RiShieldFill could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file FabGithubAlt could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file RiGithubFill could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file RiProfileLine could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file FasUserShield could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file RiTestTubeLine could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file FasUmbrellaBeach could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file FasPuzzlePiece could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> 2plugin:obsidian-icon-folder:3420 Icon file RiShieldFill could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file FasQuoteLeft could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file FasTableColumns could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file FasNoteSticky could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file FasSquarePollHorizontal could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file RiFilmLine could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file FasFileExport could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file FasLaptopCode could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file RiSlideshowLine could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file FarFileZipper could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file FasHeartPulse could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file FasAppleWhole could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file FasPersonSwimming could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file RiFileList3Fill could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file RiSpaceShipFill could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> 2plugin:obsidian-icon-folder:3420 Icon file RiArchiveFill could not be found.
> plugin:obsidian-icon-folder:3420 Icon file FasFileCode could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file RiTimerFill could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file FasUserAstronaut could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file FasLaptopCode could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file FasHouseLaptop could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file RiLightbulbFlashFill could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file FasBookJournalWhills could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file FasChessPawn could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file FasChessBishop could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file FasChessKnight could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file FasChessRook could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file FasChessQueen could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file FasChessKing could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> 2plugin:obsidian-icon-folder:3420 Icon file FasUserAstronaut could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file FasBookJournalWhills could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file RiArchiveFill could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file RiSpaceShipFill could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file RiGameFill could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file RiDoubleQuotesR could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file FasHouseChimneyUser could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file RiUserHeartLine could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file FasBoxOpen could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> plugin:obsidian-icon-folder:3420 Icon file FasLaptopCode could not be found.
> eval @ plugin:obsidian-icon-folder:3420
> ```

That's weird. Did it download all the missing icons?

**Comment by serpro69** [comment]
Well, I haven't checked file-by-file for all icons, but I saw that several folders that previously had icons were now missing them, so I assume it did not.
And each time I restarted obsidian - it kept popping up the message that icons are missing something something.

**Comment by FlorianWoelki** [comment]
> Well, I haven't checked file-by-file for all icons, but I saw that several folders that previously had icons were now missing them, so I assume it did not. And each time I restarted obsidian - it kept popping up the message that icons are missing something something.

Could you check out the newest version? I've made some changes to the logic.
Btw., how many (just a rough estimate) icons, files, and folders do you have/use?

**Comment by serpro69** [comment]
> Could you check out the newest version? I've made some changes to the logic. Btw., how many (just a rough estimate) icons, files, and folders do you have/use?

Will do.
I have 55 folders with icons assigned to them (based on what I see in data.json of the plugin)

**Comment by serpro69** [comment]
Latest version didn't fix the issue with missing icons, only that I don't see so many Notice prompts when opening obsidian.
I can still see some folders w/o icons , and those icons having error messages in the console.
I can re-assign the missing ones manually and that works just fine though, and icon svg file is being added properly.
However, another strange thing is that even after re-adding the icon manually I can still see the "icon file missing" error message in console.

For example I see in console:
```
Icon file FasArrowRightFromBracket could not be found.
```

And the folder which had that icon was without one. After that I just manually assign the same icon to the folder again, so the folder now has a visible icon. Then I restart obisidian and the error in console is still there for FasArrowRightFromBracket icon, even though I can see that the svg file has been added.

**Comment by FlorianWoelki** [comment]
> Latest version didn't fix the issue with missing icons, only that I don't see so many Notice prompts when opening obsidian.
> 
> I can still see some folders w/o icons , and those icons having error messages in the console.
> 
> I can re-assign the missing ones manually and that works just fine though, and icon svg file is being added properly.
> 
> However, another strange thing is that even after re-adding the icon manually I can still see the "icon file missing" error message in console.
> 
> 
> 
> For example I see in console:
> 
> ```
> 
> Icon file FasArrowRightFromBracket could not be found.
> 
> ```
> 
> 
> 
> And the folder which had that icon was without one. After that I just manually assign the same icon to the folder again, so the folder now has a visible icon. Then I restart obisidian and the error in console is still there for FasArrowRightFromBracket icon, even though I can see that the svg file has been added.

Thank you for the information. Then I think, I need a minimal reproduction vault, if possible.

**Comment by serpro69** [comment]
Will try to provide that, but not promising it's going to be quick :)

**Comment by serpro69** [comment]
There you go: https://github.com/serpro69/obisdian-iconize-mre

Steps:
- update plugin via obsidian settings
- enable the option to do background check in the plugin settings
- remove existing icon packs
- add icon packs
- restart obsidian

you'll see same error messages as I posted above and icons will be missing from all 3 folders

```
loading iconize
plugin:obsidian-icon-folder:558 loaded icon pack font-awesome-brands (472)
plugin:obsidian-icon-folder:558 loaded icon pack font-awesome-regular (163)
plugin:obsidian-icon-folder:558 loaded icon pack font-awesome-solid (1390)
plugin:obsidian-icon-folder:3424 Icon file FasArrowRightToBracket could not be found.
eval @ plugin:obsidian-icon-folder:3424
eval @ plugin:obsidian-icon-folder:31
__awaiter @ plugin:obsidian-icon-folder:27
getMissingIcon @ plugin:obsidian-icon-folder:3417
eval @ plugin:obsidian-icon-folder:3456
eval @ plugin:obsidian-icon-folder:31
__awaiter @ plugin:obsidian-icon-folder:27
checkMissingIcons @ plugin:obsidian-icon-folder:3414
eval @ plugin:obsidian-icon-folder:5032
plugin:obsidian-icon-folder:3424 Icon file FasFolderTree could not be found.
eval @ plugin:obsidian-icon-folder:3424
eval @ plugin:obsidian-icon-folder:31
__awaiter @ plugin:obsidian-icon-folder:27
getMissingIcon @ plugin:obsidian-icon-folder:3417
eval @ plugin:obsidian-icon-folder:3456
fulfilled @ plugin:obsidian-icon-folder:28
Promise.then (async)
step @ plugin:obsidian-icon-folder:30
eval @ plugin:obsidian-icon-folder:31
__awaiter @ plugin:obsidian-icon-folder:27
checkMissingIcons @ plugin:obsidian-icon-folder:3414
eval @ plugin:obsidian-icon-folder:5032
plugin:obsidian-icon-folder:3424 Icon file FasFileCode could not be found.
eval @ plugin:obsidian-icon-folder:3424
eval @ plugin:obsidian-icon-folder:31
__awaiter @ plugin:obsidian-icon-folder:27
getMissingIcon @ plugin:obsidian-icon-folder:3417
eval @ plugin:obsidian-icon-folder:3456
fulfilled @ plugin:obsidian-icon-folder:28
Promise.then (async)
step @ plugin:obsidian-icon-folder:30
fulfilled @ plugin:obsidian-icon-folder:28
Promise.then (async)
step @ plugin:obsidian-icon-folder:30
eval @ plugin:obsidian-icon-folder:31
__awaiter @ plugin:obsidian-icon-folder:27
checkMissingIcons @ plugin:obsidian-icon-folder:3414
eval @ plugin:obsidian-icon-folder:5032
plugin:obsidian-icon-folder:29 Uncaught (in promise) Error: ENOENT: no such file or directory, scandir '/home/sergio/obsidian/temp-vault/temp-vault/.obsidian/plugins/obsidian-icon-folder/icons/font-awesome-brands'
```

**Comment by KrzysiekWu** [comment]
> Please create a new issue, if the latest release does not fulfill this requirement.

1. As the @serpro69 wrote, there's still an issue with some of the icons. Here's a quick comparison:
![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/2963024/37d087b9-7a70-432c-8112-2f502007652a)

2. I think that the documentation about the "background checker" functionality should not imply that this is sync-only functionality (https://florianwoelki.github.io/obsidian-iconize/guide/syncing.html#background-checker)

**Comment by FlorianWoelki** [comment]
> There you go: https://github.com/serpro69/obisdian-iconize-mre
> 
> Steps:
> 
> * update plugin via obsidian settings
> * enable the option to do background check in the plugin settings
> * remove existing icon packs
> * add icon packs
> * restart obsidian
> 
> you'll see same error messages as I posted above and icons will be missing from all 3 folders
> 
> ```
> loading iconize
> plugin:obsidian-icon-folder:558 loaded icon pack font-awesome-brands (472)
> plugin:obsidian-icon-folder:558 loaded icon pack font-awesome-regular (163)
> plugin:obsidian-icon-folder:558 loaded icon pack font-awesome-solid (1390)
> plugin:obsidian-icon-folder:3424 Icon file FasArrowRightToBracket could not be found.
> eval @ plugin:obsidian-icon-folder:3424
> eval @ plugin:obsidian-icon-folder:31
> __awaiter @ plugin:obsidian-icon-folder:27
> getMissingIcon @ plugin:obsidian-icon-folder:3417
> eval @ plugin:obsidian-icon-folder:3456
> eval @ plugin:obsidian-icon-folder:31
> __awaiter @ plugin:obsidian-icon-folder:27
> checkMissingIcons @ plugin:obsidian-icon-folder:3414
> eval @ plugin:obsidian-icon-folder:5032
> plugin:obsidian-icon-folder:3424 Icon file FasFolderTree could not be found.
> eval @ plugin:obsidian-icon-folder:3424
> eval @ plugin:obsidian-icon-folder:31
> __awaiter @ plugin:obsidian-icon-folder:27
> getMissingIcon @ plugin:obsidian-icon-folder:3417
> eval @ plugin:obsidian-icon-folder:3456
> fulfilled @ plugin:obsidian-icon-folder:28
> Promise.then (async)
> step @ plugin:obsidian-icon-folder:30
> eval @ plugin:obsidian-icon-folder:31
> __awaiter @ plugin:obsidian-icon-folder:27
> checkMissingIcons @ plugin:obsidian-icon-folder:3414
> eval @ plugin:obsidian-icon-folder:5032
> plugin:obsidian-icon-folder:3424 Icon file FasFileCode could not be found.
> eval @ plugin:obsidian-icon-folder:3424
> eval @ plugin:obsidian-icon-folder:31
> __awaiter @ plugin:obsidian-icon-folder:27
> getMissingIcon @ plugin:obsidian-icon-folder:3417
> eval @ plugin:obsidian-icon-folder:3456
> fulfilled @ plugin:obsidian-icon-folder:28
> Promise.then (async)
> step @ plugin:obsidian-icon-folder:30
> fulfilled @ plugin:obsidian-icon-folder:28
> Promise.then (async)
> step @ plugin:obsidian-icon-folder:30
> eval @ plugin:obsidian-icon-folder:31
> __awaiter @ plugin:obsidian-icon-folder:27
> checkMissingIcons @ plugin:obsidian-icon-folder:3414
> eval @ plugin:obsidian-icon-folder:5032
> plugin:obsidian-icon-folder:29 Uncaught (in promise) Error: ENOENT: no such file or directory, scandir '/home/sergio/obsidian/temp-vault/temp-vault/.obsidian/plugins/obsidian-icon-folder/icons/font-awesome-brands'
> ```

Thank you for the reproduction. I was able to fix this, it was mainly an issue with font awesome.
