### ISSUE TITLE
Iconise Tab Icons reset in reading mode & when moving between panes

### ISSUE THREAD

**Issue by Aeases** [FlorianWoelki/obsidian-iconize#259]
**Describe the bug**
When entering reading mode the tab icon will reset from whatever icon is defined for that tab, to the default.
EDIT: and when moving a pane the tab icon will reset as well.
**To Reproduce**
1. Turn on Iconise Tab Icons
2. Open a note that has a custom iconise icon
3. Enter Reading Mode
4. Observe the tab icon reset back to the default file icon.

**Expected behavior**
The icon should stay the same after entering reading mode. (and when moving a pane)
**Screenshots**
![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/96164686/0870a1a7-a4aa-4e1e-bff6-88f456339a6d)

**Comment by FlorianWoelki** [comment]
This has been fixed in the [latest version](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.4.2)!
