### ISSUE TITLE
Icons not synced to Ipad

### ISSUE THREAD

**Issue by XVItokaz** [FlorianWoelki/obsidian-iconize#265]
Hi @FlorianWoelki 

I'm sorry that I need to write after the recent update, but I really can't get it to work.

Obsidian on my PC and MAC is functioning, and they sync, with only a small issue that there isn't the same number of icons in some folders, but it's not a major problem right now. However, for my new iPad Pro, not a single icon is syncing.

I have the same path on all three of my devices, i.e., .obsidian/icons.

I've even gone so far as to uninstall Obsidian from my iPad, deleted the icon folders from files, and started over from scratch.

Reinstalled Iconize, downloaded all icons at home (the exact same number as on the PC), but nothing shows up regardless.

Edit: i have also updated on all 3 devices the new latest update for iconize.

Do you have any suggestions for what it might be instead?

**Comment by FlorianWoelki** [comment]
Hey there, thank you for the request. If you set the path to `.obsidian/icons` it does not sync automatically. You have to do this manually (at least what I heard). I am not 100% sure why it is not syncing all the icons. Did you enable the background checker? This will automatically download all the missing icons.

**Comment by XVItokaz** [comment]
Hi @FlorianWoelki 

Thank you for the input regarding the background checker; I honestly missed that.

But now, after the latest update, I ran a test, perhaps a bit exaggerated, but with Obsidian and Iconize on four of my devices (PC Windows, Mac Book Pro, iPad Pro, and Samsung Galaxy S23). On all devices, i manually synchronized and selected the exact same path.

**I've noticed the following:**

Under Iconize and Icon Packs, suddenly on all four of my devices, four of the packs contain either 0 icons or 1 or just 2. It's not too difficult to uninstall and reinstall them, though. But a bit strange.

Despite the background checker, some packs have a slightly different number of icons. However, these missing icons are not ones I actually use, and we're talking about a difference of 1 to at most 5 icons in some icon packs.

Despite several attempts at synchronization and downloading new packs, I can't seem to get all four devices to cooperate. There's always a missing icon that I've placed on my PC. I try to keep the PC as the primary source before waiting for synchronization from the PC and then on the other three. 

I've verified that the icons I use are on all four devices is actually selectable, and they are , but a few still refuse to appear. I've tried restarting multiple times, syncing, and waiting, but nothing happens. I can add them manually, but it's a bit annoying.

As a last test, i tried adding the missing icons on another device, for example, via the iPad, but they didn't appear on the Samsung or Mac Pro, although they remained on the PC (fortunately) that i already selected from the start. 

So, something doesn't seem to be working correctly.

**Comment by FlorianWoelki** [comment]
> Hi @FlorianWoelki 
> 
> 
> 
> Thank you for the input regarding the background checker; I honestly missed that.
> 
> 
> 
> But now, after the latest update, I ran a test, perhaps a bit exaggerated, but with Obsidian and Iconize on four of my devices (PC Windows, Mac Book Pro, iPad Pro, and Samsung Galaxy S23). On all devices, i manually synchronized and selected the exact same path.
> 
> 
> 
> **I've noticed the following:**
> 
> 
> 
> Under Iconize and Icon Packs, suddenly on all four of my devices, four of the packs contain either 0 icons or 1 or just 2. It's not too difficult to uninstall and reinstall them, though. But a bit strange.
> 
> 
> 
> Despite the background checker, some packs have a slightly different number of icons. However, these missing icons are not ones I actually use, and we're talking about a difference of 1 to at most 5 icons in some icon packs.
> 
> 
> 
> Despite several attempts at synchronization and downloading new packs, I can't seem to get all four devices to cooperate. There's always a missing icon that I've placed on my PC. I try to keep the PC as the primary source before waiting for synchronization from the PC and then on the other three. 
> 
> 
> 
> I've verified that the icons I use are on all four devices is actually selectable, and they are , but a few still refuse to appear. I've tried restarting multiple times, syncing, and waiting, but nothing happens. I can add them manually, but it's a bit annoying.
> 
> 
> 
> As a last test, i tried adding the missing icons on another device, for example, via the iPad, but they didn't appear on the Samsung or Mac Pro, although they remained on the PC (fortunately) that i already selected from the start. 
> 
> 
> 
> So, something doesn't seem to be working correctly.

Thanks for the detailed description. Could you please share a outline of your Vault? So how many notes/folders (maybe a screenshot with blurring the names?) and how many Icons do you use?

**Comment by XVItokaz** [comment]
Hi @FlorianWoelki 

Certainly, I can do that.

I have various levels, but most commonly, I have a root icon followed by 2-3 subfolders. However, there are occasions where there can be up to 7 subfolders, but that's something unique.

I stick to fixed icons that I assign to specific stages. Except for the very first icon, which is based on what the title suggests, for example, "Development." In that case, it's an image related to the synonym "development."

But under these root icons, which are located under the root directory, if you can see it in my first image at the top under "tokaz," there's a house icon. Of course, it represents the home/start.

The icon below that, within the subfolder, is what I mean by an icon based on the categorization.

But after the "title" icon, it's always the same:

Step 2: Atom2Filled (Ti)
Step 3: CpuLine (Ri)
Step 4: Digitalocean (Si)
Step 5: CircleChevronsDo
Step 6: Line-height (Ti)
Step 7: Radio (Li)
Step 8: RadioPole (ib)

As the very last step, where my content resides (PDFs to read, articles I've written, notes I've taken, documentation, etc.), I use the BaseStationFill (Ri) icon.

Here In the image below, we can see a maximum of 4 levels (excluding the header icon you see, which is a D icon). These levels are Atom2Filled (Ti) -> CpuLine (Ri) -> Digitalocean (Si) -> and finally BaseStationFill (Ri).

It might be challenging to determine this directly from the image with all the header categories and their subfolders, but the concept remains the same with the icons:

![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/121265451/7ed66b00-1e7b-45a5-9026-89ae608114fc)

In this image (no need to blur as there's nothing to hide), you can see that the structure is the same, as a simple example where I have a maximum of 3 steps. I'm trying to place numbers next to the subfolders' icons in turquoise, so you can see them via the "Recently Used Icons" above with the corresponding linked numbers.


![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/121265451/ca2cf876-29fa-4062-9622-99ae88e218a1)

**Comment by FlorianWoelki** [comment]
I think it's due to the Obsidian sync mechanism. I've added some functionalities to prevent this issue. I'll close this issue for now. Feel free to create a new one, if needed.

If you have syncing issues, I recommend reading [this guide](https://florianwoelki.github.io/obsidian-iconize/guide/syncing.html#lucide-icons) which was also recently released.
