### ISSUE TITLE
How to automatically add a fixed icon when creating a new file or folder？

### ISSUE THREAD

**Issue by zhouxing001** [FlorianWoelki/obsidian-iconize#267]
How to set up new files and folders to automatically set a fixed icon？
![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/95668337/8f3d1bf4-6209-486c-88cf-eeb15d326afc)

**Comment by FlorianWoelki** [comment]
Maybe [this documentation](https://florianwoelki.github.io/obsidian-iconize/files-and-folders/custom-rules.html#having-a-default-icon) answers your question?

**Comment by zhouxing001** [comment]
> 也许[这个文档](https://florianwoelki.github.io/obsidian-iconize/files-and-folders/custom-rules.html#having-a-default-icon)可以回答您的问题？

OK, thanks! But how to differentiate between files and folders. Now I only know that it can be unified into one type?

**Comment by FlorianWoelki** [comment]
> > 也许[这个文档](https://florianwoelki.github.io/obsidian-iconize/files-and-folders/custom-rules.html#having-a-default-icon)可以回答您的问题？
> 
> 
> 
> OK, thanks! But how to differentiate between files and folders. Now I only know that it can be unified into one type?

Custom Rules also allow to differentiate between files and folders. You can simply create two rules, one for folders and the other for files.

**Comment by zhouxing001** [comment]
> > > 也许[这个文档](https://florianwoelki.github.io/obsidian-iconize/files-and-folders/custom-rules.html#having-a-default-icon)可以回答您的问题？
> > 
> > 
> > OK, thanks! But how to differentiate between files and folders. Now I only know that it can be unified into one type?
> 
> Custom Rules also allow to differentiate between files and folders. You can simply create two rules, one for folders and the other for files.

I saw it, thank you, thank you very much!
