### ISSUE TITLE
Pinning a note causes the icon to revert to the original icon

### ISSUE THREAD

**Issue by MKDJr** [FlorianWoelki/obsidian-iconize#271]
**Describe the bug**
Pinning a note causes the icon to revert to the original icon. Setting the icon again via the `change icon` modal allows you to change it back.

**To Reproduce**
1. Set icon for note.
2. Open note.
3. Pin note.

**Expected behavior**
When pinning the note, the note icon does not revert to the original.

**Comment by FlorianWoelki** [comment]
Thank you for the report.

Could you please tell me, how you exactly "pin" a note in Obsidian?

**Comment by MKDJr** [comment]
Sure! I use the drop-down modal when right clicking on a tab.

It seems to also occur when unpinning a note.

Also, here is a video of what is happening:

https://github.com/FlorianWoelki/obsidian-iconize/assets/61061178/1f775eb1-f373-49f6-acab-04aa7af1569c

**Comment by FlorianWoelki** [comment]
This should be already fixed :)
