### ISSUE TITLE
Inline title icon compatibility with minimal theme

### ISSUE THREAD

**Issue by kbhbhk** [FlorianWoelki/obsidian-iconize#277]
**Is your feature request related to a problem? Please describe.**

I really appreciate recent update that supports inline title icon. Thanks!
But there's an issue with minimal theme for some reason.
In minimal theme mode, the icon goes all the way left side of the note.
I think there's no problem with the Things theme, didn't check other themes.

**Describe the solution you'd like**

Compatibility with minimal theme. Since it's a theme that people use a lot 😃

**Describe alternatives you've considered**

I'm not using this feature with minimal theme for now.

**Additional context**

<img width="500" alt="default" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/130442702/b7d94ec6-35e8-4349-ac72-9fd5963ca7f0">
<img width="500" alt="minimal" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/130442702/a1819476-0653-406c-a167-6fbc0e02358e">

**Comment by FlorianWoelki** [comment]
This issue should be fixed and is now released in [v2.6.1](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.6.1)

**Comment by kbhbhk** [comment]
Thnks for your SUPER FAST work!!! Really appreciate 🥳
