### ISSUE TITLE
Request for automatic icons

### ISSUE THREAD

**Issue by viocha** [FlorianWoelki/obsidian-iconize#279]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
It's nice that every file has a default icon generated from the first letter of the filename.
The effect is as follows
![Screenshot_2023-10-26-11-17-50-045-edit_io anytype app](https://github.com/FlorianWoelki/obsidian-iconize/assets/66580331/2e93663a-c8e4-4604-ba26-c59be4b3f4da)

**Describe alternatives you've considered**

**Additional context**

**Comment by FlorianWoelki** [comment]
This is a pretty specific use case. However, you can achieve all of these by using the custom rules and regex solution.
