### ISSUE TITLE
Inline icons from icon packs don't render in edit mode

### ISSUE THREAD

**Issue by qodeninja** [FlorianWoelki/obsidian-iconize#280]
**Describe the bug**
Adding inline icons from icon packs don't render after added in edit mode. 

Not sure if there is a setting I need to configure to enable them (no documentation on this), but I recently updated from the Icon Folder version to Iconize, restarted Obsidian and reloaded the icon packs (Remix, Simple). Emojis work fine.

**To Reproduce**
1. Insert icon pack icon via :icon-name in edit mode
2. Select any remix-pack icon
3. Tab out of the icon markdown
4. See icon markdown but no icon rendered

**Expected behavior**
When inserting an icon inline it should render the selected icon instead of the markdown after tabbed out

**Screenshots**
<img width="533" alt="Screenshot 2023-10-26 at 10 31 00 AM" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/1043235/ce729307-6c63-418c-886e-30916984281d">

**Additional context**
Works fine for normal emojis but not for icon packs

**Comment by Rhydderch** [comment]
In case it might help, this plugin has support for icons in live preview: https://github.com/aidenlx/obsidian-icon-shortcodes
But it has not been updated in a while. So perhaps you could reuse some of its code.

**Comment by josh-79** [comment]
+1 it would be great if iconize could also render inline icons in edit mode

**Comment by FlorianWoelki** [comment]
This has been released in [v2.8.0](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.8.0).

**Comment by simonfossom** [comment]
@FlorianWoelki appreciate the effort 🙏

**Comment by qodeninja** [comment]
I just saw this new feature in the options. As someone with dyslexia and very visual oriented I cannot thank you enough for this update. <3
