### ISSUE TITLE
Icon in title does not scale with font size setting

### ISSUE THREAD

**Issue by redactedscribe** [FlorianWoelki/obsidian-iconize#287]
**Describe the bug**
When you Ctrl + Mousewheel up to increase the font size, the icon in the title does not increase in size along with the rest of the document.

**To Reproduce**
1. Enable Toggle Icon in Title option.
2. Add emoji to `icon:`.
3. Ctrl + Mousewheel up to increase font size a lot (or Settings > Appearance > Font >  Font size).

**Expected behavior**
Icon should scale up in size along with the inline title and rest of the text.

**Screenshots**
![Obsidian_2023-11-01_14-17-58](https://github.com/FlorianWoelki/obsidian-iconize/assets/25013746/1f62256a-b197-4a57-a43e-2589f8e24f9f)

Thanks.

**Comment by FlorianWoelki** [comment]
This has been resolved in [v2.7.2](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.7.2).
