### ISSUE TITLE
Frontmatter property throws error when property type is a list and not plain text

### ISSUE THREAD

**Issue by FlorianWoelki** [FlorianWoelki/obsidian-iconize#290]
Icon property defined in frontmatter does throw an error when type is a list.

**Comment by FlorianWoelki** [comment]
This has been resolved in [v2.7.2](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.7.2).

**Comment by mclearc** [comment]
I'm not sure if this is the same error but I'm seeing the following (I'm on the latest version):

```
app.js:1 Uncaught TypeError: Cannot read properties of null (reading 'querySelector')
    at getTitleIcon (plugin:obsidian-icon-folder:4621:17)
    at Object.updateStyle (plugin:obsidian-icon-folder:4644:23)
    at eval (plugin:obsidian-icon-folder:5613:35)
    at e.tryTrigger (app.js:1:695499)
    at e.trigger (app.js:1:695432)
    at t.trigger (app.js:1:2028169)
    at t.<anonymous> (app.js:1:1944651)
    at app.js:1:237027
    at Object.next (app.js:1:237132)
    at a (app.js:1:235850)
```

I also see this error triggered with style settings, but only when iconize is enabled. 

```
    app.js:1 Uncaught TypeError: Cannot read properties of null (reading 'querySelector')
    at getTitleIcon (plugin:obsidian-icon-folder:4621:17)
    at Object.updateStyle (plugin:obsidian-icon-folder:4644:23)
    at eval (plugin:obsidian-icon-folder:5613:35)
    at e.tryTrigger (app.js:1:695499)
    at e.trigger (app.js:1:695432)
    at t.trigger (app.js:1:2028169)
    at CSSSettingsManager.setCSSVariables (plugin:obsidian-style-settings:3779:35)
    at CSSSettingsManager.setConfig (plugin:obsidian-style-settings:3809:18)
    at eval (plugin:obsidian-style-settings:9696:34)
 ```

**Comment by FlorianWoelki** [comment]
> I'm not sure if this is the same error but I'm seeing the following (I'm on the latest version):
> 
> ```
> app.js:1 Uncaught TypeError: Cannot read properties of null (reading 'querySelector')
>     at getTitleIcon (plugin:obsidian-icon-folder:4621:17)
>     at Object.updateStyle (plugin:obsidian-icon-folder:4644:23)
>     at eval (plugin:obsidian-icon-folder:5613:35)
>     at e.tryTrigger (app.js:1:695499)
>     at e.trigger (app.js:1:695432)
>     at t.trigger (app.js:1:2028169)
>     at t.<anonymous> (app.js:1:1944651)
>     at app.js:1:237027
>     at Object.next (app.js:1:237132)
>     at a (app.js:1:235850)
> ```
> 
> I also see this error triggered with style settings, but only when iconize is enabled.
> 
> ```
>     app.js:1 Uncaught TypeError: Cannot read properties of null (reading 'querySelector')
>     at getTitleIcon (plugin:obsidian-icon-folder:4621:17)
>     at Object.updateStyle (plugin:obsidian-icon-folder:4644:23)
>     at eval (plugin:obsidian-icon-folder:5613:35)
>     at e.tryTrigger (app.js:1:695499)
>     at e.trigger (app.js:1:695432)
>     at t.trigger (app.js:1:2028169)
>     at CSSSettingsManager.setCSSVariables (plugin:obsidian-style-settings:3779:35)
>     at CSSSettingsManager.setConfig (plugin:obsidian-style-settings:3809:18)
>     at eval (plugin:obsidian-style-settings:9696:34)
> ```

Could you please describe what you did, so that I can reproduce this issue?

**Comment by mclearc** [comment]
> Could you please describe what you did, so that I can reproduce this issue?

I just turned it on. Obviously, when I have style settings turned off I don't get the error there. But just turning on the plugin returned the first of the two errors above. Here's my debug info.


```
SYSTEM INFO:
	Obsidian version: v1.4.16
	Installer version: v1.4.13
	Operating system: Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:45 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6020 23.1.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: off
	Legacy editor: off
	Base theme: adapt to system
	Community theme: Typomagical v1.9.1
	Snippets enabled: 14
	Restricted mode: off
	Plugins installed: 50
	Plugins enabled: 40
		1: Admonition v10.1.1
		2: Advanced Tables v0.19.1
		3: Auto Note Mover v1.2.0
		4: Better Word Count v0.10.0
		5: Buttons v0.4.19
		6: Dataview v0.5.64
		7: Dice Roller v10.3.0
		8: Excalidraw v1.9.28
		9: Excel to Markdown Table v0.4.0
		10: Export Image plugin v1.0.3
		11: Fantasy Statblocks v3.16.0
		12: Github Publisher v6.10.3
		13: Folder notes v1.6.8
		14: Icon Shortcodes v0.9.7
		15: JS Engine v0.0.5
		16: Meta Bind Plugin v0.7.0
		17: Initiative Tracker v12.4.2
		18: Linter v1.20.1
		19: Webpage HTML Export v1.7.3
		20: Various Complements v9.1.0
		21: Text Mapper v1.0.0
		22: Text Format v2.2.8
		23: Settings Search v1.3.10
		24: Table Extended v1.6.1
		25: Quick Switcher++ v3.3.8
		26: Pandoc Plugin v0.4.1
		27: Obsidian Enhancing Export v1.9.1
		28: Obsidian42 - BRAT v0.7.1
		29: Obsidian Leaflet v6.0.0
		30: Image Toolkit v1.4.0
		31: JSON/CSV Importer v0.31.2
		32: Tag Wrangler v0.6.1
		33: Mousewheel Image zoom v1.0.19
		34: Link with alias v1.0.7
		35: Note Auto Creator v10
		36: Iconize v2.7.2
		37: Style Settings v1.0.7
		38: Hover Editor v0.11.14
		39: Hover External Link Plugin v1.0.0
		40: Custom Frames v2.4.6

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

**Comment by FlorianWoelki** [comment]
I've added a small commit to the code base, this might resolve this issue.
Will be probably released within the next week.
