### ISSUE TITLE
Icons duplicate in the picker and constantly disappear

### ISSUE THREAD

**Issue by kearaa** [FlorianWoelki/obsidian-iconize#294]
**Describe the bug**
These are multiple bugs that might be related. 
- The icons multiply in the picker every time that they are used. 
- The icons are not recognized by Obsidian even when they are in the icon folders. 

**Steps to Reproduce**

_Multiplying icons:_
1. I download the Lucide icon pack. 
2. I change the icon of a folder to "Flame (Li)". 
3. I go to change the icon of another folder, and I search Flame again, now Flame (Li) shows up twice. It has been duplicated in the picker. (It doesn't appear to have been duplicated in the icon pack folder if I look in Finder outside Obsidian.)
4. If I choose this icon again, and repeat the process, there will now be three Flame icons in the picker. And so on and on, they will continue to multiple every time. 

_Icons dissappearing_:
1. I change all of my folders to different icons. 
2. I exit Obsidian. 
3. I open Obsidian again. 
4. A long list of notifications pops up saying that all of the icons do not exist. The icons have disappeared from my folders. I can only fix by reinstalling Iconize and the icon packs again, and then change all of the icons individually again.

**Expected behavior**
I expect the icons in the picker not to multiply. Even if I use Flame once, I expect there to still only be one Flame option in the icon picker. 

**Additional context**
I have tried these steps in both the .obsidian/icons folder, and I tried setting the icons folder to a folder in my vault. The issue still exists. 

It seems like this app now works by keeping the icons archived and only unpacking the ones being used. I see that the zip file is added into the icon folder, and then the individual icons are added into the icon pack folder when you apply them to a file in Obsidian. If you remove the icon from its use in Obsidian, it is automatically removed from the icon pack folder. Maybe this has something to do with the duplications, and maybe the duplications has something to do with the app not recognizing the icons?

I'm now attempting to fix this by unzipping the icon pack and making it into a custom icon pack myself, hoping this will stop the app from trying to manage the folders itself, and maybe that will stop it from duplications.

**Comment by kearaa** [comment]
I tried creating the Lucide icons as a custom icon pack and named it Lulu. I opened Obsidian and Iconize now says there are two lulu icon packs... and still shows multiplying icons. There is definitely only one Lulu folder in the icon folder.

![CleanShot 2023-11-07 at 11 41 58](https://github.com/FlorianWoelki/obsidian-iconize/assets/68878233/c6785f79-1913-43d9-be0e-b8aba661ac4c)

I tried again, duplicating the Lulu folder to lulu copy.. and then pressed the delete icon in Iconize settings on ONE of the lulu packs listed within Iconize. My lulu folder was deleted from Obsidian. I closed Obsidian and then opened it again and now the Lulu copy is also listed twice by Iconize. There is again only one lulu copy folder. 
![CleanShot 2023-11-07 at 11 43 24](https://github.com/FlorianWoelki/obsidian-iconize/assets/68878233/a8fc26db-833c-453d-8e7c-ecc858c97b4a)
![CleanShot 2023-11-07 at 11 45 26@2x](https://github.com/FlorianWoelki/obsidian-iconize/assets/68878233/b2e97d9e-f4cb-49e1-bd7e-b9cfb6c6a61e)

**Comment by kearaa** [comment]
I started over, uninstalled Iconize, let it restore to default settings and folder placement, and added Lucide from inside Iconize.. 
The same thing happens. See screenshot below. Lucide exists twice. In addition, everytime I add an icon to a folder, the count in Iconize goes up on one of the double folders. (see screenshot, the original is 1257 and the other now says 1259.)

![CleanShot 2023-11-07 at 11 59 21](https://github.com/FlorianWoelki/obsidian-iconize/assets/68878233/cd0bb295-003b-4203-8db7-9a3f5c35f8e3)

**Comment by Aetherinox** [comment]
I can also confirm this. 
The more I use them, the more they duplicate.

![BYVWtTi](https://github.com/FlorianWoelki/obsidian-iconize/assets/118329232/2c9b6730-a4e6-49e9-b6be-893546b005aa)

**Comment by FlorianWoelki** [comment]
This has been fixed in [v2.8.0](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.8.0).
