### ISSUE TITLE
Inline custom icons and Dataview inlines can't appear in the same list

### ISSUE THREAD

**Issue by 00dani** [FlorianWoelki/obsidian-iconize#295]
**Describe the bug**
Using an Iconize custom icon and a Dataview inline in the same note does work, but if you try to put them in the same *list*, then the Dataview inline will be rendered as regular `inline code` rather than evaluated.

**To Reproduce**
1. Create a note with a :CustomIcon: and a `=dataview inline` in the same list. I've been testing with the following source:
```markdown
- :RiCalendar2Fill: Daily
  - `$= '[[Daily/' + DateTime.now().toISODate() + '|Today]]'`
  - `$= '[[Daily/' + DateTime.now().minus({days: 1}).toISODate() + '|Yesterday]]'`
  - `$= '[[Daily/' + DateTime.now().minus({weeks: 1}).toISODate() + '|One week ago]]'`
```
2. Verify that the Dataview inlines work properly in editing view. (May need to "Enable inline JavaScript Queries" in Dataview's plugin settings, if it wasn't already enabled.)
3. Switch to reading view.

**Expected behavior**
When I'm in reading view, I expect to see both the Iconize custom icon and the rendered Dataview output.

**Screenshots**
In editing view, Dataview works fine and Iconize doesn't. This is expected, since Iconize currently only displays its inline icons in reading view, but it's worth noting. In reading view, Iconize works and Dataview doesn't.
![Screenshot 2023-11-08 at 13 48 04](https://github.com/FlorianWoelki/obsidian-iconize/assets/610876/26eba560-d18c-4477-90a3-232ddee9fe44)

However, if the icon and Dataview inlines aren't part of the same list, they work fine together:
![Screenshot 2023-11-08 at 13 52 31](https://github.com/FlorianWoelki/obsidian-iconize/assets/610876/9bbc3e62-a453-48ec-a898-2cfadcaab866)

**Additional context**
I have the latest versions of both plugins, as well as Obsidian.
Obsidian v1.4.16
Iconize v2.7.3
Dataview v0.5.64

**Comment by BaughBerry** [comment]
I can confirm that in-line icons also mess up Dataview in-line metadata.
For example, Dataview recognizes Progress:: <progress max=100 value=0> </progress> 0%
But it does not recognize, :clock: Progress:: <progress max=100 value=0> </progress> 0%

**Comment by FlorianWoelki** [comment]
The icon identifier can now be customized in [v2.10.0](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.10.0).
