### ISSUE TITLE
"Whether to apply the icon for all files/folders that match the file path." option for rules not saving

### ISSUE THREAD

**Issue by i-report-bugs** [FlorianWoelki/obsidian-iconize#298]
**Describe the bug**
This option does not save when Obsidian is closed and reopened.
![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/117464957/54883c7b-c5a4-40d9-9708-1180c69d8f8c)

**To Reproduce**
1.Create a new rule
2. Check the option
3. Restart Obsidian
4. Option is unchecked again

**Expected behavior**
It should remain checked.

**Screenshots**
Here's a video of the problem in action. As you can also see, clicking on Save Changes does not close the Rule window leaving me to close it manually. I'm using the latest version at the time of posting.

https://github.com/FlorianWoelki/obsidian-iconize/assets/117464957/79d9978f-7ba3-46fe-97dd-2768c0c13e69

**Additional context**
I made a proper bug report to continue my correspondence with the developer from this closed issue: https://github.com/FlorianWoelki/obsidian-iconize/issues/283#issuecomment-1800120704

**Comment by FlorianWoelki** [comment]
This has been fixed in [v2.8.0](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.8.0).
