### ISSUE TITLE
Random Icon intermittently appears above note title when the toggle for this is off

### ISSUE THREAD

**Issue by paulwalk** [FlorianWoelki/obsidian-iconize#299]
**Describe the bug**
A (apparently random) icon sometime appears above the note title when the `Toggle Icon in Title` setting is off.

This happens even when the note **does not have any icon configured**

**To Reproduce**
1. Go to File explorer
2. Click on a file
3. (Sometimes) see that an icon has appeared above the note title

**Expected behavior**
I do not expect to ever see an icon above the note title because I have set the `Toggle Icon in Title` setting to be off.

**Comment by FlorianWoelki** [comment]
I am not able to reproduce this issue. Please take a closer look, if other plugins interfere with Iconize or your `data.json` file is somehow broken. You can also upload a minimal reproduction vault so that I can test this problem independently.

**Comment by paulwalk** [comment]
I have tried and **failed** to reproduce this with a stripped-down copy of my vault (containing all the plugins & config but a subset of the content). However, I **do** still see this issue (intermittently) with my full vault.

I'm not able to share the full vault here for confidentiality reasons, therefore it is difficult to take this further.

I suggest that you close this issue now, and if in future I can reliably reproduce this problem with a vault that I can share, I will open a new issue and supply that example.
