### ISSUE TITLE
Using :icon: format in editing mode

### ISSUE THREAD

**Issue by Aetherinox** [FlorianWoelki/obsidian-iconize#300]
**Is your feature request related to a problem? Please describe.**
Not a problem, unsupported feature. I did a brief look through other issues and have been wondering about icons being supported in Editing mode. This plugin is almost the perfect plugin, however, at present, icons only show by their tag in Editing mode, instead of the actual icon appearing.

Have had to make use of an older / outdated plugin in order to physically see icons in Editing mode.

**Describe the solution you'd like**
Having the ability to write out the tag for an icon, and after the final `:` is placed, that text turning into an icon.

**Describe alternatives you've considered**
Currently using an old outdated plugin that semi works for viewing icons in Editing mode.

**Comment by FlorianWoelki** [comment]
Seems like a duplicate to #280?
