### ISSUE TITLE
Icons in edit mode is WIP, but no option to disable icons in edit mode?!

### ISSUE THREAD

**Issue by qlassiqa** [FlorianWoelki/obsidian-iconize#303]
**Describe the bug**
The documentation says icons in edit mode are work in progress (and I want to disable this feature since I don't use it AND conflicts with other plugins), but there is no option to disable icons in edit mode.

**To Reproduce**
1. Open Iconize settings
2. No option to disable icons in edit mode

**Expected behavior**
There should be an option to disable icons in edit mode.

**Additional context**
I use Espanso with `:` key trigger, which always triggers the unwanted iconize suggestion box, and I also use the Inline Scripts plugin set to trigger via `::`, which also conflicts with iconize.

**Comment by FlorianWoelki** [comment]
This has been released in [v2.8.0](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.8.0).
