### ISSUE TITLE
[BUG]: (v. 2.7 - 2.8) ITS Theme duplicate icons

### ISSUE THREAD

**Issue by CinemaGame** [FlorianWoelki/obsidian-iconize#308]
**Describe the bug**
When the ITS theme and its snippets are installed, the icons on the records and the folder are duplicated. The problem is missing in version 2.6.1, but after this version there are problems in ITS theme.

**Screenshots**
![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/46268190/7a925c6e-e696-4846-b134-3a9e18d6bc3b)

**Comment by FlorianWoelki** [comment]
I don't think that the issue is related to Iconize. ITS theme seems to add icons by default without any other customization. So please feel free to report the issue there.

**Comment by CinemaGame** [comment]
But in version 2.6.1, everything was fine... :cry:

**Comment by FlorianWoelki** [comment]
> But in version 2.6.1, everything was fine... 😢

It's because of renaming classes within Iconize. I've created a [pull request](https://github.com/SlRvb/Obsidian--ITS-Theme/pull/262) which should fix this issue.
