### ISSUE TITLE
[Suggestion] Add option to save icons settings on normal/md file

### ISSUE THREAD

**Issue by Zarpyk** [FlorianWoelki/obsidian-iconize#31]
It would be nice to add an option to configure a folder to save the icon settings, instead of just being able to save them in the .obsidian

This makes it easier for some ways of sync between different devices (For example: [Obsidian Live-Sync](https://github.com/vrtmrz/obsidian-livesync) it only sync no setting folders (it also sync plugins, but it doesn't work very well) or use github but only with normal/md files/folders to have different configuration in mobile and PC)

Extra: Hide this config file like [Folder Notes](https://github.com/xpgo/obsidian-folder-note-plugin) description notes

**Comment by farling42** [comment]
Alternatively, it would be nice to define the icon for each note within the frontmatter. This would make it very useful for my importer plugin to be able to set the correct icon on each note without requiring it to edit a file within the .obsidian folder.

Also, support to able to read the folder icon from the folder note that is used by "AidenLX's Folder Notes" plugin (the folder note is just a note inside the folder with the same name as the folder, but with ".md" added :)  )

**Comment by pixelsbyeryc** [comment]
It would be nice to set default icons for folders and files. That way, each time you create a new file or folder, it automatically adds an icon.

Is there a way to do this with Regex already, and I'm just not aware of how to use Regex for this purpose?

**Comment by FlorianWoelki** [comment]
> It would be nice to set default icons for folders and files. That way, each time you create a new file or folder, it automatically adds an icon.
> 
> Is there a way to do this with Regex already, and I'm just not aware of how to use Regex for this purpose?

Yes it is. There is a functionality called `Custom Rules` where you can specify your own Regex or string where it will add a default icon.

**Comment by MINIPuffer** [comment]
> > It would be nice to set default icons for folders and files. That way, each time you create a new file or folder, it automatically adds an icon.
> > Is there a way to do this with Regex already, and I'm just not aware of how to use Regex for this purpose?
> 
> Yes it is. There is a functionality called where you can specify your own Regex or string where it will add a default icon.`Custom Rules`

But the function doesn't seem to be used to match specific file types, e.g. `\w+.md`

**Comment by jason-pollock** [comment]
Anyone have a working rule to automatically add an icon to new `.md` files?

**Comment by mrhallak** [comment]
> `\.md$` worked for me to set icons on all `md` files.

This does not seem to work with colors though :/

**Comment by FlorianWoelki** [comment]
Closing because it seems similar to #142.
