### ISSUE TITLE
Added Icon pack icons are not available in the note

### ISSUE THREAD

**Issue by ABailey0** [FlorianWoelki/obsidian-iconize#310]
**Describe the bug**
When I add any icon pack including the predefined ones I can add them to the folder or file in the side bar, but when using the ":" to add an icon directly into the body of my note I only see emojis. I also have to reinstall my icon packs every time I reload obsidian. (I have hosting it on my icloud if that is releveant).

**Comment by FlorianWoelki** [comment]
Could you check for me if the icon pack zip files are downloaded? It seems like that the icon packs are not saved for you, for whatever reason.
