### ISSUE TITLE
Make it work also for sidebar tabs

### ISSUE THREAD

**Issue by huachuman** [FlorianWoelki/obsidian-iconize#311]
**Is your feature request related to a problem? Please describe.**
The issue with putting notes in the sidebar is that it's impossible to tell them apart from each other because all their icons look the same:
![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/125603964/84dfd423-7812-4f00-ba93-2494c0e3db5a)

**Describe the solution you'd like**
Being able to display the icon in those tabs would instantly help tell notes apart.

**Describe alternatives you've considered**
The only way I've found to do it is by manually creating snippets, writing the note's title and getting the appropriate SVG path from a site like Remixicon:

```
.workspace-tab-header[aria-label^="Current Research Questions"]
> .workspace-tab-header-inner
> .workspace-tab-header-inner-icon
> .svg-icon.lucide-file{
    display: none;
}

.workspace-tab-header[aria-label^="Current Research Questions"]
> .workspace-tab-header-inner
> .workspace-tab-header-inner-icon{
	background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' width='18' height='18'%3E%3Cpath d='M5.76282 17H20V5H4V18.3851L5.76282 17ZM6.45455 19L2 22.5V4C2 3.44772 2.44772 3 3 3H21C21.5523 3 22 3.44772 22 4V18C22 18.5523 21.5523 19 21 19H6.45455ZM11 14H13V16H11V14ZM8.56731 8.81346C8.88637 7.20919 10.302 6 12 6C13.933 6 15.5 7.567 15.5 9.5C15.5 11.433 13.933 13 12 13H11V11H12C12.8284 11 13.5 10.3284 13.5 9.5C13.5 8.67157 12.8284 8 12 8C11.2723 8 10.6656 8.51823 10.5288 9.20577L8.56731 8.81346Z' fill='rgba(203,102,243,1)'%3E%3C/path%3E%3C/svg%3E");    background-size: 18px 18px; /* adopt this to your file tree font height */
    transform: translate(0px, 5px); /* to position the icon */
    background-repeat: no-repeat;
    display: inline-block;
    height: 18px;
    width: 18px;
    margin: -9px 0px 0 0;
}
```

**Additional context**
The manual snippet method is very cumbersome and each individual icon has to have its css renamed if the note title changes. It also requires meddling around with a website like Remixicon for getting SVG paths. I've given up on this method because it's too time consuming. Would be great if this plugin could be extended for this use case.

**Comment by FlorianWoelki** [comment]
What do you mean specifically with Sidebar? 

Iconize already adds the icons inside the `workspace-tab-header` class by enabling [icon in tabs](https://florianwoelki.github.io/obsidian-iconize/files-and-folders/icon-tabs.html).

**Comment by huachuman** [comment]
I don't know how I missed this but that is F********************** INCREDIBLE

THANK YOU I COULD KISS YOU
