### ISSUE TITLE
Shortcodes cannot be literally presented in inline codes/codeblocks

### ISSUE THREAD

**Issue by nuanjanP** [FlorianWoelki/obsidian-iconize#312]
**Describe the bug**
Not sure if this is the intended behavior but, shortcodes cannot be literally presented in inline codes or codeblocks.

**To Reproduce**

1. Make sure the "simple-icons" icon pack is installed and enabled.
2. Type the following anywhere: `` `:SiGoogle:` ``
3. Type the following anywhere: `<code>\:SiGoogle\:</code>`
4. Type the following anywhere: `<code>&colon;SiGoogle&colon;</code>`

**Expected behavior**

- **Expected** the string `:SiGoogle:` inside inline code in all three cases.
- **Actually got** Google logo inside inline code in all three cases.

**Comment by FlorianWoelki** [comment]
This is now fixed with version [2.8.1](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.8.1).
