### ISSUE TITLE
icons not resizing in titles and in headings

### ISSUE THREAD

**Issue by trceratps** [FlorianWoelki/obsidian-iconize#316]
**Describe the bug**
icons don't resize in titles and headings. i'm utilizing minimal theme and iconize version 2.8.0

**To Reproduce**
the inline heading part:
1. open a note 
2. try to put an icon inline in a heading

the title part:
1. enable "toggle icon in title"
2. open a note with a icon attached to it

**Expected behavior**
icons resize to the size of the headings.

**Screenshots**
<img width="1187" alt="image" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/152014371/4cfb0333-6c8c-4d5c-a0dc-3d20b0c0c1d5">

**Comment by FlorianWoelki** [comment]
Cannot reproduce. Minimal theme works fine for me!
