### ISSUE TITLE
Unable to modify the Icon Packs folder path.

### ISSUE THREAD

**Issue by antungchen** [FlorianWoelki/obsidian-iconize#317]
**Describe the bug**
To solve the issue with Obsidian Sync, I tried to follow the solution from [https://florianwoelki.github.io/obsidian-iconize/guide/syncing.html] and change the settings. However, when I modify the icon folder path and click 'save,' there is no response, and the plugin doesn't save my settings. When I reopen the settings, it reverts back to the original path.

**To Reproduce**
1. Go to Icon Folder Settings.
2. Change Icon Packs folder path.
3. Click on Save.
4. Saving in progress pops up.
5. Close and Open Icon Folder Settings again, the modifications I made earlier have not changed.

**Expected behavior**
The settings should save the icon packs folder path I changed.

**Screenshots**
![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/21006766/832dbc14-081d-456f-9de6-1effb2aeeaaa)

Edit 1:
For instance, when I change the path to (.obsidian/example) and then click save, the example folder is created in the .obsidian folder in my explorer. However, when I reopen the settings, the Icon Packs folder path is still the old path, not the updated .obsidian/example.

**Comment by FlorianWoelki** [comment]
This is now fixed with version [2.8.1](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.8.1).

**Comment by kahboom** [comment]
Having this same issue on the latest version. I do use iCloud for sync and have a lot of other plugins enabled, but I'm able to reproduce consistently. When I open Obsidian it gives me the error about not putting the path directlly in `plugins`, so I go and change it to `.obsidian/plugins` or some other path, and it works fine, then I restart Obsidian and the error shows again, and I can see the path has been reset. If you'd like for me to open a new issue please let me know @FlorianWoelki .

**Comment by FlorianWoelki** [comment]
Please open a new issue with a detailed description of the actual issue. Thank you :)
