### ISSUE TITLE
Icon rules ignore font size

### ISSUE THREAD

**Issue by Cruisername** [FlorianWoelki/obsidian-iconize#319]
**Describe the bug**
Icon rules ignore the font size setting. This only happens if a rule has a custom color specified for it.

**To Reproduce**
1. Go to Custom Icon Rules and make a new one.
2. Click on Edit custom rule and pick a color, then save changes.
3. Font size of that icon changes from the one specified in settings to a different one.

**Expected behavior**
Icon size should follow the Icon font size setting regardless of whether there's a color specified for it or not.

**Screenshots**
![Obsidian_4e5j94Pxks](https://github.com/FlorianWoelki/obsidian-iconize/assets/144732483/39a1f9f5-eac8-4d3d-bd8d-d6341b453487)

**Additional context**
Isn't particularly noticeable while using the default font size.

**Comment by FlorianWoelki** [comment]
This is now fixed with version [2.8.1](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.8.1).
