### ISSUE TITLE
hope to add a config item to determine the attribute name of the icon

### ISSUE THREAD

**Issue by BobbyJonas** [FlorianWoelki/obsidian-iconize#323]
**Is your feature request related to a problem? Please describe.**
I'm using the obsidian-banner plugin. There is an attribute item that configures the icon of the banner called `banner-icon`. I hope the iconize plugin can share this configuration item to get the icon from this attribute value and display it.

**Describe the solution you'd like**
hope to add a config item to determine the attribute name of the icon

**Comment by FlorianWoelki** [comment]
Iconize already has this. It uses `data-icon` to describe the icon used in the node.
