### ISSUE TITLE
Optimize settings page

### ISSUE THREAD

**Issue by benjaminwelch** [FlorianWoelki/obsidian-iconize#326]
**Describe the bug**
All three Icon Customizations aren't working for me. I can change font size, color, margin and nothing changes.

**To Reproduce**
1. Go to 'Icon Customization'
2. Change font size, icon color, extra margin.

**Screenshots**
<img width="1365" alt="Screenshot 2023-12-13 at 13 58 38" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/610197/1677d577-ad69-40d0-99a5-7543e081c9bd">

**Additional context**
This is a fresh vault with default theme and no other community plugins. I'm on macOS 13.4 (22F66)

**Comment by FlorianWoelki** [comment]
Yes this is intended. These settings are bound to the icons used for folders/notes. Might be worth to differentiate the settings ui a bit more.

**Comment by FlorianWoelki** [comment]
Styling like the color of an icon will be tracked at #301.

**Comment by FlorianWoelki** [comment]
Settings page has been optimized with [v2.8.2](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.8.2)
