### ISSUE TITLE
Improved live preview behavior for links

### ISSUE THREAD

**Issue by benjaminwelch** [FlorianWoelki/obsidian-iconize#327]
**Is your feature request related to a problem? Please describe.**
This may be related to: https://github.com/FlorianWoelki/obsidian-iconize/issues/315

**Describe the solution you'd like**
I would like the icons to behave exactly as other font pictograms or emoji behave in live preview.

**Issues:**
- Link color is ignored
- Not underlined
- Live preview behavior is different. Icon does not remain rendered when cursor is anywhere in line. Other icons remain rendered until you get next to the link, then the markdown syntax is revealed.

**Additional context**
![iconize_live_preview](https://github.com/FlorianWoelki/obsidian-iconize/assets/610197/8f000c2b-6aa7-4fd4-9ff3-5649174286c1)
[video](https://github.com/FlorianWoelki/obsidian-iconize/assets/610197/b912b801-146c-401b-bab0-211748bd9f37)

This is a fresh vault, default theme and no other community plugins. I'm on macOS 13.4 (22F66)

**Comment by FlorianWoelki** [comment]
Will be tracked in #315
