### ISSUE TITLE
Inherited icon doesn't display in tab bar

### ISSUE THREAD

**Issue by prurph** [FlorianWoelki/obsidian-iconize#328]
**Describe the bug**
Selecting inherit icon displays the icon in the file, but not in the tab bar or file explorer.

Explicitly set icons are displayed in all three places.

**To Reproduce**

1. Enable icons in tab bar and title
2. Select an icon for a parent folder
3. Select "inherit icon" for a child note

**Expected behavior**
Inherited icon should appear anywhere an explicit icon would, based on settings, in this case in the title bar, and in the tab bar. However, only the title bar is shown.

**Screenshots**

Inherited icon: no tab bar or explorer icon
![Inherited](https://github.com/FlorianWoelki/obsidian-iconize/assets/6109531/a29c7608-c110-4e3d-946d-b9f487bb85b6)

Explicit icon: tab bar and explorer icons (works whether using front matter or setting via right-click context menu on the file itself)
![Explicit](https://github.com/FlorianWoelki/obsidian-iconize/assets/6109531/c18a5178-bc33-482a-9592-9c243524bf7a)

**Comment by FlorianWoelki** [comment]
I think this would be more like a feature than a bug. Thanks for the suggestion!

**Comment by FlorianWoelki** [comment]
For me it works perfectly. I do have files which use inherited icons that are displayed in the title bar of the document.

**Comment by prurph** [comment]
Thanks for responding! Perhaps I'm being dumb, this is what I tried on Obsidian v1.4.16:

- Create new vault
- Install `obsidian-iconize`, enable, and select enable icons in tab bar and title. Install lucide-dev icons. Restart Obsidian
- Create a folder with a note inside.
- "Change icon" on parent folder to an icon
- "Inherit icon" on child file: select the same icon from the popup (aside: why does inherit icon give a popup to select the icon)
- Inherited icon does not appear in tab bar or file explorer

I don't think it's a font/css issue because I'm using all the defaults in a brand new vault. Could there be any default Obsidian settings that are preventing this from working, that you have changed to cause it to work?

**Comment by FlorianWoelki** [comment]
Gotcha! I'll think of some renaming in the future :D
