### ISSUE TITLE
Expose `Icon Manager` Getters

### ISSUE THREAD

**Issue by RomanMunar** [FlorianWoelki/obsidian-iconize#333]
**Context**
I'm looking to automate the creation of dirs i call `collections`

- [x] can attach icon to folder `addFolderIcon(path, icon)`
> a template for the root file. eg. Games/Games.md
> > with metadata `icon: <% quickadd.suggester(...available icons) %>`

**Describe the solution you'd like**
Export these getter functions
  getAllLoadedIconNames,
  getIconPackNameByPrefix,

**Comment by FlorianWoelki** [comment]
These functions are already exposed.
