### ISSUE TITLE
Render icons in the outline pane

### ISSUE THREAD

**Issue by mardukbp** [FlorianWoelki/obsidian-iconize#334]
**Is your feature request related to a problem? Please describe.**
When an icon is used in a section heading it is not rendered in the outline pane.

![grafik](https://github.com/FlorianWoelki/obsidian-iconize/assets/1140106/be0c087c-0bcf-4cea-8bee-61c3d9cf93fc)

**Describe the solution you'd like**
Render icons in the outline pane. 

**Describe alternatives you've considered**
Not use icons in section headings :(

**Additional context**
This feature would be in line with the project's motto "Simply add icons to anything you want in Obsidian."

**Comment by FlorianWoelki** [comment]
Thank you for the suggestion. Could you please quickly describe on how to enable or see the outline pane, so that I can reproduce it?

**Comment by mardukbp** [comment]
Sure. Just activate the "Outline" core plugin, open a note, expand the right side panel and on the top you will find the outline :)

**Comment by cip247** [comment]
was there a solution / hack  for this? 
Icons are not rendering in outline in the latest version of iconize.

To reproduce:

use Iconize icon in headline e.g.

## :FasArrowRightArrowLeft: Related

icon gets rendered as text when displayed in outline (right side)
in File-Navigation(left side)  icons displays fine.

**Comment by FlorianWoelki** [comment]
This is now part of Iconize since [v2.13.0](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.13.0).

**Comment by james-brown-ca** [comment]
I have version 2.14.7 installed (Obsidian version 1.9.14) and icons in the Outline plugin are not rendering.  I have disabled snippet.css and have switched to the default theme.

Sample MD:
`# :LiCalendar: 2025-10-03
## :LiList: Personal Notes
## :LiList: Notes
# :LiListCheck: wrap-up
# :LiCheckCircle2: Tasks completed today
`

<img width="279" height="255" alt="Image" src="https://github.com/user-attachments/assets/50123c0e-5eae-49d6-aec6-f66892c203eb" />
