### ISSUE TITLE
Opening file fails when icon is inside a table

### ISSUE THREAD

**Issue by darkryder** [FlorianWoelki/obsidian-iconize#336]
**Describe the bug**
Obsidian fails to open the file with the error: `Cannot read properties of null: (reading 'tagName')`.
This happens only when the file contains an icon inside a table cell.

**To Reproduce**
Obsidian will be able to open a file containing this snippet:
```
:LiCheck:

| A | B |
| --- | --- |
| 1 | Yes |
```

However, add a new row with an icon:
```
:LiCheck:

| A | B |
| ---- | ---- |
| 1 | Yes |
| 2 | :LiCheck: |
```

Obsidian fails to open this file with the above error. 

**Additional context**
On debugging, it seems to crash on this line:

`const tagName = element.firstElementChild.tagName.toLowerCase();`
`element.firstElementChild` is null since `element` is `<div class="table-cell-wrapper">:LiCheck:</div>`. Not entirely sure how to fix this.

_Community Plugins installed:_ Only obsidian-iconize:v2.8.1
_Obsidian version:_ 1.5.3

_Settings enabled_:
 - 'Icons Background Check'
 - 'Toggle Icons while editing notes'

**Comment by FlorianWoelki** [comment]
Thank you for reporting! 
Unfortunately, I was not able to reproduce this issue. I am not sure where the class `table-cell-wrapper` comes from? Maybe a theme or something?

For me, the table nodes do not have any classes at all.

**Comment by darkryder** [comment]
The default theme has the same issue. I have not enabled any custom CSS rules or any other community plugin.
Fwiw, it broke when I updated to Obsidian 1.5.3 (released 4 days ago).

If we still can't reproduce it, we can archive this issue. I don't mind changing my :LiCheck: to "Yes". We can wait to see if more folks face the same problem before trying to solve this 'bug'.

**Comment by FlorianWoelki** [comment]
> The default theme has the same issue. I have not enabled any custom CSS rules or any other community plugin. Fwiw, it broke when I updated to Obsidian 1.5.3 (released 4 days ago).
> 
> If we still can't reproduce it, we can archive this issue. I don't mind changing my :LiCheck: to "Yes". We can wait to see if more folks face the same problem before trying to solve this 'bug'.

Oh yep nvm. I can reproduce it now. I was still on version 1.4 :D

**Comment by DRA6N** [comment]
Pretty sure this is related. If I have an icon within a table, it then freezes the ability to edit within the table, and only displays a "loading bar" as if trying to load the table and everything else below the table. Took a while to figure out which plugin was causing the issue. Iconize is 100% the culprit. I have a video recording of it but github only supports 10MB. I can link it if needed.
