### ISSUE TITLE
Emoji style 'twemoji' in title and property not working properly

### ISSUE THREAD

**Issue by kbhbhk** [FlorianWoelki/obsidian-iconize#338]
**Describe the bug**

If I set emoji style option to twemoji instead native, not showing properly in title and property value tab.
Keep showing native emoji.

**To Reproduce**

1. set emoji style as twemoji
2. enable icon in title opt
3. or also icon in frontmatter opt

**Expected behavior**

Should show twemoji instead native.

**Screenshots**

![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/130442702/d64c1de1-7068-440c-a418-41368d3f859e)

![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/130442702/bbb4272c-22dd-4113-8f62-5e5fd0ddee62)

**Additional context**

This is currently happening in Windows, but I'm not sure about other OSs.

Many thanks!

**Comment by FlorianWoelki** [comment]
This issue has been fixed with [v2.8.2](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.8.2)

**Comment by kbhbhk** [comment]
Thanks so much!

**Comment by FlorianWoelki** [comment]
> Thanks so much!

Thank you for your support and patience! :)
