### ISSUE TITLE
In-line Icons Are Off-Grid

### ISSUE THREAD

**Issue by BaughBerry** [FlorianWoelki/obsidian-iconize#341]
**Describe the bug**
In-line icons are off-grid, where the top of the icon is higher than the top of the font.

**To Reproduce**
1. Create an in-line icon next to regular text.

**Expected behavior**
Icons are aligned correctly with text

**Screenshots**
<img width="301" alt="Screenshot 2024-01-04 at 10 41 19 AM" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/129925078/fa394bf6-ba3a-45cd-92a7-7cd0626135c8">

**Comment by FlorianWoelki** [comment]
This is now fixed in [v2.9.1](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.9.1).
