### ISSUE TITLE
Interferes with basic formatting of selected text

### ISSUE THREAD

**Issue by lydiabrundisch** [FlorianWoelki/obsidian-iconize#342]
**Describe the bug**
Selected text cannot be modified by bold, italics, highlights, striked-through, brackets, quotes, or checkbox. 

**To Reproduce**
1. Create a file with both some text and some icons

```
## Text 

ab
cd
ef

## :TiBrain: 

:LiFolderOpen: 
```

1. Select the text `ab cd ef`.
2. Press formatting keys (*, =, ~, [, (, ', ", `, checkbox hotkey which is ctrl + L in my case). 
3. Either nothing happens (in the case of =, ~, checkbox hotkey) or the selected text is deleted and the key's symbol is substituted (*, [, (, ', ", `). 
4. If only a single line is selected, the error does not occur for the checkbox hotkey, but the key's symbol is again substituted for the text for all other cases (*, =, ~, [, (, ', ", `, checkbox hotkey).
5. If the `## :TiBrain:` is deleted and multiple lines are selected, the error also does not occur for the some cases (=, ~, checkbox hotkey), but remains for all others (*, [, (, ', ", `).
6. If the the `## :TiBrain:` is deleted and only a single line is selected, the error also does not occur in any case.

**Expected behavior**
The selected text should be wrapped by these formatting symbols, as is Obsidian's default behavior.

**Comment by FlorianWoelki** [comment]
This is now fixed in [v2.9.1](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.9.1).
