### ISSUE TITLE
Problem with icon syncronisation

### ISSUE THREAD

**Issue by martin-arg** [FlorianWoelki/obsidian-iconize#343]
**Describe the bug**
The icons are not synchronised between different clients.

**To Reproduce**
I set the icons in one client and sync.

**Additional context**
I don't know if it is relevant but for synchronisation I use "Note sync share". 

One question, where is the icon info save?

**Comment by FlorianWoelki** [comment]
If you are using icons for files and folders see [this documentation](https://florianwoelki.github.io/obsidian-iconize/guide/syncing.html). Icons used in notes are currently not synced correctly (see #344).

**Comment by martin-arg** [comment]
I'm using it for files and folders. I already read that page, and done as suggest. Still no icon is sync.

**Comment by FlorianWoelki** [comment]
Unfortunately I cannot help you further with this problem because I am not able to reproduce any syncing issues. The main problem relies on the amount of icons you've stored. Using the background checker mainly solves the issues.
