### ISSUE TITLE
Not working on mobile

### ISSUE THREAD

**Issue by dxcore35** [FlorianWoelki/obsidian-iconize#345]
- error message on start
- I installed the icon pack again via mobile, the installed iconpack on PC was not synchronized via Obsidian Sync
- the icons are not shown

![IMG_8192](https://github.com/FlorianWoelki/obsidian-iconize/assets/7279156/973eb5e2-688f-4c1d-bfe4-b024c6c8a002){: width="200px"}
![IMG_8194](https://github.com/FlorianWoelki/obsidian-iconize/assets/7279156/94f0f980-d091-478f-8120-5cea4113efda){: width="200px"}
![IMG_8193](https://github.com/FlorianWoelki/obsidian-iconize/assets/7279156/00e9bc1f-c883-4aa3-b5ba-b2b8b06c64ae){: width="200px"}

**Comment by FlorianWoelki** [comment]
If you are using icons for files and folders see [this documentation](https://florianwoelki.github.io/obsidian-iconize/guide/syncing.html). Icons used in notes are currently not synced correctly (see #344)
