### ISSUE TITLE
Missing option to change individual icon color

### ISSUE THREAD

**Issue by Hyperlooper** [FlorianWoelki/obsidian-iconize#350]
I don't seem to have the option in my context menu to change the color of individual icons as I see described in the features. 

OS: windows 10

**Comment by FlorianWoelki** [comment]
> I don't seem to have the option in my context menu to change the color of individual icons as I see described in the features. 
> 
> 
> 
> OS: windows 10

The icon has to be an individually set icon. That means, this doesn't work for custom rules. Please also make sure to update to the latest version.
