### ISSUE TITLE
New inheritance rules. 

### ISSUE THREAD

**Issue by Drakemoor** [FlorianWoelki/obsidian-iconize#351]
It is so much harder to manipulate and maintain inheritance icons. The rules do not always work. 
The buttons after each rule for file/folder/everything work in conjunction with the toggle button inside the edit rule form is super confusing. 

I wish there was an easy way to roll back to a previous version.

**Comment by FlorianWoelki** [comment]
adding inheritance won't happen because it means double unnecessary maintainability for me. i'll try my best to enhance the custom rule functionality and ux.

**Comment by FlorianWoelki** [comment]
I've tried to optimise the custom rules and their descriptions in [v2.12.0](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.12.0).
