### ISSUE TITLE
Have icons appear in notes

### ISSUE THREAD

**Issue by wesbaker** [FlorianWoelki/obsidian-iconize#355]
### Is your feature request related to a problem? Please describe.
I want the icon I assign to a page to show up when I create a link to it in another note. 

### Describe the solution you'd like
Ideally, I think you'd either leverage the existing custom rules or make something similar because I don't always want ~~the icon to appear in notes, just sometimes~~ every icon for every note, just some rules (e.g. I want the person icon next to people every time).

### Describe alternatives you've considered
You can use [Supercharged Links](https://github.com/mdelobelle/obsidian_supercharged_links) and [Style Settings](https://github.com/mgmeyers/obsidian-style-settings) to prepend text (emoji) to achieve a similar idea, but I'd rather use icons from Iconize to do the same thing.

#### Supercharged links
<img width="588" alt="Screenshot 2024-01-19 at 12 48 29 PM" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/15715/c55145eb-d800-4d0d-93ca-9d0dd775f444">

#### Style settings
<img width="837" alt="Screenshot 2024-01-19 at 12 49 07 PM" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/15715/1490a687-4ca7-4f61-bb4e-ad08a114a50a">

**Comment by BaughBerry** [comment]
This would be nice to have, especially because Supercharged links only supports emojis

**Comment by rx-chris** [comment]
Upvote!!! I see lots of customization potential if we can append custom icons to markdown links

**Comment by FlorianWoelki** [comment]
This is now released with the version [v.2.11.0](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.11.0).

**Comment by ngirard** [comment]
Thanks for you work !
Would you mind adding instructions, especially for transitioning from Supercharged links ?
Thanks in advance !

**Comment by FlorianWoelki** [comment]
> Thanks for you work ! Would you mind adding instructions, especially for transitioning from Supercharged links ? Thanks in advance !

I am not familiar with Supercharged Links, thus I cannot add any description of transitioning to Iconize. Additionally, it's not a full replacement of Supercharged Links.

**Comment by rx-chris** [comment]
I wonder if it is just me but my icons do not show up in links for reading view. It does show up in links for source mode and live preview though.
