### ISSUE TITLE
Icons removed by Linter plugin

### ISSUE THREAD

**Issue by jorblet** [FlorianWoelki/obsidian-iconize#356]
Icons are removed from files in File Explorer whenever I "lint" a file using the [Obsidian Linter plugin ](https://github.com/platers/obsidian-linter)

**Steps to reproduce the behavior:**
1. Install [Obsidian Linter plugin ](https://github.com/platers/obsidian-linter), with barebones settings enabled.

2. Right click on file with an icon in File Explorer and click "Lint file"
<img width="550" alt="Screenshot 2024-01-21 at 8 57 02 AM" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/8532102/77db8914-be12-4ba8-b9f4-4df5c067591b">
<img width="595" alt="Screenshot 2024-01-21 at 8 57 13 AM" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/8532102/1938e072-48fc-4a69-b738-4fd3683c785f">

3. Icon on the file will be removed
<img width="529" alt="Screenshot 2024-01-21 at 8 57 22 AM" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/8532102/322aeaad-3c46-40b0-acaa-48d98a6be15b">

**Additional context**
I've searched documentation for both plugins (Iconize and Linter) and couldn't find any way to prevent this from happening.

**Comment by simonfossom** [comment]
this is not happening to me. 

maybe diff in rules? 🤔 

don't escape special characters. it will do the following /:icon/: and that's why it will stop working. but it might be something else.

**Comment by jorblet** [comment]
I didn't have that option selected in Linter but I did more testing (turned off all custom snippets and all plugins, except Iconize). 

I fixed it by turning off "Use icon in frontmatter" in the Iconize plugin settings. No clue why that fixed it but it did.

**Comment by FlorianWoelki** [comment]
i am going to close this issue for now. i don't see anything i can do here.
