### ISSUE TITLE
add iconColor: to the frontmatter

### ISSUE THREAD

**Issue by JamesVertisan** [FlorianWoelki/obsidian-iconize#358]
I love being able to specify the icon: in the frontmatter. Can you please add a simple addition to allow iconcolor: to be add to the frontmatter for automatic binding. Some other plugins interfere with the normal approach, but pulling the icon from the frontmatter works perfectly.

I manually changed the main.js personally to include that functionality, but it's much, much better for that addition to come directly from the plugin developer. it should only be a 5-10 minute change. Please help. Thanks in advance.

**Comment by FlorianWoelki** [comment]
This is now released with the version [v.2.11.0](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.11.0).
