### ISSUE TITLE
Icons Stop Rendering After Restart

### ISSUE THREAD

**Issue by BaughBerry** [FlorianWoelki/obsidian-iconize#362]
**Describe the bug**
After restarting my computer/Obsidian, my folder icons stop rendering as icons and simply show up as their icon name. To get them to render again, I have to manually choose the icon again.

**To Reproduce**
1. Completely quit Obsidian
2. Restart

**Expected behavior**
Icons should render after a restart.

**Screenshots**
<img width="258" alt="Screenshot 2024-01-25 at 10 05 15 AM" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/129925078/f3655347-1724-4b0b-8758-948ff5aaf9a7">

**Comment by BaughBerry** [comment]
I should note that it doesn't always do this every single time, and it doesn't always fail to render every icon, sometimes it's just some of them fail to render.

**Comment by simonfossom** [comment]
same here. it shows after some time. I think it's because the async loading of the plugin.

Give it a min. also, if you have a lot of plugins, consider removing plugins you don't use or at least disabling them.

(Note: a lot => more than 10)

**Comment by FlorianWoelki** [comment]
I've added a check which preloads your added icons which should appear mostly immediately. However, it can still take some time. I'll close this issue for now. Feel free to create a new one, if needed.
