### ISSUE TITLE
Font Awesome Icons missing when opening synched vault on a different machine.

### ISSUE THREAD

**Issue by Hyperlooper** [FlorianWoelki/obsidian-iconize#364]
**Describe the bug**
When using the font-awesome icon packs, these icons are missing when opening your vault on a second machine.

**To Reproduce**
1. Add icon to folder and sync
2. open obsidian vault on another machine
3. icons are missing

**Expected behavior**
Icons should sync to your vault across machines. 

**Screenshots**
![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/7346880/d7708c6a-9a84-47ad-9a1f-0f3a16e1d01d)
![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/7346880/a5e26028-8774-496e-a8d8-6f107dad01b7)

**Additional context**
You can see in the screenshot, that the font-awesome icon packs do appear to be present on the second machine, but the icons themselves are not.

**Comment by FlorianWoelki** [comment]
if you are using obsidian sync, i highly recommend reading [this documentation](https://florianwoelki.github.io/obsidian-iconize/).
