### ISSUE TITLE
Add 'iconcolor' to frontmatter

### ISSUE THREAD

**Issue by JamesVertisan** [FlorianWoelki/obsidian-iconize#365]
There are issues syncing between multiple devices and my icon settings are frequently lost. Please add 'iconcolor' as hex (without the pound sign) to the frontmattter and bind to that. That would eliminate the issue with icon color being lost.

example:
icon: FarDoc
iconcolor: aabb22

**Comment by Oddward** [comment]
You could've added this as a comment to your previous issue https://github.com/FlorianWoelki/obsidian-iconize/issues/358 

fair idea, but it should also support named colours like `yellow`

**Comment by FlorianWoelki** [comment]
closing because of duplicate #358
