### ISSUE TITLE
Icon lost when changing note properties

### ISSUE THREAD

**Issue by weekens** [FlorianWoelki/obsidian-iconize#367]
**Describe the bug**

Note icon is lost when creating or changing properties of a note (the ones under `---`).

**To Reproduce**
1. Set an icon for a note.
2. Open note, create the properties section with `---`, if not yet created.
3. Set a new property with value.
4. Note icon is lost.

**Expected behavior**
The note icon should remain unchanged disregarding of how you change the properties or other data.

**Additional context**
Obsidian v1.5.3.

**Comment by masteryoda1997** [comment]
this could be a similar issue so let me add it here.

in my case the note Icon appears when the note property is changed.

https://github.com/FlorianWoelki/obsidian-iconize/assets/40969575/2d257121-6bfc-4958-a6fc-164f182ecec2

**Comment by FlorianWoelki** [comment]
it seems related to #375. therefore, i'll close this issue for now.
