### ISSUE TITLE
Tooltip icon codes are sometimes incorrect

### ISSUE THREAD

**Issue by Jademalo** [FlorianWoelki/obsidian-iconize#381]
**Describe the bug**
[As per the documentation](https://florianwoelki.github.io/obsidian-iconize/good-to-know/see-icon-name.html), the tooltip should show the prefix of the icon pack before the name to make remembering codes for specific icons easier. However, for `Si` icons, this doesn't seem to work.

**To Reproduce**
1. Set an icon to a Simple Icons icon
2. Hover over the icon in the file list

**Expected behavior**
It should display the name of the icon with the prefix in the same manner as other icon packs.

**Screenshots**
![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/386846/30f7e82b-ce68-406d-acbc-3d3c5150cd70)
![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/386846/20066bf9-71df-420d-ae83-a19cd37e0dc8)
The first image uses Font awesome brands, the second image uses Simple Icons.

**Comment by FlorianWoelki** [comment]
thank you for the report. the issue was with simple icons.

**Comment by FlorianWoelki** [comment]
This is now released with the version [v.2.11.0](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.11.0).
