### ISSUE TITLE
[Question] - Where to download icons?

### ISSUE THREAD

**Issue by JordanPicton** [FlorianWoelki/obsidian-iconize#382]
I'm having a problem with some SVG's when using the custom packs. When downloading them some of them are black only and don't change colour?

I'm just wondering if anyone has some more insight on how I should be including these SVG's so far I've tried iconmonstr and icon8 for the downloads though not all of them work as what I was talking about above. Where should I be looking for Icons along with should I be looking for anything in specific when downloading the icons?

Thanks in advance,
~Jordan

**Comment by FlorianWoelki** [comment]
hey, thanks for the question.

first off, custom icon packs are not fully functional. see [this note in the docs](https://florianwoelki.github.io/obsidian-iconize/guide/icon-packs.html#custom-icon-packs). so, some icon packs might work and some not.
i highly recommend, for now, just use the supported ones as they will work. i am btw. also keeping track of this issue at #224.

will close this issue for now.
