### ISSUE TITLE
Clash in Editing Mode with Obsidian Tasks

### ISSUE THREAD

**Issue by chrabia** [FlorianWoelki/obsidian-iconize#385]
**Describe the bug**
Icons in Editing Mode change back to ":Icon:". Also, it doesn't help changing mode Editing->Reading->Editing. Only things that helps is opening the note again.

**To Reproduce**
The bug happens along with Obsidian Tasks being used. When setting task as done, the document in which the task was created loses all the icons (in Editing Mode), they go back to being in the ":Icon:" format.

**Expected behavior**
Icons stay as icons.

**Screenshots**
<img width="93" alt="image" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/6050673/1df1cd74-7efe-4d22-85ae-7e0d8940027b">

**Additional context**
Maybe it should be fixed on Obsidian Tasks side? I don't know, sounds like it might be a quick fix on your side. Also it might be something that could clash in Iconize with some other plugins/things in Obsidian, but wasn't reported yet.

**Comment by FlorianWoelki** [comment]
this should be fixed with the latest version [v2.11.12](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.11.12)
