### ISSUE TITLE
Conflict with metadatamenu

### ISSUE THREAD

**Issue by LeonardoGentile** [FlorianWoelki/obsidian-iconize#389]
**Describe the bug**
As per https://github.com/mdelobelle/metadatamenu/issues/623 the two plugins seems to have a conflict when setting an icon in metadatamenu

<img width="528" alt="image" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/412061/30a3192f-343f-4a75-900c-91ac604a6310">

<img width="1448" alt="image" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/412061/ec62f9e5-2924-4ef7-98f9-a74ffa2632e7">

<img width="844" alt="image" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/412061/5f3b8432-bd9d-4ee2-a0b3-8d14d1f50d39">

The error goes away if I either disable `obsidian-iconize` entirely or disable `use icon in frontmatter`
So I guess the trouble comes from using the same property named `icon`

I'm not sure if this can be fixed, probably using an alternative field name as alias in case of these kind of conflicts?

**Comment by dml0sc** [comment]
I had opened an issue #434 (see [#434](https://github.com/FlorianWoelki/obsidian-iconize/issues/434)). It should have been solved in 2.11.09 – but it is still there in 2.11.10 – MDM icons are gone if Iconize is active

**Comment by FlorianWoelki** [comment]
> **Describe the bug** As per [mdelobelle/metadatamenu#623](https://github.com/mdelobelle/metadatamenu/issues/623) the two plugins seems to have a conflict when setting an icon in metadatamenu
> 
> <img alt="image" width="528" src="https://private-user-images.githubusercontent.com/412061/309924024-30a3192f-343f-4a75-900c-91ac604a6310.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwODM0MzgsIm5iZiI6MTcxMzA4MzEzOCwicGF0aCI6Ii80MTIwNjEvMzA5OTI0MDI0LTMwYTMxOTJmLTM0M2YtNGE3NS05MDBjLTkxYWM2MDRhNjMxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNFQwODI1MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNmNhOWJmNjliZmMxOTAxMjhmMGIyZGY3MDcwZWI2OWJmOTM0OTFiZThlN2QyNTcxZGEzYzBiZjhmMjNkZGU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.To_ppx_yVPUjfIILlfDo7Fi-0JQvN4ZSK5vRe6But5E"> <img alt="image" width="1448" src="https://private-user-images.githubusercontent.com/412061/309924507-ec62f9e5-2924-4ef7-98f9-a74ffa2632e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwODM0MzgsIm5iZiI6MTcxMzA4MzEzOCwicGF0aCI6Ii80MTIwNjEvMzA5OTI0NTA3LWVjNjJmOWU1LTI5MjQtNGVmNy05OGY5LWE3NGZmYTI2MzJlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNFQwODI1MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZmRhNzg2MTNmMGU1MDQyYzg2MGIyYzk0MTkwYjQ4ZmM1MmUxZGQ3ZmYwMTUwYzRmYWYyMjE1M2Y1ZDAwYjc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UXzrcIIXUS45lsz_JP7d78vb93RJHeK8OIvOjEeoNs4"> <img alt="image" width="844" src="https://private-user-images.githubusercontent.com/412061/309924666-5f3b8432-bd9d-4ee2-a0b3-8d14d1f50d39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwODM0MzgsIm5iZiI6MTcxMzA4MzEzOCwicGF0aCI6Ii80MTIwNjEvMzA5OTI0NjY2LTVmM2I4NDMyLWJkOWQtNGVlMi1hMGIzLThkMTRkMWY1MGQzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNFQwODI1MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMTY3NGYzZDYzOWEwOGMxOTMxZTM4M2EzNjkzYjVhMzkzZDE3MDIyMTZkNTQ3OTRhMDllYjJiNDE2YjA1YWIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5_H66y9e_oBx1oPJeTq0arxlFVkpWYvTUvXdDYz9Axk">
> The error goes away if I either disable `obsidian-iconize` entirely or disable `use icon in frontmatter` So I guess the trouble comes from using the same property named `icon`
> 
> I'm not sure if this can be fixed, probably using an alternative field name as alias in case of these kind of conflicts?

could you check out the latest version [v2.11.11](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.11.11) and see if that fixes the collision with metadatamenu? you can customize the name of the frontmatter field in the settings.

**Comment by dml0sc** [comment]
It seems to work now – thank you. Dataview renders perfectly also with Metadata Menu cards created on canvasses.

**Comment by FlorianWoelki** [comment]
> It seems to work now – thank you. Dataview renders perfectly also with Metadata Menu cards created on canvasses.

that's lovely! I'll close this issue for now!

**Comment by LeonardoGentile** [comment]
Hello @FlorianWoelki, how was this fixed? Should we use a different frontmatter field name or everything remains unchanged? Should we keep using the `icon` field even if ti's the same field used by MDM?

**Comment by FlorianWoelki** [comment]
> Hello @FlorianWoelki, how was this fixed? Should we use a different frontmatter field name or everything remains unchanged? Should we keep using the `icon` field even if ti's the same field used by MDM?

you can feel free to change the frontmatter field name in the settings of Iconize to e.g., `iconizeIcon`. that should resolve the compatibility between these two plugins.
