### ISSUE TITLE
Icon Disappearing Upon Unpinning a Note

### ISSUE THREAD

**Issue by j-finger** [FlorianWoelki/obsidian-iconize#391]
**Describe the bug**
The icon associated with a note disappears when the note is unpinned.

**To Reproduce**
1. Go to the notes section.
2. Click on the pin icon of a note to unpin it.
3. Observe that the icon of the note disappears.

**Expected behavior**
When a note is unpinned, the icon should remain visible. The only change should be the state of the note from pinned to unpinned.

**Screenshots**
![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/80647966/c311147b-e7c6-4830-8c9d-bcf3ea9a66de)

![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/80647966/664341e7-faab-4963-b4c2-67bac833b6a2)

**Comment by FlorianWoelki** [comment]
This is now released with the version [v.2.11.0](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.11.0).
