### ISSUE TITLE
Icons Disappearing Between My Two Computers

### ISSUE THREAD

**Issue by pinetreemoonlight** [FlorianWoelki/obsidian-iconize#392]
### **Describe the bug**
All folder icons that I use, except for one (Inbox (Fas)) disappear whenever I switch between my Windows desktop computer and my Macbook. I use Obsidian Sync with all Sync options (add-ons, etc.) enabled. 

Toast error message: _"Seems like you do not have an icon pack installed (icon pack name)"_  - but the respective icon packs are installed when I check my settings (see screenshots).

When I set the icons again, they will disappear again when I switch to my other device.

### **To Reproduce**
1. Open Obsidian on e.g. Windows PC
2. Right-click folder, "# Change Icon"
3. Set some icon for the folder
4. Close Obsidian on Windows device
5. Open Obsidian on Macbook
6. Icons are gone

### **Expected behavior**
Icons should still be there.

### **Screenshots**
**Error Messages about Li and Ra icon packs missing:**
![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/115622756/93486b73-0d16-46a8-9e7a-7d1b1f4d6706)
**But Li and Ra icon packs are installed:**
![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/115622756/81cf3e53-dd67-4d1b-b07f-09b3b3f11098)

### **Additional context**
I use Obsidian Sync with all Sync options enabled. My vault folders on Windows and MacOS devices are **not** synced by any other program (e.g. iCloud or GDrive).

**Comment by FlorianWoelki** [comment]
Iconize has some problems with Obsidian Sync. See [this documentation](https://florianwoelki.github.io/obsidian-iconize/guide/syncing.html) for more reference.
