### ISSUE TITLE
Icons inside callouts remove callouts icon and mess up with their folding

### ISSUE THREAD

**Issue by Rexus752** [FlorianWoelki/obsidian-iconize#395]
I'm trying to use Iconize icons inside my callouts, but they seem to create some problems. Here's a few problems I've found:

**Normal behaviour of a callout without icons inside it**
First, here's my callout without any Iconize icon inside it, working as it should:
![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/32108270/c9330ab2-eea7-489b-ba1e-963b857380ce)
Here's the "code":
![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/32108270/19e90b65-1827-42ad-87eb-1e55a465bb6b)

**Icons inside the callout remove the callout icon**
Now, if I try to put an Iconize icon in my callout like this:
![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/32108270/057f92e6-967c-4cbe-ac83-554f442b82e1)
Here's how the callout gets rendered, without its icon:
![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/32108270/dfa3c837-1ff0-44dd-b3f2-06bdc971c869)

**Icons inside the callout mess up with its folding**
And, if I try to make the callout foldable by adding a minus after the square brackets:
![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/32108270/987e0a13-5f80-4969-895e-c2dc0e2282c1)
It renders the folded callout (without its icon as before), but I also can't click on it to expand:
![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/32108270/563a6445-86eb-4c76-854f-fdf0d9e0266a)

**Comment by mtomas7** [comment]
I also noticed this problem, but it is not related to using icons inside of a call out, but presence of a Far or Fas icon in the note or in the Note Title in general.

It looks to me that under the hood Obsidian is using the FontAwsome icons and once Fas of Far icon sets are enabled and used in the particular note, the Obsidian callouts stop displaying icons. I would predict it is because of the same icon CSS name or, because iconset is registered second time.

Once you pick other icon set, problem is gone. Perhaps plugin could use Fas and Far from the system as it is already embedded?

**Comment by sigrunixia** [comment]
> Obsidian is using the FontAwsome icons

Obsidian does not bundle FAS Icons, but Lucide.

**Comment by irateSquirrel** [comment]
Came here to report this bug myself, because it took me a bit to figure out what was going on there. For what it's worth *embedding* a section, that contains an icon, into a callout does not create this problem.

**Comment by FlorianWoelki** [comment]
thanks for reporting this issue. unfortunately, I am not able to reproduce this issue. could it be fixed with [v2.11.10](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.11.10)?

**Comment by Rexus752** [comment]
Yes, I updated the plugin to v2.11.10 and now it works as it should. Thanks! 😄

**Comment by FlorianWoelki** [comment]
> Yes, I updated the plugin to v2.11.10 and now it works as it should. Thanks! 😄 

nice to hear that!
