### ISSUE TITLE
Iconize not replacing folder icons: instead, displaying both standard icon and custom icon side-by-side

### ISSUE THREAD

**Issue by sicahjes** [FlorianWoelki/obsidian-iconize#396]
**Describe the bug**
Just installed plugin for the first time, following [instructions here](https://florianwoelki.github.io/obsidian-iconize/). Instead of replacing the standard folder icon, it is displaying the custom icon next to it:

![Iconize Double Icons](https://github.com/FlorianWoelki/obsidian-iconize/assets/28281659/2e65af6f-e4ca-48b2-801d-65b13543145a)

**To Reproduce**
1. Go to 'Obsidian files panel'
2. Right click on a folder to bring up options menu.
3. Select 'change icon'.
4. Choose icon from menu by clicking on it.
5. See error.

**Expected Behaviour**
Newly selected icon to replace existing icon. 

**Additional Context**
In an attempt to troubleshoot, I have turned on all toggles in settings. I also have the following plugins installed:

- Admonition
- Advanced Tabled
- Better footnote
- Creases
- Custom File Explorer Sorting
- DataLoom
- Dataview
- Footnote Shortcut
- Highlights
- Iconize
- Icons
- Obsidian Glossary
- QuickAdd
- Reading Comments
- Style Settings
- Template
- Timelines
- Zotero Integration

**Comment by gabrielf11** [comment]
I had this issue as well but I was able to solve it by using the default theme rather than the community theme that I was using before (Border).

**Comment by sicahjes** [comment]
Thanks for responding. It turns out this was the issue (the good folk over at the Obsidian Forum helped me figure it out).

Fortunately, the Border theme works with the Style Settings plugin. If you would like to continue using this theme, you can do this by going to: _Components > File Explorer > Icon_ and then check '_Remove custom Icon_'.

![Screenshot 2024-04-14 at 11 18 42](https://github.com/FlorianWoelki/obsidian-iconize/assets/28281659/b9165d03-0acf-40bf-af87-bcef79cec8ca)

**Comment by FlorianWoelki** [comment]
i am going to close this issue for now.
