### ISSUE TITLE
Colored icons not shown in tabs

### ISSUE THREAD

**Issue by MarioFlying** [FlorianWoelki/obsidian-iconize#397]
**Describe the bug**
When using [Icon in Tabs](https://florianwoelki.github.io/obsidian-iconize/files-and-folders/icon-tabs.html) together with [Change individual icon color](https://florianwoelki.github.io/obsidian-iconize/files-and-folders/individual-icon-color.html), only the icons without color data are shown in tabs.

**To Reproduce**
1. Disable any other third party Obsidian plugin/theme and relaunch Obsidian to exclude outside influence
2. Enable "Icon in Tabs"
3. Change a file's icon color
4. Select the tab
5. Watch the corresponding tab icon disappear, replaced by the default icon
6. Reset the file's color data
4. Select the tab again
7. Watch the corresponding tab custom icon appear in the tab

**Expected behavior**
Custom colored icons showing up in tabs

**Screenshots**
![Schermata_20240321_114050](https://github.com/FlorianWoelki/obsidian-iconize/assets/2698205/0c93c305-e674-4979-b2b4-7a48c42314af)
⬇️  
![Schermata_20240321_125540](https://github.com/FlorianWoelki/obsidian-iconize/assets/2698205/93ed18ee-716c-4c24-b654-65c20586fd57)

**Additional context**
Removing any icon rule, including the "." icon rule, and re-launching Obsidian seems to have no effect.
Disabling other Iconize options has no effect, either.

**Comment by FlorianWoelki** [comment]
This issue has been resolved in [v2.11.3](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.11.3).
