### ISSUE TITLE
Keyboard shortcut to Change Icon for current note

### ISSUE THREAD

**Issue by slnc** [FlorianWoelki/obsidian-iconize#398]
**Is your feature request related to a problem? Please describe.**
When I want to add an icon to a note I have to:
- grab the mouse
- right click on the note
- click on Change Icon
- remember the name of the icon I want
- type it
- click again to select it

This is more work than using a keyboard shortcut.

**Describe the solution you'd like**
Could you please add support to change a note's icon using a keyboard shortcut? Ideally it would be possible to create shortcuts to set specific icons, but I understand that might be too hard to implement.

**Additional context**
I use Obsidian as my D&D campaign notes organizer and I use Iconize to categorize encounters based on their main type. This means I have to repeat the steps above a lot of times per session.

<img width="339" alt="image" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/69429/07b52260-f140-409c-8508-ebcec20a4f8b">

**Comment by FlorianWoelki** [comment]
this feature is now available in [v2.11.13](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.11.13).

**Comment by slnc** [comment]
Works great, thanks Florian!
