### ISSUE TITLE
Unable to copy/paste HEX color codes

### ISSUE THREAD

**Issue by dcamel** [FlorianWoelki/obsidian-iconize#399]
Hey everyone!  Absolutely LOVE this plugin.  Thank you so much for making and maintaining it!

**Issue:**
When changing the HEX color code, I'm unable to copy and paste information into the field. 

![2024-03-24_164750](https://github.com/FlorianWoelki/obsidian-iconize/assets/147558389/05c4e5a7-3c5f-41ed-ab67-43670658e637)
![2024-03-24_164817](https://github.com/FlorianWoelki/obsidian-iconize/assets/147558389/92f87eac-5deb-4004-9a39-a10cb5990e3c)

In these two image examples, I am want to use the first color value of #DAAE62 on a newly created icon from the File Explorer.
1.  I right click the File explorer entry -> change color of icon
2.  I click on the current color
3.  Switch to HEX
4.  And am unable to both **copy** and **paste** information from this field.

Currently on updated Windows 10, 
Using updatedObsidian 1.5.11

**Comment by FlorianWoelki** [comment]
Really appreciate that you love the plugin!

However, I think that this is an issue with Obsidian itself. I am only using the predefined functionality of the color picker provided by Obsidian. So I think you should raise an issue there.
