### ISSUE TITLE
Not icon on Tabs for .canvas .kanban .excalidraw

### ISSUE THREAD

**Issue by tonypuglieso** [FlorianWoelki/obsidian-iconize#402]
**Describe the bug**
Not icon on Tabs when they are not .md example .canvas .kanban .excalidraw

**To Reproduce**
1 Create a kanban or canvas file, change the icon (they work fine on three view panels)
2 Open the file, and in the tab view they have the icon of type file canvas|kanban|excalidraw

**Expected behavior**
Change icons on other type files.

**Screenshots**
![2024-03-25_152231718_Obsidian_9uIU9M5dcl_Tony-Projs_-_ obsidian _-_Obsidian_v1 5 11](https://github.com/FlorianWoelki/obsidian-iconize/assets/52177646/68620dfc-da1c-4af4-ae66-e69ec610a044)

![2024-03-25_152219136_Obsidian_v5kr7lyBZI_Tony-Projs_-_ obsidian _-_Obsidian_v1 5 11](https://github.com/FlorianWoelki/obsidian-iconize/assets/52177646/0cdf3e10-d722-400b-b7b8-e97b77388f9f)

If possible to change this for this plugin, snippets or change the config on obsidian?

**Comment by FlorianWoelki** [comment]
These extensions are currently not supported. Additionally, there are other issues that keep track of the status.
