### ISSUE TITLE
In-Line Icon Interferes with Clicking a Linked Note in Live-Preview

### ISSUE THREAD

**Issue by BaughBerry** [FlorianWoelki/obsidian-iconize#405]
**Describe the bug**
If I put an in-line icon right before a link to a note, I'm unable to click the link in live-preview. I can click the link in reading mode only. 

**To Reproduce**
1. Create an in-line icon like so, :TiBooks:
2. Add a linked note like so, :TiBooks: [[Library]]
3. In live-preview, attempt to click the link
4. The result: The link does not work and instead it opens the link for editing.

**Expected behavior**
I should be able to click the link in live-preview with an in-line icon

**Screenshots**
<img width="243" alt="Screenshot 2024-03-27 at 10 05 42 AM" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/129925078/aa910bca-97dd-4f58-b879-f08b4d5922fe">

**Comment by FlorianWoelki** [comment]
so I think this is the default behaviour of Obsidian right? for me, when I try to edit the line and edit some text after the link I can always click on the link. but I cannot click the link when I am editing the link (only with ctrl + click)
