### ISSUE TITLE
Missing icons in simple-icons pack

### ISSUE THREAD

**Issue by k1r8r0wn** [FlorianWoelki/obsidian-iconize#406]
**Describe the bug**
Missing icons in simple-icons pack. 

I've created the custom one with another name (simpleicons) - all works fine, with the same name - got 0 imported too. 

Deactivating the plugin or deleting doesn't help. Other packs work like a charm.

**To Reproduce**
1. Go to 'Iconize -> Browse icon pack'
2. Select simple-icons
3. See that total icons count equals 0

**Expected behavior**
Should work like other packs

**Screenshots**
<img width="172" alt="Снимок экрана 2024-03-28 в 13 22 56" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/8123661/35ab7c56-81ef-4d5c-b3da-232cdfc08a5d">
<img width="232" alt="Снимок экрана 2024-03-28 в 13 25 32" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/8123661/3a9126d0-6d2b-4c70-b40e-e9c079afdf1f">

**Comment by FlorianWoelki** [comment]
This issue has been resolved in [v2.11.3](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.11.3).
