### ISSUE TITLE
Can't update to Iconize from 2.11.0 to 2.11.3 ?

### ISSUE THREAD

**Issue by I-Pch** [FlorianWoelki/obsidian-iconize#408]
**Describe the bug**
There's apparently a new version of Iconize (2.11.3) ... But when clicking on `Update` within the `Community Plugins` section of Obsidian's settings, I'm told: 
```
Failed to install plugin Iconize 
``` 

**To Reproduce**
1. In Obsidian's settings, under the `Options` section, go to `Community Plugin` and click on `Check for updates` in regards of `Current plugins`
2. Click on the same button now stating `Update all`  

Obsidian's updates the other plugins and then says that it `Failed to install plugin Iconize`

**Expected behavior**
Iconize should be updated 😄

**Comment by I-Pch** [comment]
Ah well... I guess it was resolved while I was reporting the issue 😆 !

Thank you 🙌

**Comment by FlorianWoelki** [comment]
Haha no worries. I think the issue was just with Obsidian and not the plugin.
