### ISSUE TITLE
Recursive Icon Inheritance

### ISSUE THREAD

**Issue by NicolaiSchmid** [FlorianWoelki/obsidian-iconize#410]
I want to suggest a configuration option to inherit icons recursively from parent folders

My vault is setup in a loose directory structure with links and tags in between. The main folders define broad topics and categories of my life (work, journal, books, ...) 

I like this extension because it adds a new dimension into my workflow, where I can visually distinguish what type of note i'm in, just based on the icon it has.

It would be really cool, I could now, set icons for one of the root directories and have all directories and downstream notes inherit that icon, unless it specifically overwrites it.

Is that something you would like to support as an option in this extension?

If yes, let's brainstorm some implementation ideas and I can get started on a prototype

**Comment by Vars-Ulrich** [comment]
Seconded

**Comment by FlorianWoelki** [comment]
thank you for the suggestion. maybe, [custom rules](https://florianwoelki.github.io/obsidian-iconize/files-and-folders/custom-rules.html) could be interesting for you? you can basically define a regex or the simple starting path of the folder and by that set an icon for all the children.

**Comment by NicolaiSchmid** [comment]
does that overwrite the icons I set manually on a child folder?

**Comment by FlorianWoelki** [comment]
> does that overwrite the icons I set manually on a child folder?

nope, the individually set icons are always prioritised.

**Comment by FlorianWoelki** [comment]
I'll close this one as it seems that it can be realised with custom rules.
