### ISSUE TITLE
WARN: Link element does not have a linkpath to a file.

### ISSUE THREAD

**Issue by merlinuwe** [FlorianWoelki/obsidian-iconize#416]
Thanks to your great plugin.

In the console of Windown 10 (with latest releases of Obsidian and your plugin) I see this:

![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/4138869/d6aaff30-8689-4b01-a23d-5f9c3bf4c57e)

What can I do to narrow the cause?

**Comment by FlorianWoelki** [comment]
generally, you can ignore the warning messages. these are just debugging messages, i've forgotten to turn them off or have some sort of toggle.

the errors are not coming from this plugin.
