### ISSUE TITLE
Feature Request: Backup/Export existing global rules to file

### ISSUE THREAD

**Issue by j-finger** [FlorianWoelki/obsidian-iconize#419]
## Feature Request: Backup/Export existing global rules to file

**Is your feature request related to a problem? Please describe.**
The inability to backup or transfer custom icon rules poses a risk of data loss when upgrading or switching devices.

**Describe the solution you'd like**
Implement a 'Backup/Export rules' option to save rules to a file from the plugin settings, enabling easy transfer and backup. This would obviously also require an import system.

**Describe alternatives you've considered**
None

**Additional context**
Suggested interface for rule export:
![Export Custom Icon Rules](https://github.com/FlorianWoelki/obsidian-iconize/assets/80647966/34cd5a5b-7060-4ebb-92b5-b901d485030c)

**Comment by FlorianWoelki** [comment]
i don't think that this will become reality because all of the custom rules are saved in the `data.json` file of the obsidian plugin itself. thus, there is a way to backup the custom rules.
