### ISSUE TITLE
[Bug] Frontmatter icons are only indexed when Iconize is active

### ISSUE THREAD

**Issue by rx-chris** [FlorianWoelki/obsidian-iconize#423]
**Describe the bug**
- I notice that frontmatter icons only works when you update them while Iconize plugin is active. If I were to uninstall and reinstall the plugin, the frontmatter icons is no longer remembered by Iconize even though the frontmatter icon property remains unchanged in the markdown.

**To Reproduce**
- Delete the `data.json` file or uninstall and reinstall Iconize.

**Expected behavior**
- Iconize should recognise the frontmatter icon property that already exists in the vault and should not break if I were to uninstall and reinstall Iconize.

**Proposed Solution**
- Include a setting or a command to scan all notes in the vault for the frontmatter icon property and indexed them properly into `data.json`.

**Comment by FlorianWoelki** [comment]
This has been now released in [v2.14.0](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.14.0).
