### ISSUE TITLE
Markdown characters get duplicated in source mode when Iconize is on

### ISSUE THREAD

**Issue by josephtribulat** [FlorianWoelki/obsidian-iconize#425]
Since the latest update, when Iconize is activated, all markdown special characters in my notes appear twice when I'm in source mode (except on the line where my cursor is).

<img width="483" alt="Capture d’écran 2024-04-07 à 15 42 51" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/128245994/c4270c22-5efe-4865-9a9c-8716d09d5ea4">

This only happens in my main vault though. I couldn't replicate the problem in the sandbox vault, even with the plugin configured exactly the same way as in my main vault. I couldn't find where the conflict could come from. I deactivated all CSS snippets in the main vault, switched to default theme and deactivated all other plugins, yet the problem remains.

**Comment by FlorianWoelki** [comment]
thanks for the bug report. i've created a [hotfix](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.11.7) for this issue!
