### ISSUE TITLE
Iconize breaks dataview

### ISSUE THREAD

**Issue by chrizzzlybear** [FlorianWoelki/obsidian-iconize#426]
**Describe the bug**
When Iconize is active dataview queries only show the "loading" message when included in a callout but will never load. Turn iconizit off and everything is fine. Turn it on and dataview is "blocked". Other option to make dataview work: leave iconize turned on and separate it from the callout.

**To Reproduce**
1. make a dataview query within a callout (like in IdeaversePro)
2. turn on iconize and watch the dataview queries fail
3. turn iconize off and see that everything works again
4. Optional: separate the query from the callout and see it working again

**Expected behavior**

**Screenshots**
![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/130693004/565dbd5f-79c3-4c09-a605-a93af0bce331)
![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/130693004/afb2895c-10f9-4fc7-811f-9a9c6b11a80e)

**Comment by FlorianWoelki** [comment]
i think this should be related to #424.
