### ISSUE TITLE
Latest update (2024-04-07) crashes several other plugins

### ISSUE THREAD

**Issue by Davve37** [FlorianWoelki/obsidian-iconize#427]
**Describe the bug**
Iconize disrupt a bunch of other plugins in Obsidian. 

**To Reproduce**
1. Have iconize on
2. Look at Dataview Table or Meta bind.
3. ???

**Expected behavior**

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://i.imgur.com/jcPIq7Y.png)

**Additional context**

**Comment by FlorianWoelki** [comment]
thanks for the bug report!

i think this might be related to #424 
having a simple data view (with e.g., `LIST`) works flawlessly with iconize (2.11.7). would it be possible to be a bit more exact on what query you use and how i can reproduce this issue.

**Comment by Davve37** [comment]
A list works on first compile, but if you leave the note and come back to it it has stopped rendered.

```dataview
LIST
LIMIT 100
```

https://i.imgur.com/loepAg2.png

Notes with Meta Bind code also doesn't work: https://i.imgur.com/Zxya84e.png

Also when you reload your vault it fails to retrieve the last note pages and all tabs show up as "new note": https://i.imgur.com/Yjq4JSg.png

**Comment by mitchmeister** [comment]
2.11.7 has seriously disrupted Obsidian. Spontaneously creates new blank tabs & Dataview rendering is poked.

**Comment by mitchmeister** [comment]
I have reverted to 15.  16 also produced issues with Dataview & Admonition plugins although didn't mess with my tabs.

**Comment by FlorianWoelki** [comment]
i am not able to reproduce the issue anymore in [v2.11.8](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.11.8).

**Comment by mitchmeister** [comment]
My dataview's now ok with 18 thanks but this dataviewjs rendering a single "row" over 2 lines

```dataviewjs
const {fieldModifier: f} = this.app.plugins.plugins["metadata-menu"].api;

dv.table([':LiAlertCircle:', ':LiClock:', 'Task', 'Project', ':LiTimer:'], 
await Promise.all(
dv.pages('"@tasks"') 

.where((t) => {return ( t.dodate <= dv.date('today') && t.dodate !== null && (t.when?.includes('thisWeek') || t.when?.includes('scheduled')) ) })

.sort(t => [t.hour, t.project, dv.date(t.dodate), t.name])

.map(async t => [
	await f(dv, t, "essential"), 
	await f(dv, t, "hour"), 
	t.file.link, 
	await f(dv, t, "project"), 
	await f(dv, t, "duration"),
	])

))
```

<img width="795" alt="SCR-20240408-qhft" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/6250875/33b5ed85-3254-4b6c-a9e2-ab01bf70971c">
