### ISSUE TITLE
Toggle icons while edition notes feature crashes the note on Obsidian v1.5.12 if there are icons in headings

### ISSUE THREAD

**Issue by AugustoPapagno** [FlorianWoelki/obsidian-iconize#428]
After updating Obsidian to v1.5.12 a few notes crashes with "ranges must be added" error message as fails to load. Also, if any of those notes is open, the _Iconize_ Menu on Obsidian's settings is not even listed

**To Reproduce**
1. Upgrade Obsidian to v1.5.12
2. Enable _Toggle icons while edition notes_ AND _Toggle icons in links_ feature on Iconize
3. Generate a new note with  `# Test with :SiObsidian:`
4. Restart Obsidian
5. The note will not open, and you will not be able to access iconize settings
6. select a different (working) note
7. Restart Obsidian
8. Disable  _Toggle icons while edition notes_
9. Note will work (with no icon)

**Expected behavior**
mmm... not to get a heart attack seeing on of my most used notes not acccessible anymore???

**Comment by FlorianWoelki** [comment]
this is fixed in [v2.11.9](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.11.9)
