### ISSUE TITLE
Two lonesome ##

### ISSUE THREAD

**Issue by merlinuwe** [FlorianWoelki/obsidian-iconize#429]
Today, I have seen two 

##

characters in my note, which I could not delete. They were found in such a code:

`````
```html

##
´´´´
`````

After deactivating your plugin and activiating again they seem to be dissapeared.

BTW: Had problems with templater plugin today, it showed me lots of ####### in headlines. Perhaps this has something to do with the update.

Only for your information, to keep an eye on it.

**Comment by FlorianWoelki** [comment]
this should be fixed in [v2.11.8](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.11.8).
