### ISSUE TITLE
Empty tab(s) open when opening a note while on a pinned tab

### ISSUE THREAD

**Issue by tlemotlemo** [FlorianWoelki/obsidian-iconize#430]
**Describe the bug**
While on a pinned tab, if I open a note (either through the files explorer or by opening a note in Graph View), along with a new tab containing the note, another unwanted tab is created containing nothing except for the "No file is open" screen.

**To Reproduce**
1. Pin a tab and then switch to it.
2. Using either the file explorer or graph view (if the graph view is in the pinned tab), open another note while still on the pinned tab.

**Expected behavior**
When opening a note while on a pinned tab, only one new tab containing the note should appear.

**Screenshots**
![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/42396926/2e8b83a6-973c-4b9e-9865-8410c7a15422)
![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/42396926/202097cd-d01b-4bf3-9c8b-f7dade660dc2)

**Additional context**
I am running Obsidian on Linux, with NixOS as my distro. Screenshots are from a vault I created to test this bug, and there are no other plugins other than the default Core plugins.

**Comment by Smitty010** [comment]
I am seeing the same problem on Windows.  This appears to be new in a release that I picked up 5 hours ago (2.11.7).  For me the creation of new tabs was serious enough that **I finally turned off iconize so I could work**.  I would bring up a workspace and there would be no markdown files.  The place where the markdown files should be would be blank tabs.  I also saw the following message
![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/3760075/c0984c86-e8e1-44c2-bc0f-b408febb49b4)
Whatever the change was a few hours ago seems to have caused serious problems.  I believe this all worked correctly yesterday.
