### ISSUE TITLE
Visual conflict between Iconize and Task plugin's todo tag

### ISSUE THREAD

**Issue by ArgensVentus** [FlorianWoelki/obsidian-iconize#431]
**Describe the bug**
Applying iconize with "toggle icons while editing notes" interferes with "Tasks" plugin's #task filter (common for those who use tasks plugin)

**To Reproduce**
1. Have "Tasks", "Checklist", and "Iconize" community plugins installed. Turn on "Toggle icons while editing notes".
2. Create a checkbox followed by a tag `- [ ] #todo` (commonly used as a Global task filter) while in editing mode
3. See result.

**Expected behavior**
Tag should remain visibly present. Error disappears if "Toggle icons while editing notes" is turned off, which suggests that iconize detects tags following checkboxes as icons? Error is also only present in live preview, and not editing mode.

**Screenshots**
![Screenshot 2024-04-07 171813](https://github.com/FlorianWoelki/obsidian-iconize/assets/84055930/b1a45581-1b81-4dda-b214-f5e3051c0996)
![Screenshot 2024-04-07 171758](https://github.com/FlorianWoelki/obsidian-iconize/assets/84055930/54bd6e71-a2da-42c2-9e77-eeef7df91b72)

**Additional information**
- Obsidian version: 1.5.12
- Checklist version: 2.2.13
- Tasks version: 6.2.0
- Iconize version: 2.11.7

**Comment by FlorianWoelki** [comment]
this might be fixed in [v2.11.9](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.11.9)
