### ISSUE TITLE
Broken Inline Dataview

### ISSUE THREAD

**Issue by kevinkickback** [FlorianWoelki/obsidian-iconize#432]
Using an icon, from an icon pack like fas, inside a callout breaks inline dataview. This does not happen with emojis. Changing the identifier for either iconize or dataview does not fix the problem. This issue is occurring in a fresh vault with no other plugins installed. 
Iconize version: 2.11.7

**To Reproduce**
1. Create callout
2. Add icon and inline dataview querry to the body of the callout.
3. In Live Preview/Reading Mode dataview renders as codeblock.

![screenshot](https://github.com/FlorianWoelki/obsidian-iconize/assets/12663557/15b3025a-e511-4dff-9928-bd0b6e5fe510)

**EDIT:**
It seems this issue also occurs outside of callouts. If there is not at least 1 empty line between the icon and the inline querry it breaks. I tried changing the identifiers and restarting obsidian but no luck.

**DOESN'T WORK:**

```
:FasCarOn:
`=this.testing`
```

```
:FasCarOn:
<br>
`=this.testing`
```

**WORKS:**

```
:FasCarOn:

`=this.testing`
```

**Comment by kevinkickback** [comment]
Well it seems this issue also occurs outside of callouts. If there is not at least 1 empty line between the icon and the inline querry it breaks. I tried changing the identifiers and restarting obsidian but no luck.

**DOESN'T WORK:**

```
:FasCarOn:
`=this.testing`
```

```
:FasCarOn:
<br>
`=this.testing`
```

WORKS:

```
:FasCarOn:

`=this.testing`
```

**Comment by FlorianWoelki** [comment]
hey, thanks for the detailed report. i am not able to reproduce this anymore in [v2.11.8](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.11.8)
