### ISSUE TITLE
Dataview queries distorted after updating to version 2.11.7

### ISSUE THREAD

**Issue by dml0sc** [FlorianWoelki/obsidian-iconize#434]
**Describe the bug**
After updating to version 2.11.7, all Dataview queries in my Vault appear distorted. This issue may be related to the concurrent use of the Metadata Menu plugin, which, like Iconize, utilizes icons within its interface. The distortion of Dataview queries was only resolved after uninstalling the Iconize plugin, which suggests a potential conflict between these plugins when used alongside the latest update.

**Screenshot with Iconize on**
<img width="752" alt="image" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/89693506/ec8f7992-0919-4a71-a0bc-0da942298e01">

**Screenshot with Iconize disabled**
<img width="750" alt="Screenshot of Obsidian at 8 Apr 2024 at 06_40_19" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/89693506/23bc18b9-e9d8-4849-97e4-59540953cf9c">

**Comment by gerardo** [comment]
https://github.com/FlorianWoelki/obsidian-iconize/issues/431

**Comment by jaycenhorton** [comment]
Potentially fixed by #433

**Comment by FlorianWoelki** [comment]
i've also pushed another fix. so this might be fixed in [v2.11.9](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.11.9). closing for now.

**Comment by dml0sc** [comment]
It is solved now in version 2.11.11 of Iconize
