### ISSUE TITLE
Iconize breaks Tasks plugin functionality as of version 2.11.7

### ISSUE THREAD

**Issue by gypsyav** [FlorianWoelki/obsidian-iconize#435]
**Describe the bug**
When Iconize is enabled  the Tasks plugin no longer works.  One non-task item is shown where there is a query, no CSS is applied even on the original task, and right clicking on the check box does not allow changing the status.

**To Reproduce**
1. Install and enable Tasks plugin
2. Create Tasks query or custom CSS for tasks
3. Verify queried tasks/custom styled tasks are showing properly and right clicking on checkbox brings up pop up with custom statuses
4. Install and enable Iconize plugin
5. See error: Queries/custom CSS no longer renders and nothing happens when right clicking task checkbox

**Expected behavior**
Plugin should work without breaking other plugins

**Comment by gerardo** [comment]
https://github.com/FlorianWoelki/obsidian-iconize/issues/434

**Comment by gypsyav** [comment]
> this might be fixed in [v2.11.9](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.11.9). closing for now.

This didn't work. The same thing is still happening.
![IconizesError](https://github.com/FlorianWoelki/obsidian-iconize/assets/26289654/e269e95f-22d9-4cd7-9c86-ff99e4711d22)
