### ISSUE TITLE
2.11.7 broken markdown codeblock process

### ISSUE THREAD

**Issue by quanru** [FlorianWoelki/obsidian-iconize#436]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
broken by:
![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/11739753/09c68340-f3e8-4490-8d44-9fc11ccd2c38)

**Additional context**

**Comment by FlorianWoelki** [comment]
this is fixed in [v2.11.9](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.11.9)
