### ISSUE TITLE
Keystrokes and clicks in pinned note open a new empty tab

### ISSUE THREAD

**Issue by FromScratchCommunications** [FlorianWoelki/obsidian-iconize#439]
**Describe the bug**
When I pin a note, each keystroke or click inside that note opens a new empty tab.

**To Reproduce**
1. Make sure Iconize is turned on
2. Pin any note
3. Click into the note or type

**Expected behavior**
I expect no empty tabs to open when typing or clicking in a pinned note.

**Comment by FlorianWoelki** [comment]
thanks for reporting this issue. unfortunately, I am not able to reproduce this one. I've pinned a note and I can type or switch between files without any issues.
