### ISSUE TITLE
iconize causes dataview unable to render

### ISSUE THREAD

**Issue by Ilaner2000** [FlorianWoelki/obsidian-iconize#441]
**Describe the bug**

Enabling the "iconize" plugin causes Dataview not to display the queried content properly.

**To Reproduce**
 By enabling and disabling the iconize plugin, you will see how Dataview behaves differently. 

**Expected behavior**
Enabling the iconize shall not affect how Dataview render the result

**Comment by FlorianWoelki** [comment]
closing because duplicate of #438
