### ISSUE TITLE
2.11.9 causes my dataviewjs query to "lose" an icon

### ISSUE THREAD

**Issue by mitchmeister** [FlorianWoelki/obsidian-iconize#443]
**Describe the bug**
2.11.9 causes my dataviewjs query to "lose" an icon

Should look like this (2.11.5 & previous)
<img width="785" alt="SCR-20240412-kpni" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/6250875/954ba218-758d-47e8-8289-99f4c234ec9e">

2.11.9 looks like this
<img width="782" alt="SCR-20240412-kori" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/6250875/3c0411c0-a7a9-461c-ac3e-f5fc8f63200d">

**To Reproduce**

```dataviewjs
const {fieldModifier: f} = this.app.plugins.plugins["metadata-menu"].api;

dv.table([':LiAlertCircle:', ':LiClock:', 'Task', 'Project', ':LiTimer:'], 
await Promise.all(
dv.pages('"@tasks"') 

.where((t) => {return ( t.dodate <= dv.date('today') && t.dodate !== null && (t.when?.includes('thisWeek') || t.when?.includes('scheduled')) ) })

.sort(t => [t.hour, t.project, dv.date(t.dodate), t.name])

.map(async t => [
	await f(dv, t, "essential"), 
	await f(dv, t, "hour"), 
	t.file.link, 
	await f(dv, t, "project"), 
	await f(dv, t, "duration"),
	])

))
```

**Comment by FlorianWoelki** [comment]
This is similar to #438.
