### ISSUE TITLE
Callouts with emoji fail to render dataview queries

### ISSUE THREAD

**Issue by ransurf** [FlorianWoelki/obsidian-iconize#444]
**Describe the bug**
Callouts with an emoji fail to render dataview queries

**To Reproduce**
1. Have a callout with emoji in the title or content
2. Have a dataview query also in the content
3. When viewing the callout, see that query is stuck in `Loading...`

**Expected behavior**
The query should be executed and loaded when the callout is in view mode

**Screenshots**
![Screenshot 2024-04-11 at 4 47 02 PM](https://github.com/FlorianWoelki/obsidian-iconize/assets/80801637/f7cc5328-6e5c-4e52-a045-f2dc23e04bb5)

**Additional context**
I updated from 2.10.1 to 2.11.9 and experienced this issue

**Comment by FlorianWoelki** [comment]
This is similar to #443.
