### ISSUE TITLE
Iconize causes abnormal display of inline code

### ISSUE THREAD

**Issue by YC-EChen** [FlorianWoelki/obsidian-iconize#447]
When I turn on the option "Visibility of icons - Toggle icons while editing notes"（I don‘t know the purpose of this option），the character * in the inline-code will become null（N-U-L-L，4 characters），and when I turn of this option，the problem disappears.

Obsidian Version: 1.5.12

**Comment by FlorianWoelki** [comment]
this might be related to #438.
