### ISSUE TITLE
Some emojis do not appear in live preview

### ISSUE THREAD

**Issue by lilyofthealley** [FlorianWoelki/obsidian-iconize#448]
Some emojis do not appear in live preview unless cursor is on the same line of the icon.

Reading mode:
![iconize_bug1](https://github.com/FlorianWoelki/obsidian-iconize/assets/132984387/933c3d9c-6ea1-47cd-83a4-934a44899178)

Live preview:
![iconize_bug2](https://github.com/FlorianWoelki/obsidian-iconize/assets/132984387/6a1752ee-c2bd-46dc-8748-041df3636024)

**Comment by FlorianWoelki** [comment]
This is related to #438
