### ISSUE TITLE
Bullets are not shown on lists using asterisks v2.11.10

### ISSUE THREAD

**Issue by mariomui** [FlorianWoelki/obsidian-iconize#450]
**Describe the bug**
Bullets do not appear when they begin with "*" (asterisk)

**To Reproduce**
1. Create note with a bullet list with asterisks
2. Restart Obsidian app
3. Go to previous note

**Expected behavior**
Bullets should be be next to the list item.

**Screenshots**

**Additional context**
2.11.5 is the last known version where there were no problems.

**Comment by FlorianWoelki** [comment]
thanks for reporting the issue. for me they are shown but not rendered correctly :D I'll fix it!

<img width="191" alt="image" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/20746070/d2eb48d5-6495-421b-94fb-c06488015fb6">

**Comment by FlorianWoelki** [comment]
this should be fixed. I'll make a new release tomorrow.

**Comment by mariomui** [comment]
https://github.com/SilentVoid13/Templater/blob/678d075cef894e014344e969c3db252f47b41c41/tests/main.test.ts#L32

I think you're gonna prolly have to do something like this soon.
I also write tests like you where i colocate it next to the code itself. It's sweet.

**Comment by claremacrae** [comment]
I'm not sure if you wanted to add a test case for this, but just to note, `+` is also a valid list marker:
https://daringfireball.net/projects/markdown/syntax#list

**Comment by FlorianWoelki** [comment]
> https://github.com/SilentVoid13/Templater/blob/678d075cef894e014344e969c3db252f47b41c41/tests/main.test.ts#L32
> 
> I think you're gonna prolly have to do something like this soon. I also write tests like you where i colocate it next to the code itself. It's sweet.

thanks I'll take a look!

> I'm not sure if you wanted to add a test case for this, but just to note, `+` is also a valid list marker: https://daringfireball.net/projects/markdown/syntax#list

thank you. I've added this as well

**Comment by FlorianWoelki** [comment]
this should be fixed with [v2.11.11](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.11.11).
