### ISSUE TITLE
2.11.10 Breaks Dataview

### ISSUE THREAD

**Issue by almays** [FlorianWoelki/obsidian-iconize#454]
**Describe the bug**
With Iconize 2.11.10 enabled — all pages with Dataview or DB Folder or any other pages with Dataview calls — hang Obsidian.
Downgrade to 2.11.9 fixes the problem.

**To Reproduce**
1. Install Dataview and Iconize
2. Make some Dataview calls on the page
3. Get Obsidian hanging

**Expected behavior**
Expected Obsidian does not hang

**Screenshots**
<img width="545" alt="Снимок экрана 2024-04-13 в 18 05 44" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/19815/1dc78713-6126-4a48-a93e-f983929179a6">

**Comment by FlorianWoelki** [comment]
hey thanks for reporting! I need a little bit of information about your vault. do you have some minimal reproduction example? at the moment (for me), DataView works fine with Iconize.

**Comment by FlorianWoelki** [comment]
should be fixed in the latest version. i'll also create a new version tomorrow which fixes a lot of things.
