### ISSUE TITLE
Icons randomly replaced with icon file name

### ISSUE THREAD

**Issue by sicahjes** [FlorianWoelki/obsidian-iconize#455]
**Describe the bug**
Sometimes, an icon will stop displaying in file explorer (noting this is the only place I use Iconize) and instead display the name of the icon file. This can only be fixed if the icon is replaced by a different icon and then swapped back after.

**To Reproduce**
This is random, now way to reproduce as cause is uncertain.

**Expected behavior**
Icons to display, not icon file name. 

**Screenshots**

![Screenshot 2024-04-14 at 11 12 43](https://github.com/FlorianWoelki/obsidian-iconize/assets/28281659/c7b605e7-b07a-4cec-92de-9f7caa847f57)

**Comment by FlorianWoelki** [comment]
this is most likely fixed with [v2.11.12](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.11.12)
