### ISSUE TITLE
Obsidian hangs with plugin enabled

### ISSUE THREAD

**Issue by Razilator** [FlorianWoelki/obsidian-iconize#461]
**Describe the bug**
My obsidian freezes with your plugin, only when you turn it on. Let's say I go to look at CANVAS and my application freezes in such a way that the contents of the file are not shown.
Even if I leave one of your plugins, it still freezes :c

**Screenshots**
![Screenshot_1](https://github.com/FlorianWoelki/obsidian-iconize/assets/60067317/0798478c-351d-4566-8efb-834e63cf2283)
![Screenshot_2](https://github.com/FlorianWoelki/obsidian-iconize/assets/60067317/b03ddf6d-0456-4727-8984-b326e2eb48e7)
![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/60067317/35707e53-7c39-4564-8126-50d9815fd57c)

Video recording of the problem: https://drive.google.com/file/d/10QuWbtKL860IxhqY9kg-h-np4INDZbLk/view?usp=sharing

**Comment by FlorianWoelki** [comment]
this seems related to #457
