### ISSUE TITLE
Iconize crashes when used with Dataview

### ISSUE THREAD

**Issue by pag00** [FlorianWoelki/obsidian-iconize#463]
**Describe the bug**
This only occurs if iconize is enabled, therefor i assume it to be at fault.
I use [Dataview](https://github.com/blacksmithgu/obsidian-dataview) and other plugins that rely on it, in particular [Dataloom](https://github.com/trey-wallis/obsidian-dataloom) and [Annotator](https://github.com/elias-sundqvist/obsidian-annotator). When one of these plugins handles a certain string (i.e. a cell containing it is loaded in a data loom, or a annotator cell containing it is saved), Obsidian freezes. Restarting it restores the state before the last action.

_This occurs for any string that contains both numbers and letters._

for example:
abc123
matlab2023a
This sentence contains 4 words.

**To Reproduce**
1. Install Iconize, Dataview, Annotator
2. [Open any PDF in Annotator](https://github.com/elias-sundqvist/obsidian-annotator?tab=readme-ov-file#getting-started)
3. create a new annotation (mark some text and click on the note icon)
4. write one of the examples and save
5. Obsidian freezes

**Expected behavior**
Obsidian does not freeze, handles the string the way it does without Iconize enabled

**Additional context**
from Obsidian [debug info command](https://help.obsidian.md/Help+and+support#Collect+debug+information):

```
SYSTEM INFO:
	Obsidian version: v1.5.12
	Installer version: v1.5.8
	Operating system: Darwin Kernel Version 23.2.0: Wed Nov 15 21:54:10 PST 2023; root:xnu-10002.61.3~2/RELEASE_X86_64 23.2.0
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 13
	Plugins enabled: 4
		1: Annotator v0.2.11
		2: Dataview v0.5.66
		3: DataLoom v8.15.12
		4: Iconize v2.11.11

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

**Comment by FlorianWoelki** [comment]
please update to the latest version of Iconize which is version 2.11.12. I am honestly not sure why Obsidian did not recognise the update, yet. I'll raise something in their Discord.
