### ISSUE TITLE
Developer Tools Shortcut Disabled

### ISSUE THREAD

**Issue by kevinkickback** [FlorianWoelki/obsidian-iconize#469]
**Describe the bug**
ctrl + shift + i no longer opens developer tools if iconize was enabled when obsidian was started.
plugin version: 2.11.13
obsidian version: 1.5.12

**To Reproduce**
1. Enable Iconize
2. Close Obsidian
3. Open Obsidian
4.  ctrl + shift + i no longer works

**Expected behavior**
developer tools shortcut should work regardless of iconize status.

**Additional context**
Interestingly disabling OR enabling ANY plugin fixes the issue and restores the shortcut.

**Comment by FlorianWoelki** [comment]
yeah, this seems to be due to the latest addition of the shortcut for setting the icon of a file/folder. I'll add further customisation options to this shortcut. or do you have any specific shortcut idea that I could use for that?

**Comment by kevinkickback** [comment]
Nothing specific comes to mind. Anything will do for me personally as long as the default dev tools shortcut is available. Thanks for all your hard work on this great plugin.

**Comment by FlorianWoelki** [comment]
> Nothing specific comes to mind. Anything will do for me personally as long as the default dev tools shortcut is available. Thanks for all your hard work on this great plugin.

thank you! I'll try to come up with a different shortcut that is not occupied.

**Comment by FlorianWoelki** [comment]
because I am not on a windows machine, would Ctrl + Shift + J work for you?

**Comment by kevinkickback** [comment]
Yes, as far as I am away that does not conflict with any other shortcuts. To be honest if I had known initially a simple hotkey change would fix the issue I probably wouldn't have bothered you with it hah. Thanks again!

**Comment by ObsidianTTRPGProject** [comment]
Came here to ask, please stop trying to use Ctrl Shift I. 
This needs to be kept for the console and really confuses people when trying to give them assistance troubleshooting other plugins as they can't open the console.

**Comment by FlorianWoelki** [comment]
this should be now resolved in [v2.11.14](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.11.14).
