### ISSUE TITLE
Icons do not apply to all files within a folder

### ISSUE THREAD

**Issue by Kristof-h** [FlorianWoelki/obsidian-iconize#473]
I use the "default" regex rule to iconise all files within a folder : MyFolder\/[\w\d\s]+\.(?:\w+\.)*\w+

For some files the icon applies well but for some other file it doesn't work and no icon appears.
I removed all icons that were manually set before i set the rule but for some reason the ruled icon doesn't seem to apply to some files.
When i create a "new note" from scratch within the folder, the rule applies correctly to this new created file.

Is there something to "reset" so that the rule can be "forced" to properly apply to all file within a folder ?

Thank you for any advice on this !

**Comment by FlorianWoelki** [comment]
thank you for reporting this issue. could you tell me how many files are in your folder where you try to use the custom rule?

**Comment by Kristof-h** [comment]
They are around 45 files in this folder.

Another interesting point : when "toggle icon in tabs" is on you can see on the example below that a blue/green cloud icon appears when the rule applies correctly but for files where the rule doesn't apply correctly there is no icon on the left and a default file icon in the tab.
Maybe this helps.
Thanks.

<img width="918" alt="icon-issue" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/168074434/f1cf2cb1-cb85-41e2-9d77-88e2870b94c0">

**Comment by Kristof-h** [comment]
Could this problem be linked to the usage of French accents ?
"é" "è" "ê" for example ?

**Comment by FlorianWoelki** [comment]
> Problem solved with new regex : Folder/[\w\d\s\é\è\ê\à-]+.(?:\w+.)*\w+ Thank you !

Nice to hear that!
