### ISSUE TITLE
Freezing on "Loading Workspace" - v2.11.13

### ISSUE THREAD

**Issue by wdeb** [FlorianWoelki/obsidian-iconize#474]
**Describe the bug**
Since the latest update, Obsidian get's stuck on "Loading workspace" when Iconize is disabled.
If tried to update it to the latest version as well reinstall the plug-in, but it keeps freezing.

**Expected behavior**
That it works?

**Comment by FlorianWoelki** [comment]
thanks for reporting. it would be nice to get some details of your workspace. is it just iconize or is it a combination with another plugin? is there a specific file/note that affects the loading issue?

**Comment by rk-kontur** [comment]
I am using a lot of plugins but after a long time managed to pinpoint the crashes to Iconize.
When you give me a mailaddress, I can send you a copy of the file that makes Obsidian crash.

**Comment by FlorianWoelki** [comment]
> I am using a lot of plugins but after a long time managed to pinpoint the crashes to Iconize.
> 
> When you give me a mailaddress, I can send you a copy of the file that makes Obsidian crash.

I think it would be really nice if you could just paste the contents as a comment (you don't have to use the real text).

**Comment by rk-kontur** [comment]
The markdown file is 1.1 MB. It is certainly too long to paste

**Comment by FlorianWoelki** [comment]
> The markdown file is 1.1 MB. It is certainly too long to paste
> 
> 

maybe you can upload it somewhere? like in google drive?

**Comment by rk-kontur** [comment]
Sent by mail

**Comment by FlorianWoelki** [comment]
Going to close this issue because it seems to be fixed.
