### ISSUE TITLE
Icons next to internal links file names in two consecutive lines aren't displayed properly

### ISSUE THREAD

**Issue by Rexus752** [FlorianWoelki/obsidian-iconize#475]
In the latest version, if you put an internal link to a file with an icon applied to it, then the icon is displayed next to the file name, like this:

![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/32108270/80b8fb2d-c36a-45d7-ab87-2934720dc4ea)
(this is how it's seen in editing mode)

![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/32108270/b01dde43-d3c8-43a9-acea-3694bd4e7da9)
(this is in reading mode)

However, if you put two internal links in two consecutive lines, like this:

![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/32108270/da9a7e63-9ce3-47c9-9226-bc9daa26da3e)

In reading mode it's displayed only the icon of the first link:

![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/32108270/cebe61b3-176d-4609-8469-8ffba11d7f62)

And if you put an empty line between them:

![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/32108270/e4e6866b-11fe-43d0-8242-00818e82e7bc)

Then both the icons are shown:

![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/32108270/6bd48053-1e31-44f8-ac4a-60d9b5a01788)

**Comment by FlorianWoelki** [comment]
thank you for reporting. I am unfortunately not able to reproduce this issue. for me, all the links with an icon are rendered correctly.

**Comment by Rexus752** [comment]
Well, now I have updated all my plugins (including Iconize) and it seems to work correctly. Thanks anyway!

**Comment by FlorianWoelki** [comment]
> Well, now I have updated all my plugins (including Iconize) and it seems to work correctly. Thanks anyway!

that's awesome!
