### ISSUE TITLE
Please stop using Ctrl Shift I - this is required to open the Console and important for troubleshooting

### ISSUE THREAD

**Issue by ObsidianTTRPGProject** [FlorianWoelki/obsidian-iconize#487]
**Describe the bug**
This shortcut needs to be kept clear. There are thousands of people offering help to others every day and the simple task of asking someone to give them a console error is being made more difficult by you taking over the use of this shortcut. 

**Expected behavior**
Ctrl Shift I should open the Console. 

**Screenshots**
![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/96321415/9f9c9d04-49e8-469e-8a62-bdd65dd9b2dc)

**Comment by FlorianWoelki** [comment]
Did you update to the latest version? Iconize does not use Ctrl + Shift + I anymore.
