### ISSUE TITLE
Callout Title / Content: Icon's Misalignment when an Icon is present in a Link (v2.12.0)

### ISSUE THREAD

**Issue by Rivol0gY** [FlorianWoelki/obsidian-iconize#488]
**Describe the bug**
Within a callout's title or a callout's content, a link with an icon is shifted roughly by a half to the bottom while it is perfectly align in the body's text for example/

**To Reproduce**
1. Create a callout (for example > [!faq])
2. Add a link towards a note that has an icon embedded by Iconize
3. And the bug is appearing whatever the view mode used: "Live preview" / "Reading"

**Expected behavior**
Having the same alignment of the icon either in the body of a note or in a callout.

**Screenshots**
![Iconize](https://github.com/FlorianWoelki/obsidian-iconize/assets/169937755/1322f5e5-000d-4178-9cc5-3bf4863fa85d)

**HW / Versions used**
Device type: PC
OS: Windows 11
Obsidian Version: 1.5.12
Obsidian Installer Version: 1.5.12
Iconize version: 2.12.0

**Comment by FlorianWoelki** [comment]
This issue should be resolved with [v2.12.1](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.12.1).

**Comment by Rivol0gY** [comment]
Thank you very much. It works perfectly now!

Have a nice day!

**Comment by FlorianWoelki** [comment]
> Thank you very much. It works perfectly now!
> 
> Have a nice day!

Thank you, you too! :)
