### ISSUE TITLE
Long noteName pushes icon up above inline title

### ISSUE THREAD

**Issue by Aeases** [FlorianWoelki/obsidian-iconize#491]
**Describe the bug**
The inline title, when long, pushes the inline icon up above the title instead of putting it next to the title.
**To Reproduce**
1. set an icon on a note (i did it via `icon:` frontmatter
2. make the note title long
3. ***observe***

**Expected behavior**
Icon should push the text, not the other way arond
**Screenshots**
![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/96164686/2b26d36b-b9b7-4a54-a171-5f1e767dac0b)

**Additional Context**
I am using the minimal theme, i don't know if this effects it.

**Comment by FlorianWoelki** [comment]
This issue should be resolved with [v2.12.1](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.12.1).
