### ISSUE TITLE
How can I sync the icons I set up across all platforms?

### ISSUE THREAD

**Issue by youarenever** [FlorianWoelki/obsidian-iconize#496]
Thank you for your great plugin.

I use the remote save  plugin to sync between PC and mobile, but I have disabled the plugin sync function, so the contents of the .obsidian folder will not be synced.

I found that the icons I set up are stored in the data.json file in the plugin directory. 

So, how can I sync them across all platforms? 

Is it possible to set the configuration files to a custom directory?

**Comment by FlorianWoelki** [comment]
Thank you for your question. Maybe [this answer](https://florianwoelki.github.io/obsidian-iconize/guide/syncing.html#background-checker) here helps?
