### ISSUE TITLE
Feature request: Custom icon that only applies to either folders or icons.

### ISSUE THREAD

**Issue by michael-JJ** [FlorianWoelki/obsidian-iconize#497]
**Is your feature request related to a problem? Please describe.**
I'm trying to set a custom icon for folders.
For example, I want to set 📂 as the default icon for all folder, but not for files.

**Describe the solution you'd like**
Ability to create a custom icon rule that only applies to either folders or icons.
Maybe something like this?

![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/36151123/7ebf2343-8d4a-49a5-a5c6-26730a1a6484)

**Describe alternatives you've considered**
I've been using custom CSS snippets to add default icons to folders and files.

**Additional context**
/

**Comment by michael-JJ** [comment]
Nevermind, got it to work with:

![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/36151123/e29ca659-49a9-4fce-93cc-c163155d5c4a)

**Comment by pping** [comment]
> Nevermind, got it to work with:没关系，它可以使用：
> 
> `.+\.md` match everything that ends in `.md``.+\.md` 匹配以 `.md` 结尾的所有内容 `^((?!\.).)*$` match everything without a dot`^（（？！ \.).) *$` 匹配所有不带点的内容
> 
> ![image](https://private-user-images.githubusercontent.com/36151123/335762740-76d453cb-aee9-4b1b-96c3-9812e2fcb60b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY3Nzc0NzEsIm5iZiI6MTczNjc3NzE3MSwicGF0aCI6Ii8zNjE1MTEyMy8zMzU3NjI3NDAtNzZkNDUzY2ItYWVlOS00YjFiLTk2YzMtOTgxMmUyZmNiNjBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTEzVDE0MDYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxNGQ1M2U2NjEyYzdkMzBhZTE0N2MyNmY5MDFmODdlOGEyYTA5OTNmZDk0MzEwZDk0NDNlYjJjNjE1NjdlODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.O9d6bkTr5oYlD-dmr37RCqjkt-dD88AKU0y2Wwugn_I)

Very useful, this should be added to the documentation
