### ISSUE TITLE
Icon font size didn't effect to custom color icon

### ISSUE THREAD

**Issue by l2eused** [FlorianWoelki/obsidian-iconize#498]
**Describe the bug**
when I try to increase/decrease icon size in settings, it doesn't applies new size to my icon that have custom color.

**To Reproduce**
1. add any icon to files/folders
2. change color by right-click >> change icon color
3. set new color for specific icon in 2.
4. go to settings >> iconize plugin settings >> icon font size (in pixels)
5. increase/decrease value by sliding bar(?)

**Expected behavior**
it should applies new size to all icon even if it custom color or not

**Screenshots**
dump note icon is default color (untouch icon)
free note icon is custom color
![Obsidian_2pvUH0FV50](https://github.com/FlorianWoelki/obsidian-iconize/assets/94383254/5976e50c-a835-4f21-be1d-ada739414db1)

**Comment by FlorianWoelki** [comment]
This issue should be resolved with [v2.12.1](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.12.1).
