### ISSUE TITLE
Icons are too big in headings with ITS Theme

### ISSUE THREAD

**Issue by honggaruy** [FlorianWoelki/obsidian-iconize#500]
## **Describe the bug**

> There is an incompatibility between "ITS Theme" and "Iconize".
If I installed "iconize" and "ITS Theme" at the same time and added an icon in heading, it becomes very big.
I made a clean vault and installed only "ITS Theme" and "iconize"
I guess #316 is a similar problem.

> ITS Theme github : https://github.com/SlRvb/Obsidian--ITS-Theme

## **To Reproduce**

> 1. Make Clean Vault
> 2. Install and activate "ITS Theme" and "Iconize"
> 3. Add an icon in heading
> 4. Icon becomes very big

## **Expected behavior**

> Icons size in heading should be same both in default and ITS Theme

## **Screenshots**

>I added an mp4 video which describes how to reproduce error.

https://github.com/FlorianWoelki/obsidian-iconize/assets/24635919/0dc98595-0eb8-4bad-9472-ed255adcbb96

## **Additional context**

> If you change the theme, the icon size is not changed right after.  You need to select another icon name to see the final size of the icon as soon as possible.

**Comment by FlorianWoelki** [comment]
This issue has been resolved since [v2.13.0](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.13.0).
