### ISSUE TITLE
FR: clear unused icons to get more space

### ISSUE THREAD

**Issue by l2eused** [FlorianWoelki/obsidian-iconize#506]
**Is your feature request related to a problem? Please describe.**
yes, more icon files (svg) more storage consume

**Describe the solution you'd like**
allow option in plugin settings to delete unused icon files in icon folder

**Comment by FlorianWoelki** [comment]
This is already implemented. You can use the [background checker](https://florianwoelki.github.io/obsidian-iconize/guide/syncing.html#background-checker) for that.
