### ISSUE TITLE
Latest update broke all icon rendering

### ISSUE THREAD

**Issue by tjg23** [FlorianWoelki/obsidian-iconize#509]
## Description
After v2.14.0 the plugin fails to fetch or render all icons. Icons are completely missing from the file explorer. The suggester to add an icon to a file or folder shows no options, so is unusable. I cannot open any notes that contain icon shortcodes in the text. All of these issues throw the same error: `TypeError: undefined is not an object (evaluating 'icon.prefix')`

## Troubleshooting
All of my rules and set icons are still visible in the settings page and in `data.json`. Context menus in the file explorer still include the options 'Change color of icon' and 'Remove icon'.
The only icon pack I had installed was Lucide, so I suspect the new 'native support' for Lucide is related to the problem. Installing additional icon packs does not solve it – I am similarly unable to add those new icons to any file or folder.
A fresh install of the plugin in a new vault does not reproduce the error, but disabling and reenabling the plugin in the same vault has no effect.

### Expected behavior
The plugin would be able to automatically transition from using the .zip Lucide icon pack to using the native Lucide icon pack. Failing that, I would hope to be able to reset my icons or redownload the Lucide .zip from the plugin's settings.

### Screenshots
![IMG_0511](https://github.com/FlorianWoelki/obsidian-iconize/assets/115123240/4ee23cbc-780d-4dce-bcca-73897b31908f)
The icon suggester

![IMG_0509](https://github.com/FlorianWoelki/obsidian-iconize/assets/115123240/35f4628d-9ba8-4808-b087-8897b623d0ab)
One of the errors in the console

### Additional context
I encountered the issue on my iPad and haven't yet tested if the behavior is any different on my desktop

**Comment by FlorianWoelki** [comment]
Hey, thank you for your report, and sorry to hear that you have problems with the latest version.

Unfortunately, I am not able to reproduce this issue. It should migrate to the native Lucide icons without any trouble. What specific icons did you use? The only problem that I can think of is that you've used Lucide icons that do not exist in Obsidian Lucide.
Maybe you can also share the plugin's `data.json` file (anonymized)?

**Comment by nyssance** [comment]
Obsidian lucide icons is not complete, I don't think change to native is a good idea for old users. my obsidian is broken, some page can not been open.

**Comment by FlorianWoelki** [comment]
> Obsidian lucide icons is not complete, I don't think change to native is a good idea for old users. my obsidian is broken, some page can not been open.

Yes, I'll keep the native Lucide icons for now. I'll try to add a fix which doesn't break any existing pages with non existing icons for Lucide.

**Comment by FlorianWoelki** [comment]
I've released a [new version](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.14.1) which should fix the issue. It now ignores non-existing icons, so things can look a bit weird. I recommend replacing the icons, if possible. Sorry for the inconvenience.

**Comment by nyssance** [comment]
But I need some beautiful lucide new icons, obsidian's lucide icons version is too old, In the foreseeable next six months or one year, they will not to be updated.
So I choose use BRAT and frozen to 2.13 😂.

**Comment by FlorianWoelki** [comment]
> But I need some beautiful lucide new icons, obsidian's lucide icons version is too old, In the foreseeable next six months or one year, they will not to be updated.
> 
> So I choose use BRAT and frozen to 2.13 😂.

Sorry again :( 
That's also a way to do it :D

**Comment by nyssance** [comment]
> > But I need some beautiful lucide new icons, obsidian's lucide icons version is too old, In the foreseeable next six months or one year, they will not to be updated.
> > So I choose use BRAT and frozen to 2.13 😂.
> 
> Sorry again :( That's also a way to do it :D

I install more than 80+ plugins, obsidian iconize is one of my favorite. Thank you very much.

**Comment by FlorianWoelki** [comment]
> > > But I need some beautiful lucide new icons, obsidian's lucide icons version is too old, In the foreseeable next six months or one year, they will not to be updated.
> 
> > > So I choose use BRAT and frozen to 2.13 😂.
> 
> > 
> 
> > Sorry again :( That's also a way to do it :D
> 
> 
> 
> I install more than 80+ plugins, obsidian iconize is one of my favorite. Thank you very much.

That is really lovely to hear! Feel free to always reach out if you have any feedback :) it's unfortunate with Lucide though :p

**Comment by tjg23** [comment]
I must say I’m very disappointed with this response. I didn’t fully grasp the meaning of native Lucide support before, but that doesn’t work for me at all. Obsidian’s version of the Lucide package is already nine months and over 100 releases behind and we have no idea when it will be updated. It is missing hundreds of icons from the current library. Rolling back to that version is not feasible when I’ve been using the newer version for months.
I installed BRAT in order to revert to 2.13, but setting that up while trying to save my `data.json` was tedious, and still some of the issues returned today – I’m not sure how. I’ve been a big fan of this plugin but I fear I’m being forced to remove it. To be quite frank I think imposing this change was an irresponsible mistake

**Comment by nyssance** [comment]
> I must say I’m very disappointed with this response. I didn’t fully grasp the meaning of native Lucide support before, but that doesn’t work for me at all. Obsidian’s version of the Lucide package is already nine months and over 100 releases behind and we have no idea when it will be updated. It is missing hundreds of icons from the current library. Rolling back to that version is not feasible when I’ve been using the newer version for months. I installed BRAT in order to revert to 2.13, but setting that up while trying to save my `data.json` was tedious, and still some of the issues returned today – I’m not sure how. I’ve been a big fan of this plugin but I fear I’m being forced to remove it. To be quite frank I think imposing this change was an irresponsible mistake

2.13 work well for me. my steps is First, don't uninstall current version of iconize, it's will delete all settings. Second, install 2.13 with BRAT. Third, remove lucide pack and add it again in settings.

**Comment by FlorianWoelki** [comment]
> I must say I’m very disappointed with this response. I didn’t fully grasp the meaning of native Lucide support before, but that doesn’t work for me at all. Obsidian’s version of the Lucide package is already nine months and over 100 releases behind and we have no idea when it will be updated. It is missing hundreds of icons from the current library. Rolling back to that version is not feasible when I’ve been using the newer version for months. I installed BRAT in order to revert to 2.13, but setting that up while trying to save my `data.json` was tedious, and still some of the issues returned today – I’m not sure how. I’ve been a big fan of this plugin but I fear I’m being forced to remove it. To be quite frank I think imposing this change was an irresponsible mistake

I see where you are coming from. Do you generally know how many icons are missing in the native Lucide support?
I am currently thinking of just having an option where you can either use the native supported Lucide icons or download the original icon pack. What do you think of that?

**Comment by tjg23** [comment]
Thank you. I was able to get 2.13 working with BRAT – it turns out the issues I thought had reappeared were from a different plugin, they just looked coincidentally similar. In the future, restoring the option to download the full icon pack would be perfect, and I would greatly appreciate it. Thanks for your consideration

**Comment by FlorianWoelki** [comment]
> Thank you. I was able to get 2.13 working with BRAT – it turns out the issues I thought had reappeared were from a different plugin, they just looked coincidentally similar. In the future, restoring the option to download the full icon pack would be perfect, and I would greatly appreciate it. Thanks for your consideration

Awesome. I'll keep track of it at #520.
