### ISSUE TITLE
Freeze upon switching to reading mode when certain unicode characters appear in hyperlink text 

### ISSUE THREAD

**Issue by LordofDorknes** [FlorianWoelki/obsidian-iconize#510]
**Describe the bug**
When certain Unicode characters such as  `™` (U+2122 : TRADE MARK SIGN) or `®` (U+00AE : REGISTERED SIGN) are included in hyperlink text in the current window, switching that window to reading mode will freeze obsidian. This does not occur if the iconize plugin is disabled.

**To Reproduce**
1. Create a hyperlink in an empty obsidian document using the ™ character such as:
 ` [Just Do It™](https://en.wikipedia.org/wiki/Just_Do_It)`
2. Switch to reading view in the current window using the book button on the top right of obsidian.

**Expected behavior**
The document should switch to reading view normally.

**Additional context**
Tested with version 2.14.1

There are almost certainly other special characters not listed here that cause this, but some characters you might expect to exhibit similar behavior such as `℠` (U+2120 : SERVICE MARK) do not cause the issue.

The only icon pack loaded was "lucide-icons (Li)." I do not believe it has any icons that relate to the Unicode characters I have tested.

**Comment by FlorianWoelki** [comment]
Hey there, I cannot reproduce this issue :( For me, it works without any issues.
