### ISSUE TITLE
Li icons seem bigger than other in link

### ISSUE THREAD

**Issue by l2eused** [FlorianWoelki/obsidian-iconize#511]
**Describe the bug**
when using Li icons pack and open show icon in link, it doesn't match size to others (16px and 24px)

**To Reproduce**
to reproduce the behavior:
- turn on icon in link
- set icon from Li (and other pack for test)
- add 2 link that has icon

**Expected behavior**
It should same size as others.

**Screenshots**
the middle one is LiSquareKanban and others aren't from Li icons pack.
![Obsidian_UBnKbpgTgY](https://github.com/FlorianWoelki/obsidian-iconize/assets/94383254/4b781ed2-85c0-486a-80f2-8df7ff06de40)

**Additional context**
Found this bug in version 2.14.1 (and 2.14.0)
I think it just because css doesn't set size for them?

**Comment by FlorianWoelki** [comment]
This has been fixed in [v2.14.2](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.14.2).
