### ISSUE TITLE
Increase possible maximum icon size

### ISSUE THREAD

**Issue by FlorianWoelki** [FlorianWoelki/obsidian-iconize#514]
**Is your feature request related to a problem? Please describe.**

Increase the possible maximum icon size (from 24px to 48px or 64px).

**Comment by FlorianWoelki** [comment]
This has been released in [v2.14.2](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.14.2).

**Comment by Valombreuse** [comment]
Hi Florian,
Thanks for adjusting the max size to 64 px. However it doesn't work how I would like it to. You can indeed increase the size in the options but the icons displayed do not increase in size. Only the area is increased. To actually make it work you have to increase the Zoom level in Appearance. It would be cool to be able to increase the size of the icons without having to increase the zoom of the app.

![image](https://github.com/user-attachments/assets/ec949c85-c8af-4c29-bc85-3ff5423c10f3)
Desktop size : 3840 x 2160
Zoom level : 144%
Icon size : 64px
Extra margin top : -24
Extra margin Bottom : -24
Extra margin Right : 0
Extra margin Left: 0
---


![image](https://github.com/user-attachments/assets/66765172-e17d-40c4-9fd2-0c0608843169)
Desktop size : 3840 x 2160
Zoom level : 100%
Icon size : 64px
Extra margin top : -24
Extra margin Bottom : -24
Extra margin Right : 0
Extra margin Left: 0
---

![image](https://github.com/user-attachments/assets/edf66fff-948f-44c9-afcf-6c8bf68517be)

Desktop size : 3840 x 2160
Zoom level : 100%
Icon size : 64px
Extra margin top : 0
Extra margin Bottom : 0
Extra margin Right : 0
Extra margin Left: 0

**Comment by MilkyFake** [comment]
hey @Valombreuse!
Faced same problem... Since plugin is depreciated - did you somehow solved the problem? Maybe you know fork \ or have custom code edit for this problem?
Thanks
