### ISSUE TITLE
LiNotebookPen Icon was removed after updating to 2.14.2

### ISSUE THREAD

**Issue by AlgebraicFloat** [FlorianWoelki/obsidian-iconize#522]
LiNotebookPen was an lucide icon that looked like a notebook with a pen. It is now gone.

LiNotebookPen Icon was removed after updating to 2.14.2

</3

**Comment by FlorianWoelki** [comment]
Iconize switched to the native Lucide icon pack integration by Obsidian.

I am currently integrating a toggle which will switch between the original and native Lucide icon pack (#520)
