### ISSUE TITLE
i get 'lucide icons' pack that i can't delete

### ISSUE THREAD

**Issue by cheaderthecoder** [FlorianWoelki/obsidian-iconize#526]
**the issue**
after i updated the plugin i got the 'lucide icons' pack that i can't delete and is not in the icons folder like normal icon packs

**To Reproduce**
1. Go to 'settings'
3. Scroll down to 'iconize'
4. Scroll down to 'Icon packs'

**Expected behavior**
i should be able to delete the 'lucide icons' pack.

**Screenshots**
![Screenshot 2024-07-15 072917](https://github.com/user-attachments/assets/b7d555b8-bc83-478e-b12d-b8d12b817c14)

**Comment by FlorianWoelki** [comment]
This is expected behaviour because it contains all the native icons of Lucide that Obsidian supports.

**Comment by cheaderthecoder** [comment]
> This is expected behaviour because it contains all the native icons of Lucide that Obsidian supports.

how do i delete it?

**Comment by FlorianWoelki** [comment]
You can look at #527. I am currently implementing a functionality to delete it.
