### ISSUE TITLE
Add the possibility  to remove a predefined icon pack

### ISSUE THREAD

**Issue by Valombreuse** [FlorianWoelki/obsidian-iconize#527]
Hi Florian,

You can remove custom icon packs but not predefined ones. It would be cool to be able to as it pollutes the icon list. 
This is unneeded if you allows the selection of icon pack in the list.. I made a feature request for it.

**Comment by FlorianWoelki** [comment]
This issue has been resolved in the [latest release](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.14.3).

**Comment by Valombreuse** [comment]
Cool it works :) Now have the same for emoji and then have a possibility to select icon pack in the icon list ;)

**Comment by FlorianWoelki** [comment]
> Cool it works :) 
> 
> 
> 
> Thank you for your continual support 👍 
> 
> PogS
> 
> 

Awesome stuff. Sure thing! :)
