### ISSUE TITLE
Icons not showing on obsidian

### ISSUE THREAD

**Issue by CCcarols** [FlorianWoelki/obsidian-iconize#528]
HI! Hope you are doing well.

I've been using Iconize since months ago (2023) and this bug appears 
with some new updates to the plugin.

Now I can't see the icons on the tabs (where we see the name and the close option).

The icons also disappear on the files and notes (the left side).

I'm not sure how you can reproduce this error. Because it's just that the icons disappear.

I hope to see the icons to find my notes quickly.

I'm using a Samsung tablet, (I don't have and use any other device) minimal theme with some personalization. Im not using any CSS to modify my icons.

Im experiencing this since the last update of Iconize and it's a shame because I love how my vaults look with this plugin.

Have a great day, and I hope this can be fixed.

**Comment by FlorianWoelki** [comment]
It might be related to a [syncing problem](https://florianwoelki.github.io/obsidian-iconize/guide/syncing.html), when you use Obsidian Sync.

I highly recommend sticking to the native Lucide Iconpack (integrated in Iconize), which will work without any troubles with Obsidian Sync.
