### ISSUE TITLE
Icons conflict with codeblocks in callouts

### ISSUE THREAD

**Issue by Legofano** [FlorianWoelki/obsidian-iconize#543]
**Describe the bug**
If you have an icon in callout and write ``` to make a codeblock, then the icon won`t show.

**To Reproduce**
1. Type a callout.
2. Put an icon inside.
3. Include a codeblock anywhere.
4. See error.

**Expected behavior**
Show the icon.

**Screenshots**
![image](https://github.com/user-attachments/assets/27fee496-8928-4a36-a0fa-3613ba5c2da1)
![image](https://github.com/user-attachments/assets/cc5fbf91-8a26-4d6e-a5f4-4faeab7c47c7)
![image](https://github.com/user-attachments/assets/cee21536-88f7-4ba4-9539-6a211963e74f)
![image](https://github.com/user-attachments/assets/98d48d3b-9016-4fa7-8a91-c8ffa96bfca4)

**Comment by FlorianWoelki** [comment]
This issue has been resolved in [2.14.4](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.14.4).
