### ISSUE TITLE
Expose "Change icon" to obsidian command

### ISSUE THREAD

**Issue by danielwerg** [FlorianWoelki/obsidian-iconize#548]
**Is your feature request related to a problem? Please describe.**

To change icon of current note user would need 2 mouse clicks

**Describe the solution you'd like**

Instead "Change icon" could be assign to hotkey (I assume Obsidian API allows that)

**Describe alternatives you've considered**

Use the damn mouse

**Additional context**

![2024-08-12_07-17-32](https://github.com/user-attachments/assets/93d88c99-17ef-43cc-a43d-131f360f7098)

Related: https://github.com/FlorianWoelki/obsidian-iconize/discussions/547

**Comment by FlorianWoelki** [comment]
So there is a hotkey already available for setting an icon (you can see it [here](https://florianwoelki.github.io/obsidian-iconize/files-and-folders/icon-before-file-or-folder.html#icon-before-file-or-folder-name)). Additionally, there is also a command available which is called: "Set icon for file"

**Comment by danielwerg** [comment]
@FlorianWoelki Am I missing something?

![image](https://github.com/user-attachments/assets/f9cc234a-25d1-446b-b6d3-7b7f5ad5f2fb)

**Comment by FlorianWoelki** [comment]
You need to focus the file input
<img width="754" alt="image" src="https://github.com/user-attachments/assets/6ea0bb7f-8280-4cf4-a7da-5b2f109f8459">

**Comment by danielwerg** [comment]
Aaah, I was in "reading" view, that's why.
