### ISSUE TITLE
Improve the Icon Chooser window to eliminate or improve on the current display limit of 145 icons

### ISSUE THREAD

**Issue by jimbarrsc** [FlorianWoelki/obsidian-iconize#549]
**Is your feature request related to a problem? Please describe.**
There appears to be a hard limit of 145 displayed icons in the icon chooser window meaning you can't browse all available icons.

**Describe the solution you'd like**
When I right-click and select "Change Icon" on an item, a chooser window pops up. It displays the 5 recently used icons and a grid of 5 x 29 (145) available icons. Most of the available icon packs have more than 145 icons, so there appears to be no way to browse through all icons. I would like to be able to browse all available icons.

**Describe alternatives you've considered**
1. Increase the number from 145 to a more reasonable larger limit.
2. Remove the limit altogether. I realize that this could impact performance.
3. Provide an Option for the user to define the number of displayed icons. 
4. Provide a more comprehensive icon browser to view and select from all available icons.

**Comment by FlorianWoelki** [comment]
This issue is known and was decided based on performance.

I'll fix this issue and enhance the selection process of an icon with #346.
