### ISSUE TITLE
Feature: Don't display icon text unless cursor is next to it

### ISSUE THREAD

**Issue by LandonSchropp** [FlorianWoelki/obsidian-iconize#575]
**Is your feature request related to a problem? Please describe.**
Right now, when you click on a line with an icon on it, Iconize "unrenders" the icon, displaying the text. This can be a bit distracting.

Here's an example.

https://github.com/user-attachments/assets/bd7f875f-32ac-4734-a9f2-044ab60097ec

**Describe the solution you'd like**

Instead, it'd be great if Iconize only displayed the icon text when you're right next to it. This would match the behavior of other inline fields in Obsidian, like links or formatting.

https://github.com/user-attachments/assets/db35de59-00ba-4853-962b-0b9f777b7c43

**Describe alternatives you've considered**

This plugin works as-in now, but I think the UX of the solution I described is better.

**Additional context**

Thank you for creating this great plugin!

**Comment by FlorianWoelki** [comment]
This seems to be similar to #315

**Comment by LandonSchropp** [comment]
You're right. Sorry for the duplicate!
