### ISSUE TITLE
Can't paste colors (or anything) from clipboard on color picker

### ISSUE THREAD

**Issue by SametHope** [FlorianWoelki/obsidian-iconize#580]
**Describe the bug**
It is not possible to paste values or anything into color picker fields. When a string is pasted, it simply gets removed and leaves the input field empty. This forces the user to manually enter the HEX, RGB or HSL values which is incredibly inconvinient and inefficient.

**To Reproduce**
1. Copy a hexadecimal color value such as `#69db7c`.
2. Pick a existing folder with an lucide icon or create a new one and assign any icon to it.
3. Right click, select 'Change color of icon'.
4. Click into the color pick area.
5. Switch to HEX value view.
6. Try to paste the value.

**Expected behavior**
I expect to have the color value on my clipboard to have been entered into the color pickers value field when I paste it.

**Screenshots**
Not applicable.

**Additional context**
- I have created a new vault and only had this plugin enabled to make sure this is not caused by other plugins.
- I am using the latest stable version of the Obsidian.

**Comment by FlorianWoelki** [comment]
Thank you for reporting the issue. Unfortunately, Iconize tries to always use the native integrated components provided by Obsidian. Thus, the color picker component comes from Obsidian and it seems that I cannot change anything here at the moment.

**Comment by SametHope** [comment]
As a note, I went to Obsidian forums to create a bug report there but turns out this has been a known issue with the Chrome color picker for at least 4 years and unfortunately looks unlikely to be solved anytime soon.

**Comment by FlorianWoelki** [comment]
> As a note, I went to Obsidian forums to create a bug report there but turns out this has been a known issue with the Chrome color picker for at least 4 years and unfortunately looks unlikely to be solved anytime soon.
> 
> Edit: Just made a feature request post on Obsidian forum to replace the color picker: https://forum.obsidian.md/t/switch-from-chromiums-color-picker-to-a-custom-one-in-order-to-allow-copying-pasting-values/89924

Awesome! :)
