### ISSUE TITLE
Named links that have the same name as the current note which matches an icon rule displays the current note's icon, not the linked note

### ISSUE THREAD

**Issue by sadalsvvd** [FlorianWoelki/obsidian-iconize#581]
**Describe the bug**
If you are editing a note which has a given icon following the "Custom icon rules" setting, and link to another note in another folder which does not match that same custom icon rule setting, but whose link name is the same as the note currently being edited, that link will display the icon associated with the icon you're in. If there is another icon rule for the target note whose full path matches the custom icon rule, both icons show up.

I ran into this because I use matching daily notes between my personal folder and my work folder. For instance, I have notes following `Journals/YYYY/YYYY-MM-DD.md` naming convention as well as notes with `Work/<Company>/YYYY/YYYY-MM-DD.md`. The personal folder has an icon rule for `Journals/` and displays a 📝 icon. The work folder has an icon rule for `Work/` and displays a 💼 icon.

For instance, if I am in `Journals/2024/2024-10-15.md` and I add a link `[[Work/Company/2024/2024-10-15|2024-10-15]]`, it displays as `[[💼 Work/Company/2024/2024-10-15|📝 2024-10-15]]`. This only happens in edit mode and not preview mode, but I basically never use preview mode.

**To Reproduce**
1. Define a custom icon rule for one folder
2. Define a custom icon rule for a second folder
3. Create a note within the first folder with a name
4. Create a note in the second folder with the same name
5. Link to the second note from the first note, using a link name which is the same as the first note's

**Expected behavior**
Only the target link's icon rule should apply.

**Screenshots**

![image](https://github.com/user-attachments/assets/5f74f533-14b5-42aa-9721-82fed8541df0)
![image](https://github.com/user-attachments/assets/5f08f042-c0d2-4d5d-90c6-f8584be81117)

**Additional context**
Thanks for making a great plugin!

**Comment by sadalsvvd** [comment]
I'm not sure what happened or changed, but upon returning to my daily note the correct icon shows up, but it's now showing up redundantly twice:

![image](https://github.com/user-attachments/assets/67084b14-d2e4-4f35-a8f6-797a9ec71f25)

**Comment by FlorianWoelki** [comment]
I think this is related to #445. I'll close this issue for now.
