### ISSUE TITLE
Core plugins -> Bookmarks enabled ==> Iconize can not load, icons disappeared

### ISSUE THREAD

**Issue by cladic** [FlorianWoelki/obsidian-iconize#582]
**Describe the bug**
When I **enable** the option "Bookmarks" of Core plugins and "Iconize" have problems to work:
- Fail to load plugin
- Icons set on file menu disappear

"Bookmarks" of Core **disabled** ==>  "Iconize"  returns to work well...

Not in all of my Vaults !

Obsidian version: 1.7.4
Iconize version: 2.14.3

**To Reproduce**

**Expected behavior**
"Bookmarks" of Core plugins enabled and Iconize working without problems

**Screenshots**
...

**Additional context**
Suddenly some vaults start to show this problem, other not !

A example Vault is anexed ==> 
[Prob-Iconize.zip](https://github.com/user-attachments/files/17399598/Prob-Iconize.zip)

**Comment by FlorianWoelki** [comment]
Thank you for the report. This is an issue with compatibility with Obsidian >1.7 and a duplicate of #566.
