### ISSUE TITLE
Iconize plugin not loading, icons not displaying

### ISSUE THREAD

**Issue by boulhouech** [FlorianWoelki/obsidian-iconize#584]
Description:

I'm experiencing an issue with the Iconize plugin in Obsidian. The icons are not displaying correctly, and I'm receiving an error message that says "Failed to load plugin: Obsidian Plugin".

Steps to reproduce:

    Install the Iconize plugin in Obsidian
    Enable the plugin
    Attempt to use the plugin (e.g. add an icon to a note)

Expected behavior:

The plugin should load correctly and display icons as expected.

Actual behavior:

The plugin fails to load, and icons are not displayed. An error message is shown: "Failed to load plugin: Obsidian Plugin".

**Comment by NSHenry** [comment]
I've run into the same problem. Are you using the latest Obsidian release? 
I have a hunch it has something to do with this: https://docs.obsidian.md/Plugins/Guides/Understanding+deferred+views

**Comment by FlorianWoelki** [comment]
If you are using the latest version, see #566

**Comment by NSHenry** [comment]
Agreed, This is probably a duplicate. Disabling the Bookmarks in Core plugin seems to work. I only had two bookmarks in the vault that was causing problems, and the issue went away when I deleted them.
