### ISSUE TITLE
After upgrade obsidian to 1.7.4, Iconize can't start. 

### ISSUE THREAD

**Issue by Logovaz26** [FlorianWoelki/obsidian-iconize#587]
**Describe the bug**
After upgrade obsidian to 1.7.4, Iconize can't start. Error: filed to load plugin obsidian-icon-folder

**To Reproduce**
1. Switch off a plugin
2. Switch on a plugin
3. See error - filed to load plugin obsidian-icon-folder

**Expected behavior**
Plugin load's

**Screenshots**
![error](https://github.com/user-attachments/assets/79d266bb-f886-4ba8-baed-8b1a4d32bbdb)

**Comment by devnoot** [comment]
I'm seeing the same behavior. Have you happened to discover a fix?

**Comment by FlorianWoelki** [comment]
Yes #566 is related. I'll close this issue.
