### ISSUE TITLE
[BUG] Icons not loading in one device but is loading on the other

### ISSUE THREAD

**Issue by CatapultTV** [FlorianWoelki/obsidian-iconize#588]
**Describe the bug**
After downloading the new update for obsidian, the Iconize plugin is a bit glitched out, on one device (my android), the icons are working beautifully as seen in the **Expected Behaviour** part of this description, however my computer, it does not work and instead just states (ignore the homepage error message needed an update for it) "error with obsidian-icon-folder" I've checked the folder and the files and the JS script but I couldnt find anything, I went to developer mode just to check out what could be causing the problem and I think it is a problem with the script (NOT ENTIRELY SURE!!) especially the undefined value - stated in the console - with the "itemDoms.get(item)" part of the script (line 5411)

I know this is not a problem with the syncing, I sync the exact same files on both devices and I tried deleting the files for the iconize plugin and reinstall but to no avail. If there was a syncing fail then both would do the exact same thing

The problem has seems to not fix itself and I do not know what to do since everytime I add a new icon, it does not show on my computer but shows on my phone and just states the same error, it also shows the icon has been added but only on the folders that I have embedded into others or used Dataview plugin

[Edit] Works in a empty vault don't know why

**To Reproduce**
Not sure, downloaded new obsidian update and then the issue came

**Expected behaviour**

![Screenshot_20241017_181439_Obsidian](https://github.com/user-attachments/assets/a195272e-4d74-48f2-b304-9060280c10e7)

**Screenshots**
![Screenshot from 2024-10-17 18-03-25](https://github.com/user-attachments/assets/4455b79a-0d17-4566-a0e5-de09ddb405c6)
![Screenshot from 2024-10-17 18-11-16](https://github.com/user-attachments/assets/d897fe04-bfe7-463d-9be4-15c8c8d2933d)
![Screenshot from 2024-10-17 18-15-56](https://github.com/user-attachments/assets/3cb48d30-f7e3-48cb-8c45-edd5b5269d53)
![Screenshot from 2024-10-17 18-35-12](https://github.com/user-attachments/assets/0c220118-488e-413e-97f0-2304f2e7b538)

**Additional context**

**Comment by MATrsx** [comment]
+1 Same issue here

**Comment by CatapultTV** [comment]
https://github.com/user-attachments/assets/d3626e4b-0288-4f0d-81be-3fd38265471b

Im not sure but this keeps happening when I try to use the plugin now

**Comment by MATrsx** [comment]
This issue is already known. The current workaround is to disable the Obsidian bookmark plugin. For more information view this issue: https://github.com/FlorianWoelki/obsidian-iconize/issues/566

**Comment by CatapultTV** [comment]
Interesting I'll take a look I haven't seen this , I'm sorry
