### ISSUE TITLE
Failed to load plugin "obsidian-icon-folder"

### ISSUE THREAD

**Issue by lbacigal** [FlorianWoelki/obsidian-iconize#593]
Upon opening my vault, I got that error. I checked for plugin updates, updated what I could, restarted it, & still got the same error. I disabled it and tried enabling it, but I get the same error when I try to enable it. Even upon uninstalling it and reinstalling it, I still get that error.

**Comment by FlorianWoelki** [comment]
Seems like it is related to #566.
