### ISSUE TITLE
Obsidian v1.7.4 | Error during the Iconize loading and the folder and file icons are not displayed anymore

### ISSUE THREAD

**Issue by Rivol0gY** [FlorianWoelki/obsidian-iconize#594]
**Describe the bug**
Since the update to Obsidian v1.7.4, I got a loading error during the Obsidian startup and the folder icons are not displayed anymore.

**To Reproduce**
1. Update to the last version of Obsidian
2. Start it... 
4. See error in the Obsidian Developer Console:
loading iconize
app.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'get')
    at retrieveLookupItem (plugin:obsidian-icon-folder:5411:41)
    at eval (plugin:obsidian-icon-folder:5430:13)
    at Array.forEach (<anonymous>)
    at BookmarkInternalPlugin.computeNodesWithPath (plugin:obsidian-icon-folder:5429:15)
    at BookmarkInternalPlugin.onMount (plugin:obsidian-icon-folder:5435:14)
    at eval (plugin:obsidian-icon-folder:6603:32)
    at Array.forEach (<anonymous>)
    at IconizePlugin.handleChangeLayout (plugin:obsidian-icon-folder:6601:38)
    at eval (plugin:obsidian-icon-folder:6458:82)
    at e.tryTrigger (app.js:1:722881)

**Expected behavior**
As before... that the folder and file icons are displayed. If I change the workspace, it may end up by working but the behavior is random.

**Comment by I-Pch** [comment]
It's has been reported already https://github.com/FlorianWoelki/obsidian-iconize/issues/566 and is currently being worked on 😊... 
It might be fixed already https://github.com/FlorianWoelki/obsidian-iconize/issues/566#issuecomment-2421796861, the fix hasn't been released yet 😊

**Comment by bonfiresh** [comment]
also, icons not display on outline on mobile device, since obsidian v1.7.4

**Comment by AlvinPix** [comment]
I have the same problem, the plugin configuration has been corrupted after the obsidian update.

**Comment by Rivol0gY** [comment]
> It's has been reported already > #566 and is currently being worked on 😊...
> 
> It might be fixed though > [#566 (comment)](https://github.com/FlorianWoelki/obsidian-iconize/issues/566#issuecomment-2421796861) 🍀 ... but the fix hasn't been publicly released just yet 😊 ...

Thanks for the feedback. I thought it was only with the latest release so I didn't go back so far.
Really sorry for the duplicate...

**Comment by FlorianWoelki** [comment]
I'll close this one for now :) #566
