### ISSUE TITLE
Error activating extension

### ISSUE THREAD

**Issue by XanderL2** [FlorianWoelki/obsidian-iconize#595]
**Describe the bug**
It tells me that the obsidian plugin could not be loaded. This happened after an Obsidian update. Any solution? :(

![image](https://github.com/user-attachments/assets/40429ef1-35f4-4cd6-ae6b-94c23647640d)

**Comment by FlorianWoelki** [comment]
See #566 for more details. You need to disable the bookmarks for Iconize to work. However, a fix has already been made and will be released in the next few days.

Closing due to duplicate.
