### ISSUE TITLE
Show Icons in Obsidian Publish

### ISSUE THREAD

**Issue by mishozghuladze** [FlorianWoelki/obsidian-iconize#60]
**Is your feature request related to a problem? Please describe.**
I wouldn't call it a problem, more like a wish.

**Describe the solution you'd like**
I'd like the folder icons to show on Publish.

**Describe alternatives you've considered**
Manual CSS wizardry.

**Additional context**
Love your work!

**Comment by FlorianWoelki** [comment]
Thank you for your feature request. Can you please elaborate a bit more on "publish"? Is it a plugin?

**Comment by mishozghuladze** [comment]
Umm, no I mean the official Obsidian Publish functionality.

https://obsidian.md/publish

**Comment by FlorianWoelki** [comment]
Oh I got it. I am sorry, I am not using the publish functionality. Can you maybe elaborate more on what is missing in the published version?

**Comment by mishozghuladze** [comment]
The icons are just not showing up. Here are the screenshots of the published and non-published versions of the same vault.

![image](https://user-images.githubusercontent.com/77275677/162636133-50ac2c78-87ae-4f5f-b83e-5622fec7e380.png)
![image](https://user-images.githubusercontent.com/77275677/162636148-84696bdc-eecd-4922-abd0-ec6791bdb62e.png)

**Comment by FlorianWoelki** [comment]
Do you have an example page I can investigate?

**Comment by mishozghuladze** [comment]
Oops, missed the notification. Sorry for the late reply. Yea, here - https://mishozghuladze.com/001+Index

It's WIP so don't pay attention to the content xD

**Comment by FlorianWoelki** [comment]
No worries, I don't judge it :D 
It seems like the icons are not even added to the DOM. Because I don't have Obsidian Publish, I cannot really fix or investigate it further.

**Comment by vasilecampeanu** [comment]
> No worries, I don't judge it :D
> It seems like the icons are not even added to the DOM. Because I don't have Obsidian Publish, I cannot really fix or investigate it further.

Hello, I don't think that this is a bug from your side. Obsidian publish just doesn't support plugins yet.

**Comment by FlorianWoelki** [comment]
Closing for now.
