### ISSUE TITLE
Not all icons showing in selection tab

### ISSUE THREAD

**Issue by lbacigal** [FlorianWoelki/obsidian-iconize#600]
The Font Awesome pack says it has 1390 total icons, but when I try to select one for a folder, it only shows 150 total in a 5x30 grid. It does this with any pack I install, it only shows 150 of the total. Am I doing something wrong or?

![Screenshot 2024-10-22 125814](https://github.com/user-attachments/assets/13147396-a47c-402f-9004-9a9bae06a585)
![Screenshot 2024-10-22 125531](https://github.com/user-attachments/assets/ba5e8270-c62b-41eb-8e92-a40d8844bc1c)

**Comment by FlorianWoelki** [comment]
This issue has already been reported. It's a performance decision not to render all the icons inside the selector. I'll enhance this selector with #346.
