### ISSUE TITLE
Cold start Obsidian error

### ISSUE THREAD

**Issue by quanru** [FlorianWoelki/obsidian-iconize#607]
**Describe the bug**

Cold start Obsidian error occured

**To Reproduce**
Cold start Obsidian

**Expected behavior**
No error

**Screenshots**
![image](https://github.com/user-attachments/assets/bac842c3-7546-40b0-a064-235258e902e8)

**Additional context**
N/A

**Comment by FlorianWoelki** [comment]
It seems like it is an issue with the internal outline plugin in combination with Iconize.

**Comment by FlorianWoelki** [comment]
I've added a quick fix in the main branch. I've also added a setting to activate the internal plugin modifications so this does not happen again.

**Comment by FlorianWoelki** [comment]
Should be fixed with the [newest release](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.14.6).
