### ISSUE TITLE
Won't Load

### ISSUE THREAD

**Issue by LennyPhoenix** [FlorianWoelki/obsidian-iconize#608]
**Describe the bug**
Obsidian reports "failed to load plugin: 'obsidian-icon-folder'"

**Screenshots**
![image](https://github.com/user-attachments/assets/7e6ba804-c2cb-48c4-a145-c93f50c94bc3)

**Additional context**
Started erroring since recent update.

**Comment by kriss-spy** [comment]
same problem

**Comment by FlorianWoelki** [comment]
Should be fixed with the [newest release](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.14.6).
