### ISSUE TITLE
Where does iconize store info about icon packs?

### ISSUE THREAD

**Issue by Igorgro** [FlorianWoelki/obsidian-iconize#614]
I noticed the following thing: simply copying icon to .obsidian/icons/<icon-pack> folder does not make it available in the corresponding icon pack. Meanwhile adding it from settings interface from another location results in that icon being copied to the .obsidian/icons/<icon-pack> folder. After that it becomes available as the named icon in notes. Moreover if the icon is deleted from .obisidian/icons folder (while keeping original icon which was imported) and using icon name in note results in icon being restored. I tried to track changes using git and noticed that nothing is changed when adding icon to the icon pack (except obviously copying icon file to .obsidian/icons). All this means that iconize plugin stores info about installed icon packs somewhere outside of the vault. My question is the following: where does it stores this info exactly?

**Comment by Mara-Li** [comment]
You need to set it first by creating in the settings. Proper folder will be created, and you need to use the settings too in Obsidian to add icons.

**Comment by Igorgro** [comment]
I have this path set:
![image](https://github.com/user-attachments/assets/9fb96ccc-728d-4452-bdd0-bfe12e4f9334)
Or do you mean something else?

**Comment by Mara-Li** [comment]
No, sorry i was on phone so can't make screenshot!
Here: 
![image](https://github.com/user-attachments/assets/d3d0ae6d-aaf3-4b64-a66c-d5ff69c4749c)
After :
![image](https://github.com/user-attachments/assets/ab0722d0-3602-4c3c-9721-51b72f80420b)

**Comment by Igorgro** [comment]
Excuse me, did you read the original question? I'm asking about where does this setting is stored? When I add icon though this button, nothing is changed in my vault except icon copied to .obsidian/icons. When I manually copy icin to that location, it is not added to the iconize pack. That means that iconize stores wome extra information outside of vault. I'm asking, where?

**Comment by FlorianWoelki** [comment]
That's a question, not an issue nor a feature request. Please use the discussion feature of GitHub for future questions.
Nevertheless, Iconize doesn't store anything outside of the vault. However, custom icon packs and icons currently have limited support. So there might be some kind of bug.
