### ISSUE TITLE
Render icons in the outline pane

### ISSUE THREAD

**Issue by gaslit** [FlorianWoelki/obsidian-iconize#625]
Icons no longer appear in outline pane. Icons appear correctly next to the headings however.
![Obsidian v1 7 7](https://github.com/user-attachments/assets/a6eb5521-e3c6-4111-a787-bcb1afaa0702)

Exact steps:
1. Select an icon pack in the Settings>Iconize modal
2. Pop icons into the headings - works perfectly
3. Appears in the outline as mnemonics instead as shown abv

This problem also occurs with community icon packs as well .e.g. Si pack

Upon checking the issues, found out that support for icons in outline view was a feature all along :D

**Comment by FlorianWoelki** [comment]
Thank you for the report.

This is expected because the internal plugin modifications are now experimental.

Feel free to enable it by going to settings and then enable `EXPERIMENTAL: Use internal plugins`
